'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const L=require('../src/learning');
let A;try{A=require('../src/appdata-store');}catch(_){}
const empty=()=>({schema:1,snapshot:'3.2557.2',model:L.normalizeModel(),records:[]});
function packet(id){return{record:{schema:1,id,snapshot:'3.2557.2',status:'completed',mode:'Default',duration:10,trainingEnabled:true},delta:{weights:new Array(L.DIM).fill(.0001),updates:2,reward:1}};}
function harness(data=null){let revision=0,state=data;const requests=[], disk={get state(){return state;},get revision(){return revision;}};const fetch=async(url,opts={})=>{url=String(url);requests.push([url,opts]);const out=(s,j)=>({ok:s<400,status:s,json:async()=>j});
 if(url.endsWith('capabilities'))return out(200,{app:'Web Royale AI',schema:1,token:'test-token',path:'C:\\Users\\Player\\AppData\\Local\\WebRoyale\\AI',archiveLimitBytes:536870912});
 assert.equal(opts.headers['X-Web-Royale-AI'],'test-token');
 if(opts.method==='POST'){const b=JSON.parse(opts.body);if(b.revision!==revision)return out(409,{error:'revision conflict'});state=structuredClone(b.data);revision++;return out(200,{revision});}
 return out(200,{revision,data:structuredClone(state)});
 };return{fetch,requests,disk};}
function fallback(data=empty()){return {model:data.model,records:data.records,mode:'IndexedDB',persistent:true,async open(){return this;},async export(){return structuredClone(data);},async refresh(){return this.model;},async commit(p){this.model=L.mergePacket(this.model,p);return {ok:true,model:this.model};},async reset(){this.model=L.normalizeModel();}};}
test('AppData store is available as a real local/browser adapter',()=>{assert.ok(A?.AppDataLearningStore);});
test('uses AppData endpoint, migrates browser model once and commits model/record transactionally',async()=>{assert.ok(A);const data=empty();data.model=L.mergePacket(data.model,packet('legacy'));data.records=[packet('legacy').record];const h=harness(),s=new A.AppDataLearningStore({fetch:h.fetch,location:{hostname:'127.0.0.1',origin:'http://127.0.0.1:8080'},fallback:fallback(data)});await s.open();assert.equal(s.mode,'AppData');assert.match(s.path,/AppData/);assert.equal(s.model.matches,1);await s.commit(packet('new'));assert.equal(h.disk.state.model.matches,2);assert.equal(h.disk.state.records.length,2);assert.equal(s.persistent,true);const out=await s.export();assert.equal(out.scope,'local-AppData; no remote uploads');});
test('existing AppData model wins over unrelated browser model',async()=>{assert.ok(A);const disk=empty();disk.model=L.mergePacket(disk.model,packet('disk'));const local=empty();local.model.matches=999;const h=harness(disk),s=new A.AppDataLearningStore({fetch:h.fetch,location:{hostname:'localhost',origin:'http://localhost:8080'},fallback:fallback(local)});await s.open();assert.equal(s.model.matches,1);assert.equal(h.disk.revision,0);});
test('multiple tabs merge rather than overwrite and duplicate commits are idempotent',async()=>{assert.ok(A);const h=harness(empty()),opts={fetch:h.fetch,location:{hostname:'127.0.0.1',origin:'http://127.0.0.1:8080'},fallback:fallback()};const x=new A.AppDataLearningStore(opts),y=new A.AppDataLearningStore(opts);await Promise.all([x.open(),y.open()]);await Promise.all([x.commit(packet('x')),y.commit(packet('y'))]);await x.commit(packet('x'));assert.equal(h.disk.state.model.matches,2);assert.deepEqual(h.disk.state.model.seen,['x','y']);});
test('batch commit retains all model updates while raw live export retention stays bounded',async()=>{assert.ok(A);const h=harness(empty()),s=new A.AppDataLearningStore({fetch:h.fetch,location:{hostname:'127.0.0.1',origin:'http://127.0.0.1:8080'},fallback:fallback()});await s.open();await s.commitMany(Array.from({length:60},(_,i)=>packet('batch-'+i)));assert.equal(h.disk.state.model.matches,60);assert.equal(h.disk.state.model.updates,120);assert.equal(h.disk.state.records.length,40);const sent=h.requests.filter(([,o])=>o.method==='POST');assert.ok(sent.length<=2);assert.equal(JSON.parse(sent.at(-1)[1].body).archive.length,60);});
test('hosted websites keep browser storage and never probe disk endpoint',async()=>{assert.ok(A);let calls=0;const s=new A.AppDataLearningStore({fetch:async()=>{calls++;throw Error('unexpected');},location:{hostname:'example.org',origin:'https://example.org'},fallback:fallback()});await s.open();assert.equal(calls,0);assert.equal(s.mode,'IndexedDB');});
test('AppData write failure is surfaced and not silently claimed as persisted',async()=>{assert.ok(A);const h=harness(empty()),s=new A.AppDataLearningStore({fetch:h.fetch,location:{hostname:'127.0.0.1',origin:'http://127.0.0.1:8080'},fallback:fallback()});await s.open();s.fetch=async(u,o)=>o?.method==='POST'?{ok:false,status:507,json:async()=>({error:'Disk full'})}:h.fetch(u,o);await assert.rejects(s.commit(packet('full')),/Disk full|507/);assert.equal(s.persistent,false);assert.equal(h.disk.state.model.matches,0);});
test('invalid import is rejected before touching AppData',async()=>{assert.ok(A);const h=harness(empty()),s=new A.AppDataLearningStore({fetch:h.fetch,location:{hostname:'127.0.0.1',origin:'http://127.0.0.1:8080'},fallback:fallback()});await s.open();const bad=empty();bad.model.weights[0]='not number';await assert.rejects(s.import(bad),/Invalid|invalid/);assert.equal(h.disk.revision,0);});
