'use strict';
const test=require('node:test'),A=require('node:assert/strict'),N=require('../src/native');
const ID=[1,0,0,1,0,0],NO=65535;
const shape=(w=10,h=10)=>[{texture:0,xy:[[0,0],[w,0],[w,h],[0,h]],uv:[[0,0],[1,0],[1,1],[0,1]]}];
function fixture(){return new N.Scene({exports:{ground:1},matrices:[[1,0,0,1,10,20]],colors:[[0,0,0,128,255,255,255]],shapes:{5:shape(),6:shape()},clips:{1:{fps:30,frames:[[[5,NO,NO,0],[2,0,0,0],[6,NO,NO,0]]]},2:{fps:30,frames:[[[5,NO,NO,0]],[[6,NO,NO,0]]]}}},[{naturalWidth:32,naturalHeight:32}]);}
function fakeCanvas(w=800,h=1000){let m=[...ID],stack=[];const cv={width:w,height:h},c={canvas:cv,globalAlpha:1,globalCompositeOperation:'source-over',draws:[],save(){stack.push({m:[...m],alpha:this.globalAlpha,blend:this.globalCompositeOperation});},restore(){const s=stack.pop();m=s.m;this.globalAlpha=s.alpha;this.globalCompositeOperation=s.blend;},transform(...v){m=N.mul(m,v)},getTransform(){const[a,b,c,d,e,f]=m;return{a,b,c,d,e,f}},setTransform(...v){m=v.length===1?['a','b','c','d','e','f'].map(k=>v[0][k]):v},scale(x,y){this.transform(x,0,0,y,0,0)},translate(x,y){this.transform(1,0,0,1,x,y)},drawImage(...x){this.draws.push(x)},beginPath(){},moveTo(){},lineTo(){},closePath(){},clip(){},clearRect(){},fillRect(){}};cv.getContext=()=>c;return cv;}
function withDOM(fn){const previous=global.document;global.document={createElement:()=>fakeCanvas()};try{return fn()}finally{global.document=previous}}
function lib(){const s=fixture(),a={id:'one',scene:'arena',export:'ground',objects:[]};const l=new N.Library({arenas:[a,{...a,id:'two'}],scenes:{},units:{}},{});l.scenes.arena=s;l.ready=true;return {l,s};}
test('arena planner separates still ground from moving children in painter order',()=>{const s=fixture();A.equal(typeof s.arenaParts,'function');const p=s.arenaParts('ground');A.deepEqual(p.map(o=>[o.id,o.dynamic]),[[5,false],[2,true],[6,false]]);A.deepEqual(p[1].m,[1,0,0,1,10,20]);A.deepEqual(p[1].color,[0,0,0,128,255,255,255]);});
test('low/background still mode retains a single frozen root',()=>{const s=fixture();A.equal(typeof s.arenaParts,'function');const p=s.arenaParts('ground',false);A.equal(p.length,1);A.equal(p[0].dynamic,false);A.equal(p[0].id,1);});
test('explicit frame never advances its descendants',()=>{const s=fixture();A.equal(typeof s.arenaParts,'function');const p=s.arenaParts('ground',true,0);A.equal(p.length,1);A.equal(p[0].frame,0);A.equal(p[0].dynamic,false);});
test('masked one-frame assembly is not split across its mask',()=>{const s=fixture();s.data.modifiers={5:38};A.equal(typeof s.arenaParts,'function');const p=s.arenaParts('ground');A.equal(p.length,1);A.equal(p[0].id,1);A.equal(p[0].dynamic,true);});
test('animated root remains intact instead of freezing its own timeline',()=>{const s=fixture();A.equal(typeof s.arenaParts,'function');const p=s.arenaParts(2);A.equal(p.length,1);A.equal(p[0].id,2);A.equal(p[0].dynamic,true);});
test('arena offscreen shapes are culled before rasterization',()=>{const s=fixture(),c=fakeCanvas().getContext();let n=0;s.coloredShape=()=>{n++;return {image:{},x:0,y:0,w:10,h:10}};c.translate(2000,2000);s.draw(c,5,0,{arena:true});A.equal(n,0);A.equal(c.draws.length,0);});
test('non-arena paths retain their ordinary rasterization behavior',()=>{const s=fixture(),c=fakeCanvas().getContext();let n=0;s.coloredShape=()=>{n++;return {image:{},x:0,y:0,w:10,h:10}};c.translate(2000,2000);s.draw(c,5);A.equal(n,1);});
test('huge untinted arena shapes draw directly without an oversized raster',()=>withDOM(()=>{const s=fixture(),c=fakeCanvas().getContext();s.data.shapes[5]=shape(7000,7000);s.draw(c,5,0,{arena:true});A.equal(s.cache.size,0);A.equal(c.draws.length,1);}));
test('small visible arena shapes keep the original cached raster',()=>withDOM(()=>{const s=fixture(),c=fakeCanvas().getContext();s.draw(c,5,0,{arena:true});A.equal(s.cache.size,1);A.equal(c.draws.length,1);}));
test('switching arenas releases all background raster surfaces',()=>withDOM(()=>{const {l}=lib();l.drawArena(fakeCanvas().getContext(),0);const images=[...l.arenaCache.values()].flat().filter(o=>o.image).map(o=>o.image);A.ok(images.length>0);l.setArena('two');A.equal(l.arenaCache.size,0);A.ok(images.every(i=>i.width===1&&i.height===1));}));
test('normal and overtime share the cache when their art is identical',()=>withDOM(()=>{const {l}=lib(),c=fakeCanvas().getContext();l.drawArena(c,0,false);const original=[...l.arenaCache.values()][0];l.drawArena(c,1,true);A.equal(l.arenaCache.size,1);A.equal([...l.arenaCache.values()][0],original);}));
test('normal and overtime differing art keep separate variants',()=>withDOM(()=>{const {l}=lib(),c=fakeCanvas().getContext();l.arena.objects.push({name:6,x:0,y:0,visibility:'Overtime'});l.drawArena(c,0,false);l.drawArena(c,1,true);A.equal(l.arenaCache.size,2);}));
test('still runs are not repainted on later animation frames',()=>withDOM(()=>{const {l,s}=lib(),c=fakeCanvas().getContext();let calls=0;const draw=s.draw.bind(s);s.draw=(...args)=>{calls++;return draw(...args)};l.drawArena(c,0);const initial=calls;l.drawArena(c,.4);A.equal(calls-initial,1,'only one animated child repaints');}));
test('offscreen area cache construction does not allocate negative extents',()=>withDOM(()=>{const {l}=lib(),c=fakeCanvas().getContext();const previous=global.RoyaleBattleView;global.RoyaleBattleView={worldClip:{x:9999,y:9999,width:200,height:200}};try{A.equal(l.drawArena(c,0),true);A.equal([...l.arenaCache.values()][0].filter(o=>o.image).length,0);}finally{global.RoyaleBattleView=previous}}));
test('many camera variants retain a bounded, released background cache',()=>withDOM(()=>{const {l}=lib(),c=fakeCanvas().getContext(),previous=global.RoyaleBattleView;let first=[];try{for(let i=0;i<10;i++){global.RoyaleBattleView={worldClip:{x:-i,y:-10,width:800,height:1000}};l.drawArena(c,i);if(!i)first=[...l.arenaCache.values()][0].filter(o=>o.image).map(o=>o.image);}A.ok(l.arenaCache.size<=2);A.ok(first.every(i=>i.width===1&&i.height===1));}finally{global.RoyaleBattleView=previous}}));
