'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
let A={};try{A=require('../src/assets.js')}catch(e){if(e.code!=='MODULE_NOT_FOUND')throw e;}
const manifest={revision:'abc',cards:[{id:'knight',url:'https://example.invalid/knight.png'},{id:'archers',url:'https://example.invalid/archers.png'}]};
const good='data:image/png;base64,aW1hZ2U=';
function memory(){const data=new Map();return{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k),data};}
function make(opts={}){return A.createStore({manifest,storage:memory(),fetchImage:async()=>good,decodeImage:async src=>{if(src!==good)throw new Error('bad PNG');return{image:{width:302,height:363},bounds:{x:25,y:25,width:252,height:313}};},...opts});}
test('card art module provides the store factory',()=>assert.equal(typeof A.createStore,'function'));
const featureTest=typeof A.createStore==='function'?test:test.skip;
featureTest('bundled real-image data takes priority and needs no HTTP',async()=>{const s=make({bundled:{knight:good},fetchImage:async()=>{throw new Error('network must not be used')}});await s.load('knight');assert.equal(s.get('knight').status,'ready');assert.equal(s.get('knight').source,'bundled');});
featureTest('downloaded images are cached by revision and reused offline',async()=>{const storage=memory();let calls=0;const s=make({storage,fetchImage:async()=>{calls++;return good}});await s.load('knight');const again=make({storage,fetchImage:async()=>{throw new Error('offline')}});await again.load('knight');assert.equal(again.get('knight').source,'cache');assert.equal(calls,1);});
featureTest('broken cached PNG is discarded and re-downloaded',async()=>{const storage=memory();storage.setItem(A.cacheKey(manifest.revision,'knight'),'data:image/png;base64,bad');const s=make({storage});await s.load('knight');assert.equal(s.get('knight').status,'ready');assert.equal(s.get('knight').source,'download');});
featureTest('blocked localStorage does not prevent downloaded art',async()=>{const storage={getItem(){throw Error('blocked')},setItem(){throw Error('blocked')},removeItem(){throw Error('blocked')}};const s=make({storage});await s.load('knight');assert.equal(s.get('knight').status,'ready');assert.equal(s.get('knight').persistent,false);});
featureTest('duplicate requests share one download and one decoded image',async()=>{let count=0;const s=make({fetchImage:async()=>{count++;await new Promise(r=>setTimeout(r,10));return good}});await Promise.all([s.load('knight'),s.load('knight'),s.load('knight')]);assert.equal(count,1);});
featureTest('an unavailable source is exposed as error and can be retried',async()=>{let offline=true;const s=make({fetchImage:async()=>{if(offline)throw Error('Offline');return good}});await s.load('knight');assert.equal(s.get('knight').status,'error');assert.equal(s.summary().failed,1);offline=false;await s.loadAll({retry:true});assert.equal(s.summary().ready,2);});
featureTest('retry leaves already-ready images alone',async()=>{let count=0;const s=make({fetchImage:async()=>{count++;return good}});await s.loadAll();await s.loadAll({retry:true});assert.equal(count,2);});
featureTest('failed network/decode does not cache unusable images',async()=>{const storage=memory();const s=make({storage,fetchImage:async()=>'<html>error</html>'});await s.load('knight');assert.equal(s.get('knight').status,'error');assert.equal(storage.data.size,0);});
featureTest('state notifications allow existing canvases to redraw after loading',async()=>{const s=make();const states=[];const unsub=s.subscribe(id=>states.push(s.get(id).status));await s.load('knight');assert.deepEqual(states,['loading','ready']);unsub();await s.load('archers');assert.equal(states.length,2);});
featureTest('unknown IDs cannot trigger an arbitrary fetch',async()=>{const s=make();await assert.rejects(()=>s.load('../other'),/Unknown card/);assert.equal(s.get('../other'),null);});
featureTest('fitting artwork preserves its source aspect ratio',()=>{const r=A.containRect(252,313,101,127,2);assert.ok(Math.abs(r.width/r.height-252/313)<1e-10);assert.ok(r.x>=2&&r.y>=2&&r.x+r.width<=99.001&&r.y+r.height<=125.001);});
test('local manifest maps every source card to an original PNG with no network dependency',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'assets/manifest.json'))),C=require('../src/core.js');assert.deepEqual(m.cards.map(c=>c.id),C.CARDS.map(c=>c.id));assert.equal(m.cards.length,102);assert.equal(m.revision,'uploaded-'+C.DATA.snapshot);for(const c of m.cards){assert.match(c.file,/^assets\/cards\/[a-z0-9-]+\.png$/);assert.ok(c.source);assert.equal(c.url,undefined);assert.equal(fs.readFileSync(path.join(root,c.file)).subarray(0,8).toString('hex'),'89504e470d0a1a0a');}});
