'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{webkit,devices}=require('playwright');
const out=path.resolve(process.env.MOBILE_FRAMING_QA_OUT||'docs/qa/v034/mobile-framing');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await webkit.launch({headless:true}),context=await browser.newContext({...devices['iPhone 13']}),page=await context.newPage(),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(process.env.WEB_ROYALE_URL||'http://127.0.0.1:8093');const startupLog=setInterval(()=>page.evaluate(()=>({status:document.getElementById('loadMessage')?.textContent,progress:document.getElementById('loadProgress')?.style.width})).then(s=>console.log('Mobile startup',s)).catch(()=>{}),10000);
 await page.waitForFunction(()=>globalThis.RoyaleDemo&&document.querySelector('#loading.hidden'),null,{timeout:180000}).catch(async error=>{console.error('Startup state',await page.evaluate(()=>({status:document.getElementById('loadMessage')?.textContent,progress:document.getElementById('loadProgress')?.style.width,version:globalThis.RoyaleBundle?.version})),errors);throw error;}).finally(()=>clearInterval(startupLog));
 console.log('Mobile framing: startup ready');await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.documentElement.style.setProperty('--app-safe-top','59px');document.documentElement.style.setProperty('--app-safe-bottom','34px');dispatchEvent(new Event('resize'));});
 const menuWidth=await page.locator('#viewport').evaluate(e=>e.getBoundingClientRect().width);
 await page.evaluate(async()=>{await RoyaleDemo.startBattle('Default',true,{seed:3401});RoyaleDemo.battle.ai=false;RoyaleDemo.battle.paused=true;});console.log('Mobile framing: battle ready');
 async function geometry(){return page.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}},s=document.getElementById('stage'),v=document.getElementById('viewport'),vr=rect(v),f=RoyaleCore.fitViewport(s.clientWidth,s.clientHeight);return{stage:rect(s),view:vr,hand:rect(document.querySelector('.hand-panel')),mode:RoyaleBattleView.mode,height:RoyaleBattleView.layout.height,expectedWidth:f.width,canvasHeight:parseFloat(getComputedStyle(document.getElementById('battleCanvas')).height),towers:RoyaleDemo.battle.towers.map(t=>{const p=RoyaleBattleView.toScreen(t);return{x:vr.x+p.x*vr.width/540,y:vr.y+p.y*vr.height/RoyaleBattleView.layout.height}}),overflow:document.documentElement.scrollWidth>innerWidth};});}
 for(const [w,h,top,bottom]of [[390,844,59,34],[390,664,0,0],[375,667,20,0],[375,547,0,0],[844,390,0,21]]){
  await page.setViewportSize({width:w,height:h});await page.evaluate(({top,bottom})=>{document.documentElement.style.setProperty('--app-safe-top',top+'px');document.documentElement.style.setProperty('--app-safe-bottom',bottom+'px');dispatchEvent(new Event('resize'));},{top,bottom});await page.waitForTimeout(750);
  const g=await geometry();assert.equal(g.mode,'compact');assert.equal(g.height,960);assert.equal(g.canvasHeight,960);assert(Math.abs(g.view.width-g.expectedWidth)<.1,'Battle width equals menu width');assert(g.view.x>=g.stage.x-.1&&g.view.right<=g.stage.right+.1&&g.view.y>=g.stage.y-.1&&g.view.bottom<=g.stage.bottom+.1);assert(!g.overflow);
  assert.equal(g.towers.length,6);assert(g.towers.every(t=>t.y>g.view.y&&t.y<g.hand.y),'All six tower anchors above the hand');assert(g.hand.bottom<=g.view.bottom+.1,'Complete hand fits');checks.push({size:[w,h],geometry:g});await page.screenshot({path:path.join(out,`battle-${w}x${h}.png`)});
 }
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.documentElement.style.setProperty('--app-safe-top','59px');document.documentElement.style.setProperty('--app-safe-bottom','34px');dispatchEvent(new Event('resize'));RoyaleDemo.battle.paused=false;RoyaleDemo.battle.elixir[0]=10;RoyaleDemo.refreshHand(true);});
 assert(Math.abs((await geometry()).view.width-menuWidth)<.1);
 const slot=await page.evaluate(()=>RoyaleDemo.battle.hand[0].findIndex(id=>RoyaleCore.CARD_BY_ID[id].kind==='Troop'));assert(slot>=0);await page.locator(`.hand-card[data-slot="${slot}"]`).tap();assert.equal(await page.evaluate(()=>RoyaleDemo.selected),slot);
 async function worldTap(x,y){const p=await page.evaluate(({x,y})=>{const q=RoyaleBattleView.toScreen({x,y}),r=document.getElementById('viewport').getBoundingClientRect();return{x:r.x+q.x*r.width/540,y:r.y+q.y*r.height/RoyaleBattleView.layout.height}},{x,y});await page.touchscreen.tap(p.x,p.y);}
 await worldTap(110,420);await page.evaluate(()=>RoyaleDemo.battle.paused=true);assert(await page.evaluate(()=>RoyaleDemo.battle.units.some(u=>u.team===0&&Math.abs(u.x-110)<35&&Math.abs(u.y-420)<35)),'Real hand touch deploys near the requested world position');
 await page.evaluate(()=>{const b=RoyaleDemo.battle;b.finish(0,'Framing check');});await page.locator('#matchEnd').waitFor({state:'visible'});await page.locator('#endOk').waitFor({state:'visible'});
 const result=await page.locator('#endOk').boundingBox(),view=await page.locator('#viewport').boundingBox();assert(result.y>=view.y&&result.y+result.height<=view.y+view.height);await page.screenshot({path:path.join(out,'result-phone.png')});await page.locator('#endOk').tap();
 await page.locator('#home>.sandbox-launch').tap();await page.waitForFunction(()=>RoyaleDemo.sandboxUI.ready);await page.locator('#sandboxPause').tap();await page.locator('#sandboxCard').selectOption('baby-dragon');await page.waitForFunction(()=>RoyaleDemo.sandboxUI.ready);await page.locator('#sandboxTargets').check();await worldTap(160,420);
 assert(await page.evaluate(()=>RoyaleDemo.battle.units.some(u=>u.entity==='BabyDragon'&&Math.abs(u.x-160)<1&&Math.abs(u.y-420)<1)),'Sandbox uses the same camera and inverse touch mapping');
 const contained=await page.evaluate(()=>{const p=document.querySelector('.sandbox-controls').getBoundingClientRect();return[...document.querySelectorAll('.sandbox-controls button,.sandbox-controls select,.sandbox-controls input')].every(e=>{const r=e.getBoundingClientRect();return r.left>=p.left-.1&&r.right<=p.right+.1&&r.top>=p.top-.1&&r.bottom<=p.bottom+.1})});assert(contained,'Sandbox controls fit the compact hand lane');await page.screenshot({path:path.join(out,'sandbox-phone.png')});
 await page.locator('[data-action="sandbox-towers"]').tap();await page.screenshot({path:path.join(out,'sandbox-towers-phone.png')});const towerBox=await page.locator('#sandboxTowers').boundingBox(),frame=await page.locator('#viewport').boundingBox();assert(towerBox.y>=frame.y&&towerBox.y+towerBox.height<=frame.y+frame.height);
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({browser:browser.version(),emulation:'Desktop WebKit with iPhone13 touch profile and synthetic safe insets; not physical iOS',checks,touch:true,result:true,sandbox:true,errors},null,2));console.log('Mobile framing: menu width parity, full world/hand, touch, result, sandbox and rotations pass.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
