const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('../src/core.js');
const advance=(b,s)=>{for(let i=0;i<Math.ceil(s*60);i++)b.step(1/60)};
test('viewport contract exists',()=>assert.equal(typeof C.fitViewport,'function'));
for(const [w,h] of [[1920,1080],[1280,720],[3440,1440],[768,1024],[390,844],[540,960],[280,300]]){
 test(`9:16 centered contain at ${w}x${h}`,()=>{const v=C.fitViewport(w,h);assert.ok(Math.abs(v.width/v.height-9/16)<1e-10);assert.ok(v.width<=w+.001&&v.height<=h+.001);assert.equal(v.x,(w-v.width)/2);assert.equal(v.y,(h-v.height)/2)})
}
test('invalid viewport sizes are rejected',()=>{assert.throws(()=>C.fitViewport(0,900));assert.throws(()=>C.fitViewport(NaN,900))});
test('coordinates exclude black bars and map center',()=>{assert.equal(C.pointInViewport(0,500,1920,1080),null);const p=C.pointInViewport(960,540,1920,1080);assert.equal(p.x,270);assert.equal(p.y,480)});
test('profile validates malformed saves and persists lane memory',()=>{const p=C.normalizeProfile({matches:-1,trophies:NaN,gold:Infinity,laneCounts:[8,4],history:'bad'});assert.equal(p.matches,0);assert.equal(p.trophies,1000);assert.equal(p.gold,2500);assert.deepEqual(p.laneCounts,[8,4]);assert.deepEqual(p.history,[])});
test('102 cards, unique eight-card deck, four-card hand and four-card queue',()=>{assert.equal(C.CARDS.length,102);const b=new C.Battle({ai:false});assert.equal(b.hand[0].length,4);assert.equal(b.queue[0].length,4);assert.equal(new Set([...b.hand[0],...b.queue[0]]).size,8)});
test('uses source starting elixir, spends once, cycles played card to queue tail',()=>{const b=new C.Battle({ai:false});const id=b.hand[0][0],next=b.queue[0][0];const cost=C.CARD_BY_ID[id].cost;assert.equal(b.elixir[0],C.DATA.timelines.Default.StartingElixir);assert.ok(b.deploy(0,0,90,410).ok);assert.equal(b.elixir[0],C.DATA.timelines.Default.StartingElixir-cost);assert.equal(b.hand[0][0],next);assert.equal(b.queue[0].at(-1),id)});
test('deployment rejects enemy half, tower footprints, NaN and invalid hand slot',()=>{const b=new C.Battle({ai:false});assert.equal(b.deploy(0,0,80,100).ok,false);assert.equal(b.deploy(0,0,b.towers.find(t=>t.team===0&&!t.king).x,b.towers.find(t=>t.team===0&&!t.king).y).ok,false);assert.equal(b.deploy(0,0,NaN,450).ok,false);assert.equal(b.deploy(0,8,80,410).ok,false);assert.equal(b.units.length,0);assert.equal(b.elixir[0],C.DATA.timelines.Default.StartingElixir)});
test('insufficient elixir never cycles or deploys',()=>{const b=new C.Battle({ai:false});b.elixir[0]=0;const hand=[...b.hand[0]];assert.equal(b.deploy(0,0,80,400).reason,'Not enough elixir');assert.deepEqual(b.hand[0],hand);assert.equal(b.units.length,0)});
test('archers spawn as a pair',()=>{const b=new C.Battle({ai:false});b.hand[0][0]='archers';assert.ok(b.deploy(0,0,80,410).ok);assert.equal(b.units.length,2)});
test('spells can hit enemy territory and deal reduced tower damage',()=>{const b=new C.Battle({ai:false});b.hand[0][0]='fireball';b.elixir[0]=10;const t=b.towers[1];const hp=t.hp;assert.ok(b.deploy(0,0,t.x,t.y).ok);advance(b,4);assert.ok(t.hp<hp);assert.equal(hp-t.hp,Math.floor(C.CARD_BY_ID.fireball.damage*(100+C.DATA.projectiles.FireballSpell.CrownTowerDamagePercent)/100))});
test('elixir regenerates at normal and double rates, capped at ten',()=>{const b=new C.Battle({ai:false});b.elixir[0]=0;advance(b,2.8);assert.ok(Math.abs(b.elixir[0]-1)<.01);b.time=121;const e=b.elixir[0];advance(b,2.8);assert.ok(Math.abs(b.elixir[0]-e-2)<.01);advance(b,60);assert.equal(b.elixir[0],10)});
test('pause freezes rules and deployment',()=>{const b=new C.Battle({ai:false});b.paused=true;const t=b.time;advance(b,3);assert.equal(b.time,t);assert.equal(b.deploy(0,0,80,420).ok,false)});
test('king destruction yields three crowns and one final result',()=>{const b=new C.Battle({ai:false});b.towers.find(t=>t.team===1&&t.king).hp=0;b.step(1/60);assert.equal(b.result.winner,0);assert.equal(b.crowns[0],3);const r=b.result;advance(b,2);assert.equal(b.result,r)});
test('regulation crown lead wins; ties enter overtime',()=>{let b=new C.Battle({ai:false});b.towers.find(t=>t.team===1&&!t.king).hp=0;b.step(1/60);b.time=179.99;b.step(.02);assert.equal(b.result.winner,0);b=new C.Battle({ai:false});b.time=179.99;b.step(.02);assert.equal(b.overtime,true);assert.equal(b.result,null)});
test('overtime next crown ends the match',()=>{const b=new C.Battle({ai:false});b.time=181;b.overtime=true;b.towers.find(t=>t.team===1&&!t.king).hp=0;b.step(.02);assert.equal(b.result.winner,0)});
test('equal tiebreak towers create a draw',()=>{const b=new C.Battle({ai:false});b.overtime=true;b.time=299.99;b.step(.02);assert.equal(b.result.winner,-1)});
test('troops path through a bridge rather than the river',()=>{const b=new C.Battle({ai:false});b.elixir[0]=10;b.deploy(0,0,230,365);let crossed=false;for(let i=0;i<2400&&!b.result;i++){b.step(1/60);for(const u of b.units){if(u.team===0&&u.y>303&&u.y<337){crossed=true;assert.ok(Math.min(Math.abs(u.x-3.5*C.SX),Math.abs(u.x-14.5*C.SX))<=30)}}}assert.ok(crossed)});
test('practice opponent plays using real elixir and hand',()=>{const b=new C.Battle({seed:1});advance(b,15);assert.ok(b.played[1]>0);assert.ok(b.elixir[1]>=0&&b.elixir[1]<=10);assert.equal(new Set([...b.hand[1],...b.queue[1]]).size,8)});
test('result updates profile once, history is bounded and losses clamp trophies',()=>{let p=C.normalizeProfile();let b=new C.Battle({ai:false});b.result={winner:0,reason:'King tower',time:20};b.laneCounts=[4,1];let q=C.applyResult(p,b);assert.equal(q.matches,1);assert.equal(q.wins,1);assert.equal(q.trophies,p.trophies+30);assert.deepEqual(q.laneCounts,[5,2]);assert.equal(q.history.length,1)});
test('bounded step rejects negative or nonfinite time',()=>{const b=new C.Battle({ai:false});b.step(NaN);b.step(-1);assert.equal(b.time,0)});
test('king artwork and health fit below HUD and above hand',()=>{const b=new C.Battle({ai:false});for(const t of b.towers.filter(t=>t.king)){assert.ok(t.y+110-83>=81,'crown must not be obscured by the header');assert.ok(t.y+110+52<=794,'health must stay above the hand')}});
test('repeated result processing cannot duplicate rewards',()=>{const b=new C.Battle({ai:false});b.result={winner:0,reason:'Test'};const p=C.applyResult(C.normalizeProfile(),b);assert.deepEqual(C.applyResult(p,b),p)});
test('history sanitization cannot inject markup or nonnumeric crowns',()=>{const p=C.normalizeProfile({history:[{winner:0,crowns:['<svg>',Infinity],duration:'bad'},{winner:99}]});assert.equal(p.history.length,1);assert.deepEqual(p.history[0].crowns,[0,0])});
test('an unattended match ends naturally with a bot victory',()=>{const b=new C.Battle({seed:1});advance(b,180);assert.ok(b.result);assert.equal(b.result.winner,1);assert.equal(b.crowns[1],3)});
