'use strict';
const test=require('node:test'),A=require('node:assert/strict'),C=require('../src/core');
function pair(){const b=new C.Battle({ai:false});const a=b.spawn('Knight',0,240,370,{wait:0});const t=b.spawn('Knight',1,240,350,{wait:1});return {b,a,t};}
test('v110: deployment is an action delay, not target immunity',()=>{const {b,a,t}=pair();A.equal(b.canTarget(a,t),true);A.equal(b.chooseTarget(a).id,t.id);});
test('v110: a deploying troop can be killed before acting',()=>{const {b,a,t}=pair();const initial=a.hp;t.hp=1;b.damage(t,50,a);b.step(1/60);A.ok(!b.getEntity(t.id));A.equal(a.hp,initial);});
test('v110: splash and spell areas hit deploying troops',()=>{const {b,t}=pair(),hp=t.hp;b.hitArea({team:0,x:t.x,y:t.y,damage:100,radius:2,ground:true,air:true});A.equal(t.hp,hp-100);const area=b.createArea('Freeze',0,t.x,t.y,9);A.ok(b.areaTargets(area).some(x=>x.id===t.id));});
test('v110: line projectiles hit deploying troops',()=>{const {b,t}=pair(),hp=t.hp;const a=b.spawn('Bowler',0,240,395,{wait:0});b.fireProjectile('BowlerProjectile',a,t);for(let i=0;i<18;i++)b.step(1/60);A.ok(t.hp<hp);});
test('v110: delayed spawns are not visible or targetable before their appearance time',()=>{const {b,a}=pair();const t=b.spawn('Knight',1,240,350,{wait:2,appearsIn:1});A.equal(b.isPresent(t),false);A.equal(b.canTarget(a,t),false);b.time=1.2;A.equal(b.isPresent(t),true);A.equal(b.canTarget(a,t),true);});
test('v110: deployment keeps movement and attack disabled',()=>{const {b,a,t}=pair();a.hp=10000;const x=t.x,y=t.y;for(let i=0;i<20;i++)b.step(1/60);A.equal(t.x,x);A.equal(t.y,y);A.equal(t.lastAttackAt,-Infinity);});
test('v110: deployment preview reports real range and enemy aggro without mutation',()=>{const {b}=pair();b.hand[0]=['musketeer','knight','fireball','mortar'];const before=JSON.stringify({units:b.units,events:b.events,hand:b.hand,next:b.nextId});const p=b.placementPreview(0,0,260,360);A.equal(p.ok,true);A.equal(p.range,C.entityDef('Musketeer',9).range);A.ok(p.attackers.length);A.equal(JSON.stringify({units:b.units,events:b.events,hand:b.hand,next:b.nextId}),before);});
test('v110: preview respects locked targets and air/ground capability',()=>{const b=new C.Battle({ai:false});b.hand[0]=['balloon','knight','fireball','mortar'];const knight=b.spawn('Knight',1,250,355,{wait:0});const m=b.spawn('Musketeer',1,230,355,{wait:0});const p=b.placementPreview(0,0,240,360);A.ok(!p.attackers.some(a=>a.id===knight.id));A.ok(p.attackers.some(a=>a.id===m.id));});
