'use strict';
const test=require('node:test'),A=require('node:assert/strict'),L=require('../src/learning');
let Store;try{Store=require('../src/learning-store').LearningStore;}catch(e){if(e.code!=='MODULE_NOT_FOUND')throw e;}
test('v110: shared learning store exists',()=>A.equal(typeof Store,'function'));
const T=Store?test:test.skip;
const packet=id=>({record:{schema:1,snapshot:L.normalizeModel().snapshot,id,mode:'Default',status:'completed',duration:10,result:{winner:0},commands:[],events:[],transitions:[],snapshots:[]},delta:{weights:Array(L.DIM).fill(.01),updates:3,reward:2}});
T('learning model survives repository recreation and all match IDs deduplicate',async()=>{const mem=new Map(),storage={getItem:k=>mem.get(k),setItem:(k,v)=>mem.set(k,v),removeItem:k=>mem.delete(k)};let s=new Store({storage,indexedDB:null});await s.open();await s.commit(packet('a'));await s.commit(packet('a'));A.equal(s.model.matches,1);s=new Store({storage,indexedDB:null});await s.open();A.equal(s.model.updates,3);await s.commit(packet('b'));A.equal(s.model.matches,2);A.equal((await s.export()).records.length,2);});
T('bounded retention keeps cumulative learning but only recent raw matches',async()=>{const s=new Store({indexedDB:null,maxRecords:3});await s.open();for(let i=0;i<8;i++)await s.commit(packet('m'+i));const out=await s.export();A.equal(out.model.matches,8);A.equal(out.records.length,3);});
T('blocked storage remains usable and explicitly reports session-only mode',async()=>{const s=new Store({indexedDB:null,storage:{getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}}});await s.open();await s.commit(packet('x'));A.equal(s.persistent,false);A.ok(s.error);A.equal(s.model.matches,1);});
T('invalid imports cannot replace a valid model',async()=>{const s=new Store({indexedDB:null});await s.open();await s.commit(packet('a'));await A.rejects(()=>s.import({schema:1,snapshot:'999',model:{},records:[]}));A.equal(s.model.matches,1);await A.rejects(()=>s.import({schema:1,snapshot:s.model.snapshot,model:{...s.model,weights:Array(L.DIM).fill(Infinity)},records:[]}));A.equal(s.model.matches,1);});
T('resetting learning does not touch the game profile save key',async()=>{const m=new Map([['web-royale-classic-v4','KEEP']]),s=new Store({indexedDB:null,storage:{getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}});await s.open();await s.commit(packet('a'));await s.reset();A.equal(m.get('web-royale-classic-v4'),'KEEP');A.equal(s.model.matches,0);});
