'use strict';
const test=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../src/core.js'),root=path.resolve(__dirname,'..');
function ui(){const f=path.join(root,'src/menu-model.js');A.ok(fs.existsSync(f),'Reference-menu model is missing');return require(f);}
test('reference menus preserve the classic roster and level cap',()=>{const U=ui();A.equal(U.snapshot,C.DATA.snapshot);A.equal(U.maxLevel,13);A.equal(U.cardCount,102);});
test('deck slot swaps preserve unique cards and do not mutate stored input',()=>{const U=ui(),d=[...C.DEFAULT_DECK],before=d.join();const next=U.swapSlots(d,0,7);A.equal(next[0],d[7]);A.equal(next[7],d[0]);A.equal(new Set(next).size,8);A.equal(d.join(),before);A.deepEqual(U.swapSlots(d,-1,2),d);A.deepEqual(U.swapSlots(d,1,99),d);});
test('collection filters use source rarity and never invent missing cards',()=>{const U=ui();A.equal(U.filterCards(C.CARDS,'','all','rarity').length,102);A.equal(U.filterCards(C.CARDS,'electro','all','name').length,4);A.ok(U.filterCards(C.CARDS,'','Legendary','rarity').every(c=>c.rarity==='Legendary'));A.equal(U.filterCards(C.CARDS,'<script>','all','name').length,0);});
test('hour shop countdown includes seconds and rolls over on the hour',()=>{const U=ui();A.equal(U.refreshIn(Date.parse('2026-09-23T12:43:00Z')),'00:17:00');A.equal(U.refreshIn(Date.parse('2026-09-23T23:59:59Z')),'00:00:01');A.equal(U.refreshIn(Date.parse('2026-09-24T00:00:00Z')),'01:00:00');});
test('new menu text is escaped before HTML rendering',()=>{const U=ui();A.equal(U.escape('<b>" &\''),'&lt;b&gt;&quot; &amp;&#39;');});
test('classic emote purchases persist, reject duplicates and insufficient gems',()=>{const U=ui();let p=C.normalizeProfile({gems:300});const r=U.purchaseEmote(p,'Emote4');A.ok(r.ok);A.equal(r.profile.gems,250);A.ok(r.profile.ownedEmotes.includes('Emote4'));A.equal(p.gems,300);A.ok(!U.purchaseEmote(r.profile,'Emote4').ok);A.ok(!U.purchaseEmote({...r.profile,gems:49},'Emote20').ok);A.ok(!U.purchaseEmote(p,'new-hero').ok);A.ok(C.normalizeProfile(r.profile).ownedEmotes.includes('Emote4'));});
test('removed gem packs cannot grant currency through former entry points',()=>{const U=ui(),p=C.normalizeProfile({gems:100});A.ok(Array.isArray(U.gemPacks));for(const id of [-1,0,6,'0']){const r=U.grantGemPack(p,id);A.equal(r.ok,false);A.equal(r.profile.gems,100);}A.equal(p.gems,100);});
test('clan posts retain safe typed emotes across saves and drop unsupported emotes',()=>{const p=C.normalizeProfile({clan:{name:'Test',messages:[{name:'Nano',text:'',kind:'emote',emote:'Emote0',bot:false},{name:'<script>',text:'hello',kind:'emote',emote:'unknown'}]}});A.equal(p.clan.messages[0].emote,'Emote0');A.equal(p.clan.messages[0].kind,'emote');A.equal(p.clan.messages[1].kind,'text');});
test('deck menu uses screenshot-style segmented tabs and a full-width OK tray',()=>{const html=fs.readFileSync(path.join(root,'src/index.template.html'),'utf8');A.match(html,/id="deckSegments"/);A.match(html,/id="cardsDone"/);A.match(html,/id="deckToolbar"/);A.match(html,/id="collectionHeader"/);});
test('screenshot chrome is not bundled as a page backdrop or phone status bar',()=>{const html=fs.readFileSync(path.join(root,'src/index.template.html'),'utf8'),s=fs.readFileSync(path.join(root,'src/app.js'),'utf8');A.ok(!/IMG_497[4-8]/.test(html+s));A.ok(!/dynamic-island|phone-statusbar/.test(html+s));});
test('clan message import tolerates null and malformed entries without losing progress',()=>{const p=C.normalizeProfile({gold:4321,clan:{name:'Team',messages:[null,0,'bad',{name:'Nano',text:'Ready',time:10}]}});A.equal(p.gold,4321);A.equal(p.clan.messages.length,1);A.equal(p.clan.messages[0].text,'Ready');});
test('clan history timestamps never display NaN for imported dates',()=>{const U=ui();A.equal(U.age(NaN),'Earlier');A.equal(U.age(0,60000),'1min ago');});
