'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),http=require('node:http'),net=require('node:net'),path=require('node:path'),fs=require('node:fs'),zlib=require('node:zlib');
const root=path.resolve(__dirname,'..'),release=require('../dist/release.json');let port,child;
before(async()=>{const socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));port=socket.address().port;await new Promise(r=>socket.close(r));child=spawn(process.execPath,['tools/serve.cjs'],{cwd:root,env:{...process.env,PORT:String(port)},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server startup timeout')),10000);child.stdout.on('data',b=>{if(b.toString().includes('Web Royale:')){clearTimeout(timer);resolve();}});child.on('error',e=>{clearTimeout(timer);reject(e);});child.on('exit',code=>{if(code)reject(Error('Server exited '+code));});});});
after(()=>{if(child)child.kill();});
function request(name='/',method='GET',headers={}){return new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port,path:name,method,headers},res=>{const chunks=[];res.on('data',x=>chunks.push(x));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:Buffer.concat(chunks)}));});req.on('error',reject);req.end();});}
test('static host serves the exact web entry with restrictive headers',async()=>{const r=await request();assert.equal(r.status,200);assert.deepEqual(r.body,fs.readFileSync(path.join(root,'dist/index.html')));assert.equal(r.headers['x-content-type-options'],'nosniff');assert.match(r.headers['content-security-policy'],/script-src 'self'/);assert.equal(r.headers['cache-control'],'no-cache');});
test('hashed scripts have immutable cache headers and gzip round trips',async()=>{const r=await request('/'+release.app,'GET',{'Accept-Encoding':'gzip'});assert.equal(r.status,200);assert.equal(r.headers['content-encoding'],'gzip');assert.match(r.headers['cache-control'],/immutable/);assert.deepEqual(zlib.gunzipSync(r.body),fs.readFileSync(path.join(root,'dist',release.app)));});
test('HEAD returns file length without the body',async()=>{const r=await request('/index.html','HEAD');assert.equal(r.status,200);assert.equal(r.body.length,0);assert.equal(Number(r.headers['content-length']),fs.statSync(path.join(root,'dist/index.html')).size);});
test('static host rejects writes and cannot expose parent source files',async()=>{assert.equal((await request('/','POST')).status,405);for(const p of ['/%2e%2e%2fpackage.json','/assets/%2e%2e%2f%2e%2e%2fsrc/app.js','/missing-file.js'])assert.equal((await request(p)).status,404,p);assert.equal((await request('/%zz')).status,400);});
test('text variants vary on accepted encoding, even when uncompressed',async()=>{const r=await request('/index.html');assert.equal(r.headers.vary,'Accept-Encoding');});
test('gzip explicitly refused by the client is not sent',async()=>{const r=await request('/index.html','GET',{'Accept-Encoding':'gzip;q=0, identity'});assert.equal(r.headers['content-encoding'],undefined);assert.deepEqual(r.body,fs.readFileSync(path.join(root,'dist/index.html')));});
test('rebuilt files invalidate compressed responses even with the same byte length',async()=>{const name='server-cache-test-'+process.pid+'.html',file=path.join(root,'dist',name);try{fs.writeFileSync(file,'<p>before</p>');const first=await request('/'+name,'GET',{'Accept-Encoding':'gzip'});assert.equal(zlib.gunzipSync(first.body).toString(),'<p>before</p>');fs.writeFileSync(file,'<p>after!</p>');const second=await request('/'+name,'GET',{'Accept-Encoding':'gzip'});assert.equal(zlib.gunzipSync(second.body).toString(),'<p>after!</p>');}finally{fs.rmSync(file,{force:true});}});
