const test=require('node:test'),A=require('node:assert/strict'),C=require('../src/core.js');
let AI;try{AI=require('../src/ai.js')}catch{AI={}}
const make=(hand,elixir=10)=>{const b=new C.Battle({ai:false});b.time=10;b.hand[1]=hand;b.elixir[1]=elixir;return b;};
const choose=b=>new AI.TacticalBot({team:1,difficulty:'expert',seed:1}).choose(AI.observe(b,1));
const spawn=(b,name,x=94,y=210)=>{const u=b.spawn(name,0,x,y,{wait:0,level:9,card:C.CARDS.find(c=>c.entity===name)?.id||name});u.born=b.time-1;return u;};
test('tactical policy exposes a restricted public observation',()=>{A.equal(typeof AI.observe,'function');const b=make(['knight','archers','fireball','giant']);const v=AI.observe(b,1);A.equal(v.team,1);A.equal(v.hand.length,4);A.equal(v.enemyHand,undefined);A.equal(v.enemyElixir,undefined);A.equal(v.queue,undefined);A.equal(v.random,undefined);A.ok(!JSON.stringify(v).includes('lastResultId'));});
test('policy does not read the opposing hand queue or exact elixir',()=>{const b=make(['knight','archers','fireball','giant']);for(const k of ['hand','queue','elixir'])Object.defineProperty(b[k],0,{get(){throw Error('Hidden '+k)}});A.doesNotThrow(()=>choose(b));});
test('invisible enemy units are absent from observation',()=>{const b=make(['knight','archers','fireball','giant']);const u=spawn(b,'Ghost');u.invisible=true;A.equal(AI.observe(b,1).enemies.length,0)});
test('waits instead of spending the starting bank without a threat',()=>{const b=make(['knight','archers','fireball','giant'],6);A.equal(choose(b),null)});
test('saves single-elixir budget for a coherent heavy opening',()=>{const b=make(['golem','night-witch','lightning','tornado'],8);A.equal(choose(b),null)});
test('avoids leaking at full elixir',()=>{const b=make(['knight','archers','fireball','giant'],10);const a=choose(b);A.ok(a);A.ok(!C.CARD_BY_ID[b.hand[1][a.slot]].spell);A.equal(b.placement(1,b.card(1,a.slot),a.x,a.y).ok,true)});
test('selects anti-air instead of a ground-only counter against Balloon',()=>{const b=make(['knight','musketeer','bomber','giant'],7);spawn(b,'Balloon',94,205);const a=choose(b);A.ok(a);A.equal(b.hand[1][a.slot],'musketeer')});
test('uses splash against a clustered skeleton swarm',()=>{const b=make(['mini-pekka','bomber','giant','ice-golem'],7);for(let i=0;i<10;i++)spawn(b,'Skeleton',90+(i%3)*8,205+Math.floor(i/3)*6);const a=choose(b);A.ok(a);A.equal(b.hand[1][a.slot],'bomber')});
test('chooses a tank killer against a Giant',()=>{const b=make(['bomber','mini-pekka','giant','ice-golem'],7);spawn(b,'Giant',94,195);const a=choose(b);A.ok(a);A.equal(b.hand[1][a.slot],'mini-pekka')});
test('central defensive building pulls an approaching building-targeter',()=>{const b=make(['cannon','skeletons','giant','fireball'],6);spawn(b,'HogRider',94,240);const a=choose(b);A.ok(a);A.equal(b.hand[1][a.slot],'cannon');A.ok(a.x>135&&a.x<345);A.ok(a.y>=160&&a.y<290)});
test('does not use a ground-only spell against Minions',()=>{const b=make(['the-log','archers','knight','ice-golem'],6);for(let i=0;i<3;i++)spawn(b,'Minion',90+i*10,200);const a=choose(b);A.ok(a);A.equal(b.hand[1][a.slot],'archers')});
test('spells target valuable clusters rather than a naked healthy tower',()=>{const b=make(['fireball','giant','knight','ice-golem'],6);spawn(b,'Musketeer',100,215);spawn(b,'Wizard',115,220);const a=choose(b);A.ok(a);A.equal(b.hand[1][a.slot],'fireball');A.ok(Math.abs(a.x-105)<65);A.ok(Math.abs(a.y-215)<60)});
test('finishes a lethal princess tower with a damage spell',()=>{const b=make(['rocket','knight','giant','ice-golem'],6);const t=b.towers.find(t=>t.team===0&&!t.king);t.hp=100;const a=choose(b);A.ok(a);A.equal(b.hand[1][a.slot],'rocket');A.equal(a.x,t.x);A.equal(a.y,t.y)});
test('never wastes a standalone spell on a healthy sleeping king',()=>{const b=make(['rocket','fireball','arrows','zap'],10);const a=choose(b);A.equal(a,null)});
test('does not rage empty ground',()=>{const b=make(['rage','clone','freeze','heal-spirit'],4);A.equal(choose(b),null)});
test('refuses unavailable or unaffordable hand slots',()=>{const b=make(['musketeer','rocket','pekka','golem'],2);spawn(b,'Balloon');A.equal(choose(b),null);b.elixir[1]=10;b.slotReady[1]=[100,100,100,100];A.equal(choose(b),null)});
test('returns deterministic choices and reasons for a fixed observation',()=>{const b=make(['knight','archers','fireball','giant'],10);const a=choose(b),z=choose(b);A.deepEqual(a,z);A.equal(typeof a.reason,'string');A.ok(Number.isFinite(a.score))});
test('observation does not mutate the battle',()=>{const b=make(['knight','archers','fireball','giant'],10);const hp=b.towers[0].hp,v=AI.observe(b,1);v.towers[0].hp=0;A.equal(b.towers[0].hp,hp)});
test('attack policy supports either side with legal symmetric placement',()=>{const b=make(['knight','archers','fireball','giant'],10);b.elixir=[10,10];b.hand[0]=b.hand[1].slice();const a=new AI.TacticalBot({team:0}).choose(AI.observe(b,0));A.ok(a);A.ok(a.y>=340);A.ok(b.placement(0,b.card(0,a.slot),a.x,a.y).ok)});
test('public deployment costs update remembered enemy elixir without hidden reads',()=>{const bot=new AI.TacticalBot({team:1});const b=make(['knight','archers','fireball','giant'],6);bot.choose(AI.observe(b,1));b.record({type:'deploy',team:0,card:'golem',cost:8,x:94,y:520});bot.choose(AI.observe(b,1));A.ok(bot.memory.estimate<=3);A.ok(bot.memory.seen.golem);});
test('default battle uses tactical policy and still only spends legal elixir',()=>{const b=new C.Battle({seed:9});A.ok(b.bots&&b.bots[1]);for(let i=0;i<60*20;i++)b.step(1/60);A.ok(b.elixir[1]>=0&&b.elixir[1]<=10);A.ok(b.played[1]>0);A.ok(b.bots[1].decisions.length>0)});

test("fresh deployments respect the humanized observation delay",()=>{const b=make(["knight","musketeer","bomber","giant"],7);const u=spawn(b,"Balloon");u.born=b.time;A.equal(choose(b),null);});
