'use strict';
const test=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),N=require('../src/native'),L=require('../src/arena-layout');
function canvas(){const cv={width:1000,height:1400},calls=[],c={canvas:cv,calls,globalAlpha:1,save(){},restore(){},scale(){},translate(){},transform(){},beginPath(){calls.push(['beginPath'])},moveTo(...p){calls.push(['moveTo',...p])},lineTo(...p){calls.push(['lineTo',...p])},closePath(){},clip(){calls.push(['clip'])},drawImage(...p){calls.push(['drawImage',...p])},fillRect(){},clearRect(){},createLinearGradient(){return{addColorStop(){}}}};cv.getContext=()=>c;return cv;}
function withDOM(fn){const old=global.document;global.document={createElement:canvas};try{return fn()}finally{global.document=old}}
const triangle={texture:0,xy:[[2,3],[19,4],[7,29]],uv:[[.133,.004],[.133,.004],[.133,.004]]},texture={naturalWidth:1000,naturalHeight:1000};
test('cached authored flat-texel triangles retain source polygon and exact RGBA sample',()=>withDOM(()=>{const scene=new N.Scene({exports:{marks:5},matrices:[],colors:[],shapes:{5:[triangle]},clips:{}},[texture]),sh=scene.shape(5),calls=sh.image.getContext('2d').calls,draw=calls.find(c=>c[0]==='drawImage');A.ok(draw,'Authored marking triangle must paint');A.equal(draw[1],texture);A.deepEqual(draw.slice(2,6),[133,4,1,1]);A.deepEqual(draw.slice(6),[2,3,17,26]);A.deepEqual(calls.filter(c=>['moveTo','lineTo'].includes(c[0])),[['moveTo',2,3],['lineTo',19,4],['lineTo',7,29]]);A.ok(calls.some(c=>c[0]==='clip'));}));
test('direct backdrop polygons use the same flat source sample instead of a failed affine',()=>{const scene=new N.Scene({exports:{marks:5},matrices:[],colors:[],shapes:{5:[triangle]},clips:{}},[texture]),c=canvas().getContext('2d');scene.drawRawShape(c,5);const draw=c.calls.find(c=>c[0]==='drawImage');A.ok(draw);A.deepEqual(draw.slice(2,6),[133,4,1,1]);A.deepEqual(draw.slice(6),[2,3,17,26]);});
test('ordinary authored UV triangles continue through the affine image path',()=>withDOM(()=>{const shape={...triangle,uv:[[0,0],[1,0],[0,1]]},scene=new N.Scene({exports:{sprite:5},matrices:[],colors:[],shapes:{5:[shape]},clips:{}},[texture]);const draw=scene.shape(5).image.getContext('2d').calls.find(c=>c[0]==='drawImage');A.equal(draw.length,4);}));
const descriptor=JSON.parse(fs.readFileSync(path.join(__dirname,'../assets/native/data.json'),'utf8')).touchdownArena;
function arenaHarness(){
 const paints=[],canvases=[],g={arenaScale:1,arenaAnimated:true,arenaFps:30};
 function makeCanvas(){const cv=canvas(),c=cv.getContext('2d');for(const name of ['rect','fill','stroke','ellipse','bezierCurveTo','rotate','strokeRect','setTransform'])c[name]=(...args)=>c.calls.push([name,...args]);const draw=c.drawImage;c.drawImage=(...args)=>{paints.push({type:'image',image:args[0],canvas:cv});draw(...args)};canvases.push(cv);return cv;}
 const root={document:{createElement:makeCanvas},RoyaleGraphics:{current:g},RoyaleNative:N,URL,Image:class{set src(x){throw Error('Complete source stadium must not load the screenshot: '+x)}}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/custom-arena.js'),'utf8'),root);
 const lib={data:{touchdownArena:descriptor},scenes:{},preparation:1};
 for(const scene of new Set([descriptor.scene,...descriptor.objects.map(o=>o.scene)])){
  const names=new Set(descriptor.objects.filter(o=>o.scene===scene).map(o=>o.name));if(scene===descriptor.scene)for(const key of ['pitchExport','backdropExport','lightingExport','turfExport'])names.add(descriptor[key]);
  lib.scenes[scene]={id:name=>names.has(name)?name:undefined,clip:()=>({fps:24,frames:[[]]}),bounds:()=>({x:-10,y:-10,width:20,height:20}),arenaParts(name,animate,frame){return[{id:name,m:[1,0,0,1,0,0],color:null,blend:name===descriptor.lightingExport?'multiply':null,dynamic:!!animate&&frame===undefined&&/audience|flag/.test(name),frame}]},draw(c,name,time,options){paints.push({type:'source',name,time,options,canvas:c.canvas,blend:c.globalCompositeOperation})}};
 }
 return{api:root.RoyaleCustomArena,root,lib,g,paints,canvases};
}
test('source body and original white scoring lines align to unchanged normal and wide layouts',()=>{
 const h=arenaHarness();for(const id of ['Touchdown','Touchdown2v2','Touchdown3v3']){const l=L.get(id),before=JSON.stringify(l),t=h.api.sourceStadiumTransform(l,descriptor);A.ok(t);const x=v=>v*t.xScale+t.xOffset,y=v=>v*t.yScale+t.yOffset;A.ok(Math.abs(x(descriptor.field.left)-l.left*480/18)<1e-8);A.ok(Math.abs(x(descriptor.field.right)-l.right*480/18)<1e-8);A.ok(Math.abs(y(descriptor.field.goalTop)-25)<1e-8);A.ok(Math.abs(y(descriptor.field.goalBottom)-615)<1e-8);A.equal(JSON.stringify(l),before);A.ok(y(-4.833333333333333)<l.top*20);A.ok(y(636.8333333333334)>l.bottom*20);}
});
test('source readiness requires every declared scene/export; missing optional source cannot replace fallback',()=>{
 const h=arenaHarness();A.equal(h.api.sourceStadiumReady(h.lib),true);const scene=descriptor.objects.find(o=>o.scene!==descriptor.scene)?.scene;delete h.lib.scenes[scene];A.equal(h.api.sourceStadiumReady(h.lib),false);A.equal(h.api.sourceStadiumReady({data:{},scenes:{}}),false);
});
test('source stadium caches ground, keeps original crowd clocks and source blends, and holds closed hatch',async()=>{
 const h=arenaHarness(),b={arenaLayout:L.get('Touchdown3v3'),visualTime:.23};A.equal(await h.api.prepareAssets(b,'http://example.test/',h.lib),true);const cv=h.api.prepare(b,h.lib);A.equal(cv.stadiumArt,'source-stadium');const pitchPaints=h.paints.filter(p=>p.name===descriptor.pitchExport);A.equal(pitchPaints.length,1);const c=h.root.document.createElement('canvas').getContext('2d');h.paints.length=0;h.api.draw(c,b,h.lib);h.paints.push({type:'units'});h.api.drawForeground(c,b,h.lib,.23);h.api.draw(c,b,h.lib);h.api.drawForeground(c,b,h.lib,.97);A.equal(h.api.prepare(b,h.lib),cv);A.equal(h.paints.filter(p=>p.name===descriptor.pitchExport).length,0,'Pitch must not be painted again on animation ticks');const crowds=h.paints.filter(p=>p.type==='source'&&/audience|flag/.test(p.name));A.ok(crowds.length>0);A.ok(crowds.some(p=>p.time===6/30));A.ok(crowds.some(p=>p.time===29/30));A.ok(h.paints.findIndex(p=>p.type==='units')<h.paints.findIndex(p=>crowds.includes(p)),'Raised source actors draw after units');A.ok(h.paints.some(p=>p.name===descriptor.lightingExport&&p.blend==='multiply'));const hatch=h.paints.filter(p=>p.name==='touchdown_hatch_01');A.equal(hatch.length,0,'Closed source hatch belongs to static cache');A.ok(h.canvases.some(c=>c.getContext('2d').calls.some(p=>p[0]==='clip')),'Source floor uses unchanged field clip');h.g.arenaAnimated=false;const still=h.api.prepare(b,h.lib);A.notEqual(still,cv,'Animation setting invalidates source surface cache');h.paints.length=0;h.api.drawForeground(c,b,h.lib,3);A.equal(h.paints.filter(p=>p.type==='source'&&/audience|flag/.test(p.name)).length,0);h.api.clear();A.equal(cv.width,1);A.ok(cv.sourceStadium.foreground.every(run=>!run.image||run.image.width===1));
});
test('old stadium screenshot remains a working fallback, then complete source promotes the cache',async()=>{
 const h=arenaHarness(),b={arenaLayout:L.get('Touchdown')},full=h.lib.scenes;h.lib.scenes={};h.root.Image=class{constructor(){this.naturalWidth=551;this.naturalHeight=647}set src(x){this.onload()}};A.equal(await h.api.prepareAssets(b,'http://example.test/',h.lib),true);const old=h.api.prepare(b,h.lib);A.equal(old.stadiumArt,'supplied-reference');h.lib.scenes=full;const source=h.api.prepare(b,h.lib);A.notEqual(source,old);A.equal(source.stadiumArt,'source-stadium');
});
test('dedicated stadium scene closure is optional and never extends the Trophy Road list',async()=>{
 const data={arenas:[{id:'royal',scene:'level_royal_arena',objects:[]}],units:{},scenes:{},touchdownArena:descriptor},before=JSON.stringify(data.arenas),deps=N.touchdownSceneDependencies(data);A.deepEqual(deps,[...new Set([descriptor.scene,...descriptor.objects.map(o=>o.scene)])]);for(const name of [...deps,'ui_battle_end'])data.scenes[name]={textures:[]};const lib=new N.Library(data,{}),loaded=[];lib.ensureScenes=async names=>{loaded.push(...names);if(names.includes(descriptor.scene))throw Error('Stadium optional HTTP404')};lib.retainScenes=names=>{lib.kept=names};lib.prewarmBattleActors=async()=>{};const old=global.RoyaleCustomArena;global.RoyaleCustomArena={prepareAssets:async()=>{},prepare(){}};try{await lib.prepareBattle({arenaLayout:L.get('Touchdown'),initialDecks:[[]],towers:[]},{cards:[]});A.ok(loaded.includes(descriptor.scene));A.match(lib.touchdownSourceError,/HTTP404/);A.equal(lib.error,null);A.ok(!lib.kept.includes(descriptor.scene));A.equal(JSON.stringify(data.arenas),before);}finally{global.RoyaleCustomArena=old}
});
