'use strict';
const test=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),zlib=require('node:zlib');let U={};try{U=require('../tools/unpack.js')}catch(e){if(e.code!=='MODULE_NOT_FOUND')throw e}
const png='data:image/png;base64,iVBORw0KGgo=',webp='data:image/webp;base64,UklGRgQAAABXRUJQ';
function sample(){return {version:'0.4.0',game:{snapshot:'fixture'},manifest:{cards:[{id:'knight',file:'assets/cards/knight.png'}]},native:{scenes:{knight:{textures:[{file:'knight-0.webp'}]}}},art:{knight:png},images:{'knight-0.webp':webp},uiImages:{gold:png},uiManifest:{gold:{file:'assets/ui/gold.png'}}};}
function html(b){return '<html><script id="royale-payload" type="application/octet-stream">'+zlib.gzipSync(JSON.stringify(b)).toString('base64')+'</script></html>'}
test('offline asset unpacker has an explicit API',()=>A.equal(typeof U.decodeHTML,'function'));
const T=typeof U.decodeHTML==='function'?test:test.skip;
T('decodes the compressed playable HTML payload',()=>A.deepEqual(U.decodeHTML(html(sample())),sample()));
T('restores original image bytes and native metadata',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'royale-unpack-'));try{const r=U.restoreBundle(sample(),dir);A.equal(r.images,3);A.equal(fs.readFileSync(path.join(dir,'assets/cards/knight.png')).toString('hex'),'89504e470d0a1a0a');A.equal(JSON.parse(fs.readFileSync(path.join(dir,'assets/native/data.json'))).scenes.knight.textures.length,1);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
T('invalid compressed payload cannot be treated as assets',()=>{A.throws(()=>U.decodeHTML('<script id="royale-payload">not_base64</script>'));A.throws(()=>U.decodeHTML('<html>no payload</html>'));});
T('asset path traversal is rejected before any write',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'royale-unpack-')),b=sample();try{b.manifest.cards[0].file='../outside.png';A.throws(()=>U.restoreBundle(b,dir),/path|file/i);A.deepEqual(fs.readdirSync(dir),[]);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
T('HTML content masquerading as PNG is rejected',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'royale-unpack-')),b=sample();try{b.art.knight='data:image/png;base64,PGh0bWw+';A.throws(()=>U.restoreBundle(b,dir),/image|PNG/i);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
T('extraction refuses an asset-directory symlink',()=>{if(process.platform==='win32')return;const dir=fs.mkdtempSync(path.join(os.tmpdir(),'royale-unpack-')),outside=fs.mkdtempSync(path.join(os.tmpdir(),'royale-external-'));try{fs.symlinkSync(outside,path.join(dir,'assets'));A.throws(()=>U.restoreBundle(sample(),dir),/symlink/i);A.deepEqual(fs.readdirSync(outside),[]);}finally{fs.rmSync(dir,{recursive:true,force:true});fs.rmSync(outside,{recursive:true,force:true})}});
T('identical existing image bytes are not rewritten',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'royale-unpack-'));try{U.restoreBundle(sample(),dir);const p=path.join(dir,'assets/cards/knight.png'),before=fs.statSync(p).mtimeMs;U.restoreBundle(sample(),dir);A.equal(fs.statSync(p).mtimeMs,before);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
