'use strict';
const test=require('node:test'),A=require('node:assert/strict'),C=require('../src/core.js'),E=require('../src/economy.js');
const NOW=1800000000000;
function result(id,winner=0,extra={}){return{id,result:{winner},crowns:winner===0?[3,0]:[0,3],time:180,mode:'Default',queueType:'trophy-road',...extra};}
test('v036 free chest is ready exactly ten minutes after claiming',()=>{const r=E.classicChest(C.normalizeProfile({}),false,NOW);A.ok(r.ok);A.equal(r.profile.freeChestAt,NOW+600000);A.equal(E.classicChest(r.profile,false,NOW+599999).ok,false);A.equal(E.classicChest(r.profile,false,NOW+600000).ok,true);});
test('v036 migrates a v9 four-hour deadline once, preserving last claim',()=>{const p=C.normalizeProfile({version:9,freeChestAt:NOW+14400000});A.equal(p.freeChestAt,NOW+600000);A.equal(C.normalizeProfile(p).freeChestAt,p.freeChestAt);});
test('v036 ten crowns ignore an old crown cooldown and are spent atomically',()=>{let p=C.normalizeProfile({version:9,earnedCrowns:30,crownChestClaimed:0,crownChestAt:NOW+86400000});for(let i=1;i<=3;i++){const r=E.classicChest(p,true,NOW);A.ok(r.ok);p=r.profile;A.equal(p.crownChestClaimed,i*10);A.equal(p.crownChestAt,0);}A.equal(E.classicChest(p,true,NOW).ok,false);});
test('v036 streak bonus rerolls on each win within an unlocked tier',()=>{let p=C.normalizeProfile({});const bonuses=[];for(let n=1;n<=18;n++){const prior=p.trophies;p=C.applyResult(p,result('roll-'+n));const m=Math.floor(n/3),low=Math.min(3,m)*10+Math.max(0,m-3)*5;A.ok(p.winStreakBonus>=low&&p.winStreakBonus<=m*15);A.equal(p.trophies-prior,30+p.winStreakBonus);if(n>=3&&n<=5)bonuses.push(p.winStreakBonus);}A.ok(new Set(bonuses).size>1,'bonus must not stay fixed from milestone to milestone');});
test('v036 the same result pays once and replay/practice cannot change a streak',()=>{let p=C.normalizeProfile({winStreak:6,winStreakBonus:25});const b=result('receipt');p=C.applyResult(p,b);A.deepEqual(C.applyResult(p,b),p);for(const extra of [{isReplay:true},{practice:true},{queueType:'training'},{queueType:'2v2',is2v2:true}]){const q=C.applyResult(p,result('other-'+JSON.stringify(extra),1,extra));A.equal(q.winStreak,p.winStreak);A.equal(q.winStreakBonus,p.winStreakBonus);}A.equal(C.applyResult(p,result('loss',1)).winStreak,0);A.equal(C.applyResult(p,result('draw',-1)).winStreakBonus,0);});
test('v036 lightning shop exposes exactly three eligible unique offers for ten minutes',()=>{A.equal(typeof E.lightningOffers,'function');const p=C.normalizeProfile({trophies:6000,highestTrophies:6000});const o=E.lightningOffers(NOW,p);A.equal(o.length,3);A.equal(new Set(o.map(x=>x.id)).size,3);A.deepEqual(o,E.lightningOffers(NOW+599999,p));A.notEqual(E.lightningWindow(NOW),E.lightningWindow(NOW+600000));A.notDeepEqual(o,E.lightningOffers(NOW+600000,p));A.ok(o.every(x=>E.cardPool(p).some(c=>c.id===x.id)));A.equal(E.offers(NOW,p).length,12);});
test('v036 lightning shop can select every rarity over its rotations',()=>{A.equal(typeof E.lightningOffers,'function');const p=C.normalizeProfile({trophies:6000,highestTrophies:6000}),rarities=new Set();for(let i=0;i<40;i++)E.lightningOffers(NOW+i*600000,p).forEach(o=>rarities.add(o.rarity));A.deepEqual([...rarities].sort(),['Common','Epic','Legendary','Rare']);});
test('v036 lightning purchase persists, rejects duplicates and stale offers without charging',()=>{A.equal(typeof E.purchaseLightningCard,'function');let p=C.normalizeProfile({gold:99999});const o=E.lightningOffers(NOW,p)[0],key=E.lightningWindow(NOW);const r=E.purchaseLightningCard(p,0,NOW,key,o.id);A.ok(r.ok);A.equal(r.profile.gold,p.gold-o.price);A.equal(r.profile.copies[o.id],p.copies[o.id]+o.quantity);p=C.normalizeProfile(JSON.parse(JSON.stringify(r.profile)));A.equal(E.purchaseLightningCard(p,0,NOW,key,o.id).ok,false);const stale=E.purchaseLightningCard(p,1,NOW+600000,key,o.id);A.equal(stale.ok,false);A.equal(stale.profile.gold,p.gold);A.equal(E.purchaseLightningCard(p,1,NOW,key,'fake-card').ok,false);A.equal(E.purchaseLightningCard(p,3,NOW,key,o.id).ok,false);});
