'use strict';
const test=require('node:test'),a=require('node:assert/strict'),C=require('../src/core.js'),R=require('../src/replay.js');let D={};try{D=require('../src/deck-manager.js');}catch{}
test('Normal deck deletion survives normalization, and ten saved decks are retained',()=>{const p=C.normalizeProfile({});p.decks=p.decks.slice(0,2);p.activeDeck=1;a.equal(C.normalizeProfile(p).decks.length,2);p.decks=Array.from({length:10},()=>[...C.DEFAULT_DECK]);p.activeDeck=9;a.equal(C.normalizeProfile(p).decks.length,10);a.equal(C.normalizeProfile(p).activeDeck,9);});
test('Add/remove deck operations retain at least one and never mutate the input',()=>{a.equal(typeof D.add,'function');let p=C.normalizeProfile({});const r=D.add(p);a.equal(r.ok,true);a.equal(r.profile.decks.length,6);a.equal(p.decks.length,5);a.deepEqual(r.profile.decks[5],p.decks[0]);p=r.profile;while(p.decks.length<D.MAX_DECKS)p=D.add(p).profile;a.equal(D.add(p).ok,false);while(p.decks.length>1)p=D.remove(p,p.activeDeck).profile;a.equal(D.remove(p,0).ok,false);a.equal(p.activeDeck,0);a.equal(D.remove(p,Infinity).ok,false);});
test('Four-card saved deck is independent, legal and persistent',()=>{const p=C.normalizeProfile({});a.equal(p.fourCardDeck.length,4);p.fourCardDeck=[...C.DEFAULT_DECK].reverse().slice(0,4);a.deepEqual(C.normalizeProfile(JSON.parse(JSON.stringify(p))).fourCardDeck,p.fourCardDeck);a.equal(C.normalizeProfile({...p,fourCardDeck:['missing','missing','mirror','mirror']}).fourCardDeck.length,4);});
test('Four-card matches have four real cards on both sides and safely cycle with an empty queue',()=>{const deck=C.DEFAULT_DECK.slice(0,4),b=new C.Battle({mode:'FourCardDeck',queue:'challenge',deck,enemyDeck:deck,ai:false,seed:36});a.equal(b.mode,'FourCardDeck');a.deepEqual(b.initialDecks.map(x=>x.length),[4,4]);a.deepEqual(b.queue,[[],[]]);b.elixir[0]=10;const id=b.hand[0][0],r=b.deploy(0,0,240,480);a.equal(r.ok,true);a.equal(b.hand[0][0],id);a.equal(b.queue[0].length,0);a.equal(b.deploy(0,0,240,480).ok,false);for(let i=0;i<75;i++)b.step(1/60);b.elixir[0]=10;a.equal(b.deploy(0,0,240,480).ok,true);a.equal(b.kingLevels[0],9);});
test('Random deck generation varies per seed without editing saved decks',()=>{a.equal(typeof D.random,'function');const p=C.normalizeProfile({}),before=JSON.stringify(p.decks);const decks=Array.from({length:20},(_,i)=>D.random(p,i));for(const d of decks){a.equal(d.length,8);a.equal(new Set(d).size,8);a.ok(d.every(id=>C.CARD_BY_ID[id]));}a.ok(new Set(decks.map(JSON.stringify)).size>1);a.equal(JSON.stringify(p.decks),before);});
test('Random deck mode remains named and non-ranked without modifying the deck library',()=>{const p=C.normalizeProfile({winStreak:5,trophies:1000}),b=new C.Battle({mode:'RandomDeck',queue:'challenge',profile:p,ai:false});a.equal(b.mode,'RandomDeck');b.finish(0,'test');const q=C.applyResult(p,b);a.equal(q.trophies,p.trophies);a.equal(q.winStreak,p.winStreak);a.deepEqual(q.decks,p.decks);});
test('Four-card replay reproduces input cycling and rejects invalid mismatched cycle sizes',()=>{const deck=C.DEFAULT_DECK.slice(0,4),b=new C.Battle({mode:'FourCardDeck',deck,enemyDeck:deck,ai:false,seed:61});R.captureInitial(b);a.equal(b.deploy(0,0,240,480).ok,true);for(let i=0;i<90;i++)b.step(1/60);const record=R.pack(b);a.equal(record.initial.decks[0].length,4);const replay=new R.Session(record);replay.seek(record.duration);a.equal(replay.error,null);a.deepEqual(R.digest(replay.battle),R.digest(b));const invalid=JSON.parse(JSON.stringify(record));invalid.initial.queue[0].push('knight');a.throws(()=>R.validate(invalid),/deck size/);});
