'use strict';
const test=require('node:test'),a=require('node:assert/strict'),C=require('../src/core.js'),E=require('../src/economy.js');const NOW=Date.UTC(2026,8,28,12);
const p=()=>C.normalizeProfile({version:11,highestTrophies:6000,trophies:6000,gems:10000,gold:20000});
test('v038 Daily Shop legacy prices remain unchanged while current quantities follow king scaling',()=>{const q=p(),o=E.dailyOffers(NOW,q),base={Common:500,Rare:150,Epic:30,Legendary:8};a.equal(o.length,9);for(const x of o.slice(3)){a.equal(x.quantity,E.scaleShopQuantity(base[x.rarity],x.rarity,q));a.equal(x.reward.cards[0].count,x.quantity);a.equal(x.price,{Common:100,Rare:250,Epic:500,Legendary:1000}[x.rarity]);}});
test('v038 Daily Shop free wildcards multiply by five, not currency or claim count',()=>{const range={Common:[250,1250],Rare:[125,375],Epic:[25,95],Legendary:[5,5]};const found=new Set();for(let day=0;day<350;day++){const os=E.dailyOffers(NOW+day*86400000,p()),o=os[2];found.add(o.rarity);a.ok(o.quantity>=range[o.rarity][0]&&o.quantity<=range[o.rarity][1]);a.equal(o.quantity%5,0);a.equal(o.reward.wildcards[o.rarity],o.quantity);a.ok(os[0].reward.gold>=100&&os[0].reward.gold<=10000);a.ok(os[1].reward.gems>=5&&os[1].reward.gems<=250);a.ok(os.slice(0,3).every(o=>o.price===0));}a.equal(found.size,4);});
test('v038 Gem Shop has six distinct persistent eligible gem-priced offers',()=>{a.equal(typeof E.gemOffers,'function');const base=p(),offers=E.gemOffers(base);a.equal(offers.length,6);a.equal(new Set(offers.map(o=>o.id)).size,6);a.deepEqual(offers,E.gemOffers(C.normalizeProfile(JSON.parse(JSON.stringify(base)))));for(const o of offers){a.equal(o.currency,'gems');a.ok(o.quantity>0&&o.price>0);a.ok(E.cardPool(base).some(c=>c.id===o.id));}});
test('v038 Gem Shop rotates all six slots on the second successful purchase, not the first',()=>{a.equal(typeof E.purchaseGemCard,'function');let base=p();const initial=E.gemOffers(base),cycle=base.gemShop.rotation;const one=E.purchaseGemCard(base,0,cycle,initial[0].id);a.equal(one.ok,true);a.equal(one.profile.gems,base.gems-initial[0].price);a.equal(one.profile.gold,base.gold);a.equal(one.profile.copies[initial[0].id],base.copies[initial[0].id]+initial[0].quantity);a.equal(one.profile.gemShop.rotation,cycle);a.deepEqual(one.profile.gemShop.purchased,[0]);base=C.normalizeProfile(JSON.parse(JSON.stringify(one.profile)));a.deepEqual(E.gemOffers(base),initial);const two=E.purchaseGemCard(base,1,cycle,initial[1].id);a.equal(two.ok,true);a.equal(two.profile.gemShop.rotation,cycle+1);a.deepEqual(two.profile.gemShop.purchased,[]);a.notDeepEqual(E.gemOffers(two.profile),initial);a.equal(two.refreshed,true);});
test('v038 Gem Shop rejects duplicate, unfunded, stale, and invalid purchases without state changes',()=>{a.equal(typeof E.purchaseGemCard,'function');const base=p(),o=E.gemOffers(base),cycle=base.gemShop.rotation;for(const [profile,index,rot,id]of [[{...base,gems:0},0,cycle,o[0].id],[base,-1,cycle,o[0].id],[base,6,cycle,o[0].id],[base,1.5,cycle,o[0].id],[base,0,cycle+1,o[0].id],[base,0,cycle,'bad']]){const r=E.purchaseGemCard(profile,index,rot,id);a.equal(r.ok,false);a.deepEqual(r.profile,C.normalizeProfile(profile));}const one=E.purchaseGemCard(base,0,cycle,o[0].id);const dup=E.purchaseGemCard(one.profile,0,cycle,o[0].id);a.equal(dup.ok,false);a.deepEqual(dup.profile,one.profile);const two=E.purchaseGemCard(one.profile,1,cycle,o[1].id);a.equal(E.purchaseGemCard(two.profile,2,cycle,o[2].id).ok,false);});
test('v038 legacy profiles keep currency/decks and new gem rotation normalization is bounded',()=>{const old=p(),q=C.normalizeProfile({...old,gemShop:{rotation:-4,purchased:[0,0,-1,7,'1']}});a.deepEqual(q.gemShop,{rotation:0,arenaNumber:old.gemShop.arenaNumber,purchased:[0]});a.equal(q.gems,old.gems);a.deepEqual(q.decks,old.decks);a.deepEqual(C.normalizeProfile({}).gemShop,{rotation:0,arenaNumber:1,purchased:[]});});

test('v038 Gem Shop does not reroll on arena unlock before two purchases',()=>{let base=C.normalizeProfile({});const os=E.gemOffers(base),r=E.purchaseGemCard({...base,gems:10000},0,0,os[0].id);a.equal(r.ok,true);const promoted=C.normalizeProfile({...r.profile,trophies:6000,highestTrophies:6000});a.deepEqual(E.gemOffers(promoted),os);const next=E.purchaseGemCard(promoted,1,0,os[1].id);a.equal(next.ok,true);a.ok(next.profile.gemShop.arenaNumber>base.gemShop.arenaNumber);});
