'use strict';
const test=require('node:test'),a=require('node:assert/strict'),C=require('../src/core.js'),G=require('../src/arena-grid.js'),Nav=require('../src/navigation.js');
function battle(mode='Team3v3',seed=9){return new C.Battle({mode,seed,queue:'challenge',headless:true,ai:false});}
test('3v3 creates six independent level-9 seats and six towers per side',()=>{const b=battle();a.equal(b.mode,'Team3v3');a.equal(b.seatCount,6);a.equal(b.initialDecks.length,6);a.equal(b.towers.length,12);for(const s of b.seats){a.equal(b.kingLevels[s],9);a.equal(b.towers.filter(t=>t.owner===s&&t.king).length,1);a.equal(b.towers.filter(t=>t.owner===s&&!t.king).length,1);}a.notEqual(b.hand[0],b.hand[2]);});
test('3v3 seeded assignment is a permutation on each side and unbiased over seeds',()=>{const counts=[0,0,0];for(let seed=1;seed<=300;seed++){const b=battle('Team3v3',seed);a.equal(b.seatSlots?.length,6);for(const team of [0,1])a.deepEqual(b.seats.filter(s=>s%2===team).map(s=>b.seatSlots[s]).sort(),[0,1,2]);counts[b.seatSlots[0]]++;a.deepEqual(b.seatSlots,battle('Team3v3',seed).seatSlots);}a.ok(counts.every(n=>n>65&&n<135),JSON.stringify(counts));});
test('destroyed assigned King stops only its owner passive elixir without deleting bank',()=>{const b=battle(),k=b.towers.find(t=>t.king&&t.owner===0);b.elixir.fill(4);k.hp=0;b.step(.1);a.equal(b.result,null);a.equal(b.elixir[0],4);for(const s of b.seats.slice(1))a.ok(b.elixir[s]>4);b.creditElixir(0,1);a.equal(b.elixir[0],5);b.step(.1);a.equal(b.elixir[0],5);});
test('survivor can spend elixir and their existing pump works after King destruction',()=>{const b=battle();b.towers.find(t=>t.king&&t.owner===0).hp=0;b.deaths();b.elixir[0]=8;const slot=b.hand[0].findIndex(id=>C.CARD_BY_ID[id].entity&&!C.CARD_BY_ID[id].building);const r=b.deploy(0,slot,9*C.SX,19*C.SY);a.ok(r.ok,r.reason);const bank=b.elixir[0];const pump=b.spawn('ElixirCollector',0,6*C.SX,20*C.SY,{owner:0,wait:0});pump.manaAt=b.time;b.step(.01);a.equal(b.elixir[0],bank+1);});
test('3v3 golem descendants retain owner and return generated elixir to that owner',()=>{const b=battle();b.elixir.fill(0);b.towers.find(t=>t.king&&t.owner===4).hp=0;b.deaths();b.spawn('ElixirGolem1',0,9*C.SX,20*C.SY,{owner:4,wait:0}).hp=0;b.deaths();const children=b.units.filter(u=>u.entity==='ElixirGolem2');a.equal(children.length,2);a.ok(children.every(u=>u.owner===4));children.forEach(u=>u.hp=0);b.deaths();const blobs=b.units.filter(u=>u.entity==='ElixirGolem4');a.equal(blobs.length,4);blobs.forEach(u=>u.hp=0);b.deaths();a.equal(b.elixir[4],4);a.equal(b.elixir[0],0);a.equal(b.elixir[1],0);});
test('normal Elixir Golem still gives elixir to opposing side',()=>{const b=battle('Default');b.elixir.fill(0);b.spawn('ElixirGolem4',0,9*C.SX,20*C.SY,{owner:0,wait:0}).hp=0;b.deaths();a.equal(b.elixir[0],0);a.equal(b.elixir[1],1);});
test('3v3 needs all three Kings for immediate victory and can record six crowns',()=>{const b=battle();const enemy=b.towers.filter(t=>t.team===1);enemy.filter(t=>!t.king).forEach(t=>t.hp=0);b.deaths();a.equal(b.crowns[0],3);const ks=enemy.filter(t=>t.king);for(let i=0;i<3;i++){ks[i].hp=0;b.deaths();b.checkResult();a.equal(b.crowns[0],4+i);if(i<2)a.equal(b.result,null);}a.equal(b.result.winner,0);});
test('Bridge mode has two seats, one King and one Princess each; off-lane deployment is rejected',()=>{const b=battle('BridgeBattle');a.equal(b.mode,'BridgeBattle');a.equal(b.towers.length,4);a.ok(b.towers.every(t=>t.x===9*C.SX));const c=C.cardAt('knight',9);a.equal(b.placement(0,c,2*C.SX,22*C.SY).ok,false);a.equal(b.placement(0,c,9*C.SX,19*C.SY).ok,true);});
test('custom layouts drive swept navigation, not just visual backgrounds',()=>{a.equal(Nav.pointClear({x:9,y:16},.6,[],{layout:'Team3v3'}),true);a.equal(Nav.pointClear({x:6,y:16},.6,[],{layout:'Team3v3'}),false);a.equal(Nav.pointClear({x:3.5,y:16},.6,[],{layout:'BridgeBattle'}),false);a.equal(Nav.pointClear({x:9,y:16},.6,[],{layout:'BridgeBattle'}),true);a.equal(Nav.pointClear({x:3,y:22},.6,[],{layout:'BridgeBattle'}),false);a.equal(G.waterClear(9,16,.6),false,'normal river remains blocked in middle');});
