'use strict';
const test=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),C=require('../src/core');
function policy(){A.ok(fs.existsSync('src/rematch.js'),'Play Again policy exists');return require('../src/rematch');}
function finished(mode='Default',queue='trophy-road',extra={}){return{mode,queueType:queue,result:{winner:0},initialDecks:[[...C.DEFAULT_DECK]],...extra};}
test('Play Again retains mode, queue and a copy of the selected deck',()=>{const R=policy(),b=finished('TeamRumble','5v5'),p=R.request(b);A.equal(p.mode,'TeamRumble');A.equal(p.training,false);A.equal(p.extra.queue,'5v5');A.deepEqual(p.extra.deck,b.initialDecks[0]);A.notEqual(p.extra.deck,b.initialDecks[0]);A.equal(p.extra.seed,undefined);A.equal(p.extra.opponent,undefined);});
test('casual 1v1 repeat cannot become a ranked match',()=>{const p=policy().request(finished('Default','challenge'));A.equal(p.mode,'Default');A.equal(p.extra.queue,'challenge');});
test('Random Deck repeat requests fresh generation instead of reusing either deck',()=>{const p=policy().request(finished('RandomDeck','challenge'));A.equal(p.extra.deck,undefined);A.equal(p.extra.enemyDeck,undefined);A.equal(p.extra.arenaId,undefined);});
test('all selectable deck sizes are preserved by repeat',()=>{for(const mode of ['FourCardDeck','TwelveCardDeck','OneShot']){const deck=C.normalizeProfile({})[C.MODE_DECKS[mode].key],p=policy().request(finished(mode,'challenge',{initialDecks:[deck]}));A.deepEqual(p.extra.deck,deck);A.equal(p.extra.deck.length,C.MODE_DECKS[mode].size);}});
test('practice repeat keeps practice rewards disabled',()=>{const p=policy().request(finished('Default','training',{practice:true}));A.equal(p.training,true);A.equal(p.extra.practice,true);});
test('unfinished, sandbox, replay and war-ticket matches cannot be repeated from results',()=>{const R=policy();for(const extra of [{result:null},{isReplay:true},{isSandbox:true},{warContext:{ticketId:'used'}},{queueType:'clan-war'},{queueType:'self-play'},{queueType:'replay'}])A.equal(R.request(finished('Default','trophy-road',extra)),null);A.equal(R.request(null),null);});
test('repeat request does not modify or repay the completed match',()=>{const b=new C.Battle({mode:'TeamRumble',queue:'5v5',seed:72,ai:false});b.crowns=[10,0];b.finish(0,'test');const p=C.applyResult(C.normalizeProfile({}),b),before=JSON.stringify(p),id=b.id;for(let i=0;i<3;i++)policy().request(b);A.equal(b.id,id);A.equal(JSON.stringify(p),before);A.deepEqual(C.applyResult(p,b),p);});
