'use strict';
const test=require('node:test'),a=require('node:assert/strict'),C=require('../src/core'),E=require('../src/economy'),R=require('../src/progression'),CR=require('../src/crown-road'),Ch=require('../src/chest-rules');
function win(id,extra={}){return{id,result:{winner:0},mode:'Default',queueType:'trophy-road',crowns:[1,0],time:180,...extra};}
test('Legendary battle chest has exact 0.1% weight without reducing Gem/Treasure odds',()=>{const w=Ch.DROP_WEIGHTS,total=Object.values(w).reduce((a,b)=>a+b,0);a.equal(w.legendary/total,.001);a.equal(w.gem/total,1/12);a.equal(w.treasure/total,1/15);});
test('Wild cards books and magic coins all have real very rare receipt-keyed battle awards',()=>{a.equal(typeof Ch.battleItem,'function');const counts={wild:0,book:0,coin:0};for(let i=0;i<100000;i++){const item=Ch.battleItem('award-'+i,331);if(item){a.ok(item.count>=1);counts[item.kind]++;a.deepEqual(item,Ch.battleItem('award-'+i,331));}}for(const kind in counts)a.ok(counts[kind]>60&&counts[kind]<140,kind+': '+counts[kind]);});
test('Battle items credit once, persist, and pay with full chest slots but never in practice or on loss',()=>{a.equal(typeof Ch.battleItem,'function');const p=C.normalizeProfile({gold:0,gems:0,chests:Array.from({length:4},(_,i)=>({id:'existing'+i,kind:'silver',winsProgress:0}))});const found={};for(let i=0;i<50000&&Object.keys(found).length<3;i++){const id='pay-'+i,item=Ch.battleItem(id,p.world.seed);if(item&&!found[item.kind])found[item.kind]={id,item};}a.equal(Object.keys(found).length,3);for(const {id,item} of Object.values(found)){const q=C.applyResult(p,win(id));const inventory=item.kind==='wild'?'wildcards':'magicItems',key=item.kind==='wild'?item.rarity:item.id;a.equal(q[inventory][key]-p[inventory][key],item.count);a.equal(q.chests.length,4);a.equal(q.history[0].itemRewards[0].id,item.id);a.deepEqual(C.applyResult(q,win(id)),q);a.deepEqual(C.normalizeProfile(JSON.parse(JSON.stringify(q))).history[0].itemRewards,q.history[0].itemRewards);for(const change of [{practice:true},{queueType:'training'},{isReplay:true},{result:{winner:1}}]){const no=C.applyResult(p,win(id,change));a.equal(no[inventory][key],p[inventory][key]);}}});
test('Trophy Road adds new independently claimable books, coins, and wild milestones without removing old claims',()=>{const steps=R.ROAD_REWARDS.filter(r=>r.id.startsWith('road2-'));a.ok(steps.filter(r=>r.kind==='wildcards').length>=14);for(const id of ['common-book','magic-coin'])a.ok(steps.some(r=>r.item===id));const p=C.normalizeProfile({trophies:8000,highestTrophies:8000,roadClaimed:['road1-50']});for(const s of steps.filter(r=>r.kind==='magic-item')){const got=E.claimRoad(p,s.id);a.ok(got.ok);a.equal(got.profile.magicItems[s.item],p.magicItems[s.item]+s.amount);a.ok(got.profile.roadClaimed.includes('road1-50'));a.equal(E.claimRoad(got.profile,s.id).ok,false);}});
test('Crown Road increases book/coin frequency and preserves old claims',()=>{let books=0,coins=0;for(let i=1;i<=100;i++){const r=CR.reward(i);if(Object.keys(r.magicItems||{}).some(id=>id.includes('book')))books++;if(r.magicItems?.['magic-coin'])coins++;}a.ok(books>=10);a.ok(coins>=10);const p=C.normalizeProfile({lifetimeCrowns:1000,crownRoadClaims:[[1,99]]}),g=E.claimCrown(p,100);a.ok(g.ok);a.equal(E.claimCrown(g.profile,100).ok,false);a.equal(CR.progress(g.profile).unclaimed,0);});
test('A rare battle Legendary chest never opens empty before the first Legendary arena',()=>{const p=C.normalizeProfile({trophies:0,highestTrophies:0,chests:[{id:'early-legendary',kind:'legendary',winsProgress:10}]});const got=E.openChest(p,'early-legendary');a.ok(got.ok);a.equal(got.reward.wildcards?.Legendary,1);a.equal(got.profile.wildcards.Legendary,1);a.deepEqual(got.profile.unlockedCards,p.unlockedCards);});
