'use strict';
const test=require('node:test'),a=require('node:assert/strict'),C=require('../src/core.js'),L=require('../src/arena-layout.js'),N=require('../src/navigation.js');
function battle(mode,arenaId){return new C.Battle({mode,arenaId,queue:'challenge',ai:false,headless:true,seed:4505});}
function obstacles(b){return b.towers.map(t=>({id:t.id,x:t.x/C.SX,y:t.y/C.SY,radius:t.def.radiusTiles}));}
function structural(id){const l=L.get(id);return {left:l.left,right:l.right,top:l.top,bottom:l.bottom,riverTop:l.riverTop,riverBottom:l.riverBottom,lanes:l.lanes,bridges:l.bridges,kings:l.kings,princessY:l.princessY};}
test('v045 themed 3v3 maps retain the proven Bastion collision geometry',()=>{const base=structural('Team3v3');for(const id of ['Team3v3Jungle','Team3v3Volcano'])a.deepEqual(structural(id),base);});
test('v045 themed Bridge maps retain the proven Causeway collision geometry',()=>{const base=structural('BridgeBattle');for(const id of ['BridgeBattleLava','BridgeBattleGarden'])a.deepEqual(structural(id),base);});
test('v045 reverse-arch Rumble has swept rear routes behind every tower',()=>{const id='TeamRumbleArcReverse',b=battle('TeamRumble',id),obs=obstacles(b),r=1;for(const tower of b.towers){const dir=tower.team?1:-1,start={x:tower.x/C.SX,y:tower.y/C.SY-dir*(tower.def.radiusTiles+r+.1)},target={x:start.x,y:16,radius:0};a.ok(N.pointClear(start,r,obs,{layout:id}),'rear start '+tower.id);const route=N.route(start,target,r,1.1,obs,{layout:id});a.ok(route.length,'route '+tower.id);}});
test('v045 four-bridge Rumble exposes four genuinely two-tile-wide crossings for large troops',()=>{const id='TeamRumbleRiverLine',l=L.get(id);a.equal(l.bridges.length,4);for(const bridge of l.bridges){a.equal(bridge.right-bridge.left,2);const x=(bridge.left+bridge.right)/2;a.ok(L.waterClear(x,16,.9,id),'bridge fits radius .9');a.ok(N.segmentClear({x,y:14},{x,y:18},.9,[],{layout:id}),'swept river crossing');}});
for(const id of ['Touchdown','Touchdown3v3'])test('v045 touchdown lanes are unobstructed on '+id,()=>{const l=L.get(id);for(const x of l.lanes){const start={x,y:l.goalBottom-1.5},target={x,y:l.goalTop+1.5,radius:0},route=N.route(start,target,1,1.1,[],{layout:id});a.ok(route.length,id+' route');}});
test('v046 current arena registry retires the v045 FFA geometry',()=>{a.equal(L.get('FreeForAll').id,'classic');});
