/* Recover lossless source images from the one-copy offline HTML distribution.
 * No downloads and no evaluation of JavaScript from the HTML. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
function decodeHTML(html){const match=/<script\s+id="royale-payload"[^>]*>([A-Za-z0-9+/=\r\n]+)<\/script>/.exec(html);if(!match)throw Error('Missing or invalid compressed asset payload');const compressed=Buffer.from(match[1].trim(),'base64');const decoded=zlib.gunzipSync(compressed,{maxOutputLength:300*1024*1024});const b=JSON.parse(decoded.toString('utf8'));if(b.version!=='0.4.0'||!b.native?.scenes||!b.game||!Array.isArray(b.manifest?.cards)||!b.uiManifest)throw Error('Unsupported bundle format');return b;}
function imageBytes(url){if(typeof url!=='string'||url.length>48*1024*1024)throw Error('Invalid image payload size');const m=/^data:image\/(png|webp);base64,([A-Za-z0-9+/=]+)$/.exec(url);if(!m)throw Error('Invalid image encoding');const bytes=Buffer.from(m[2],'base64');if(m[1]==='png'&&bytes.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error('Invalid PNG image');if(m[1]==='webp'&&(bytes.toString('ascii',0,4)!=='RIFF'||bytes.toString('ascii',8,12)!=='WEBP'))throw Error('Invalid WebP image');return bytes;}
function safeAncestors(root,file){let p=root;for(const name of file.split('/').slice(0,-1)){p=path.join(p,name);if(fs.existsSync(p)&&fs.lstatSync(p).isSymbolicLink())throw Error('Refusing asset directory symlink: '+p);}const dest=path.join(root,file);if(fs.existsSync(dest)&&fs.lstatSync(dest).isSymbolicLink())throw Error('Refusing asset file symlink: '+dest);}
function restoreBundle(b,root){root=path.resolve(root);const writes=new Map();let images=0;const add=(file,data)=>{if(!/^assets\/(cards|native|ui|game)\/[A-Za-z0-9_-]+\.(png|webp|json)$/.test(file)&&file!=='assets/manifest.json')throw Error('Unsafe asset path '+file);safeAncestors(root,file);writes.set(file,data);};
 for(const c of b.manifest.cards){if(!/^[a-z0-9-]+$/.test(c.id)||c.file!=='assets/cards/'+c.id+'.png')throw Error('Invalid card asset file path');add(c.file,imageBytes(b.art[c.id]));images++;}
 const seen=new Set();for(const s of Object.values(b.native.scenes))for(const t of s.textures){if(!/^[a-zA-Z0-9_-]+\.(png|webp)$/.test(t.file))throw Error('Invalid native texture filename');if(!seen.has(t.file)){add('assets/native/'+t.file,imageBytes(b.images[t.file]));seen.add(t.file);images++;}}
 for(const [id,a]of Object.entries(b.uiManifest)){if(!/^[a-z0-9-]+$/.test(id)||a.file!=='assets/ui/'+id+'.png')throw Error('Invalid UI image file path');add(a.file,imageBytes(b.uiImages[id]));images++;}
 for(const [f,data]of [['assets/manifest.json',b.manifest],['assets/native/data.json',b.native],['assets/ui/manifest.json',b.uiManifest],['assets/game/data.json',b.game]])add(f,Buffer.from(JSON.stringify(data)));
 let changed=0;for(const [f,bytes]of writes){const dest=path.join(root,f);if(fs.existsSync(dest)&&fs.readFileSync(dest).equals(bytes))continue;fs.mkdirSync(path.dirname(dest),{recursive:true});const tmp=dest+'.unpack-tmp';const fd=fs.openSync(tmp,'wx');try{fs.writeFileSync(fd,bytes);}finally{fs.closeSync(fd);}try{fs.renameSync(tmp,dest);}catch(e){fs.rmSync(tmp,{force:true});throw e;}changed++;}
 return {images,files:writes.size,changed};
}
function restoreFromFile(filename,root=path.resolve(__dirname,'..')){const st=fs.statSync(filename);if(!st.isFile()||st.size>300*1024*1024)throw Error('HTML bundle exceeds supported bounds');return restoreBundle(decodeHTML(fs.readFileSync(filename,'utf8')),root);}
module.exports={decodeHTML,restoreBundle,restoreFromFile};
if(require.main===module){try{console.log(restoreFromFile(process.argv[2]||path.resolve(__dirname,'../Royale-Demo.html')));}catch(e){console.error('Asset extraction failed: '+e.message);process.exitCode=1;}}
