/* AI-only persistence adapter. A hosted browser cannot select AppData itself.
   The offline opener exposes a same-origin, token-protected, fixed-path store.
   CAS revisions prevent concurrent tabs from replacing one another's updates. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./learning.js'):root.RoyaleLearning,n?require('./learning-store.js'):root.RoyaleLearningStore);if(n)module.exports=api;else root.RoyaleAppData=api;})(globalThis,function(L,S){'use strict';
const PREFIX='/__webroyale_ai__/',MAX_RECORDS=40,MAX_BYTES=24*1024*1024,copy=x=>JSON.parse(JSON.stringify(x));
function validate(data){const m=data?.model;if(data?.schema!==1||data.snapshot!==L.normalizeModel().snapshot||m?.schema!==1||m.snapshot!==data.snapshot||!Array.isArray(m.weights)||m.weights.length!==L.DIM||!m.weights.every(w=>Number.isFinite(w)&&Math.abs(w)<=L.WEIGHT_LIMIT)||!Array.isArray(data.records)||data.records.length>100)throw Error('Invalid or incompatible AI data');if(JSON.stringify(data).length>40*1024*1024)throw Error('AI data exceeds the import limit');for(const r of data.records)if(!r||typeof r.id!=='string'||r.id.length>140||r.snapshot!==data.snapshot)throw Error('Invalid match record');return data;}
function bound(records){const seen=new Set(),out=[];let bytes=0;for(let i=records.length-1;i>=0;i--){const r=records[i];if(seen.has(r.id))continue;seen.add(r.id);const size=JSON.stringify(r).length;if(out.length>=MAX_RECORDS||bytes+size>MAX_BYTES)continue;bytes+=size;out.push(copy(r));}return out.reverse();}
class AppDataLearningStore{
 constructor({fetch,location,indexedDB,storage,fallback}={}){this.maxRecords=MAX_RECORDS;this.maxBytes=MAX_BYTES;this.fetch=fetch;this.location=location;this.fallback=fallback||new S.LearningStore({indexedDB,storage});this.model=L.normalizeModel();this.records=[];this.mode='Opening AI storage';this.persistent=false;this.error=null;this.path=null;this.token=null;this.local=false;this.revision=0;this._queue=Promise.resolve();this.pending=[];}
 async api(name,{method='GET',body}={}){const controller=typeof AbortController!=='undefined'?new AbortController():null,timer=controller?setTimeout(()=>controller.abort(),method==='GET'?4000:30000):null;try{const response=await this.fetch(new URL(PREFIX+name,this.location.origin).href,{method,cache:'no-store',credentials:'same-origin',redirect:'error',headers:{'X-Web-Royale-AI':this.token||'','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),...(controller?{signal:controller.signal}:{})});let data;try{data=await response.json();}catch(_){throw Error('Offline AI host returned an invalid response');}if(!response.ok){const e=Error(data.error||'Offline AI host: HTTP '+response.status);e.status=response.status;throw e;}return data;}finally{if(timer)clearTimeout(timer);}}
 async open(){await this.fallback.open();this.syncFallback();if(!['127.0.0.1','localhost'].includes(this.location?.hostname)||typeof this.fetch!=='function')return this;
  try{const caps=await this.api('capabilities');if(caps.app!=='Web Royale AI'||caps.schema!==1||!caps.token)throw Error('The local preview host does not offer AppData storage');this.token=caps.token;this.path=String(caps.path||'');this.archiveLimitBytes=caps.archiveLimitBytes;this.local=true;let state=await this.api('state');if(state.data===null){const initial=validate(await this.fallback.export());try{const r=await this.api('state',{method:'POST',body:{revision:state.revision,data:initial,archive:initial.records}});state={revision:r.revision,data:initial};}catch(e){if(e.status!==409)throw e;state=await this.api('state');}}this.accept(state);}
  catch(e){if(this.local){this.mode='AppData unavailable';this.persistent=false;this.error=String(e.message||e);}else{this.syncFallback();this.warning='Open with the updated offline BAT to store AI data in AppData.';}}
  return this;
 }
 syncFallback(){for(const k of ['model','records','mode','persistent','error'])this[k]=this.fallback[k];}
 accept(state){validate(state.data);this.model=L.normalizeModel(state.data.model);this.records=bound(state.data.records);this.revision=state.revision;this.mode='AppData';this.persistent=true;this.error=null;}
 async refresh(){await this._queue;if(this.local){this.accept(await this.api('state'));return copy(this.model);}const m=await this.fallback.refresh();this.syncFallback();return m;}
 commit(packet){return this.commitMany([packet]);}
 commitMany(packets){if(!Array.isArray(packets)||packets.length>100) return Promise.reject(Error('Commit at most 100 match packets at a time'));const task=this._queue.then(async()=>{if(!this.local){for(const p of packets)await this.fallback.commit(p);this.syncFallback();return{ok:true,model:copy(this.model),persistent:this.persistent,error:this.error};}
   for(let attempt=0;attempt<10;attempt++){const latest=await this.api('state');validate(latest.data);let model=L.normalizeModel(latest.data.model),records=latest.data.records.slice(),archive=[];for(const p of packets){const known=model.seen.includes(p?.record?.id);model=L.mergePacket(model,p);if(!known){records.push(copy(p.record));archive.push(copy(p.record));}}
    const data={schema:1,snapshot:model.snapshot,engine:L.ENGINE,model,records:bound(records)};try{const result=await this.api('state',{method:'POST',body:{revision:latest.revision,data,archive}});this.accept({revision:result.revision,data});return{ok:true,model:copy(model),persistent:true};}catch(e){if(e.status!==409)throw e;await new Promise(r=>setTimeout(r,10+attempt*15));}}
   throw Error('AI storage is busy in another tab. Retry saving shortly.');
  }).catch(e=>{if(this.local){this.error=String(e.message||e);this.persistent=false;this.mode='AppData write failed';}throw e;});this._queue=task.catch(()=>{});return task;}
 async export(){await this._queue;if(!this.local)return this.fallback.export();await this.refresh();return{schema:1,snapshot:this.model.snapshot,engine:L.ENGINE,exportedAt:new Date().toISOString(),scope:'local-AppData; no remote uploads',retention:{maxRecords:MAX_RECORDS,maxBytes:MAX_BYTES,archiveLimitBytes:this.archiveLimitBytes},features:L.FEATURE_NAMES,model:copy(this.model),records:copy(this.records)};}
 replace(data){validate(data);const task=this._queue.then(async()=>{if(!this.local){await this.fallback.import(data);this.syncFallback();return this;}const latest=await this.api('state');const limited={schema:1,snapshot:data.snapshot,engine:L.ENGINE,model:L.normalizeModel(data.model),records:bound(data.records)};const result=await this.api('state',{method:'POST',body:{revision:latest.revision,data:limited,archive:limited.records}});this.accept({revision:result.revision,data:limited});return this;});this._queue=task.catch(()=>{});return task;}
 async import(data){return this.replace(data);}
 async reset(){return this.replace({schema:1,snapshot:this.model.snapshot,model:L.normalizeModel(),records:[]});}
}
return{AppDataLearningStore,validate,bound,PREFIX};});
