/* Immutable battle geometry, shared by placement, collision, routing and art.
   Classic coordinates stay 18 x 32; expanded maps retain that origin and scale. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.RoyaleArenaLayout=api;})(globalThis,function(){'use strict';
const freeze=o=>{for(const v of Object.values(o))if(v&&typeof v==='object')freeze(v);return Object.freeze(o);};
const classic=freeze({id:'classic',custom:false,left:0,right:18,top:0,bottom:32,riverTop:15,riverBottom:17,lanes:[3.5,14.5],bridges:[{left:2.5,right:4.5},{left:13.5,right:15.5}],kings:[9],princessY:[6.5,6.5]});
const triple=freeze({id:'Team3v3',custom:true,theme:'bastion',left:0,right:18,top:-2,bottom:34,kingY:1.5,riverTop:15,riverBottom:17,lanes:[3.5,9,14.5],bridges:[{left:2.25,right:4.75},{left:7.75,right:10.25},{left:13.25,right:15.75}],kings:[5.6,9,12.4],princessY:[6.5,6.5,6.5]});
const tripleJungle=freeze({...triple,id:'Team3v3Jungle',theme:'jungle',revision:1});
const tripleVolcano=freeze({...triple,id:'Team3v3Volcano',theme:'volcano',revision:1});
const bridge=freeze({id:'BridgeBattle',custom:true,theme:'ice',left:5.25,right:12.75,top:-2,bottom:34,riverTop:15,riverBottom:17,lanes:[9],bridges:[{left:7.5,right:10.5}],kings:[9],princessY:[8]});
const bridgeLava=freeze({...bridge,id:'BridgeBattleLava',theme:'lava',revision:1});
const bridgeGarden=freeze({...bridge,id:'BridgeBattleGarden',theme:'garden',revision:1});
const rumble=freeze({id:'TeamRumble',custom:true,theme:'castle',revision:4,river:false,left:-5,right:23,top:-8,bottom:40,kingY:-.5,kingYs:[3.2,.7,-.5,.7,3.2],riverTop:16,riverBottom:16,lanes:[-1,4,9,14,19],bridges:[{left:-5,right:23}],kings:[-1,4,9,14,19],princessY:[9.2,6.9,6.2,6.9,9.2]});
const rumbleReverse=freeze({...rumble,id:'TeamRumbleArcReverse',theme:'moon-castle',revision:1,kingYs:[-.5,.7,3.2,.7,-.5],princessY:[6.2,6.9,9.2,6.9,6.2]});
const rumbleRiver=freeze({id:'TeamRumbleRiverLine',custom:true,theme:'river-fort',revision:1,river:true,left:-3,right:21,top:-5,bottom:37,kingY:1.4,kingYs:[1.4,1.4,1.4,1.4,1.4],riverTop:15,riverBottom:17,lanes:[-1,4,9,14,19],bridges:[{left:.5,right:2.5},{left:5.5,right:7.5},{left:10.5,right:12.5},{left:15.5,right:17.5}],kings:[-1,4,9,14,19],princessY:[7.8,7.8,7.8,7.8,7.8]});
const touchdown=freeze({id:'Touchdown',custom:true,theme:'touchdown',touchdown:true,river:false,left:0,right:18,top:-1,bottom:33,riverTop:16,riverBottom:16,lanes:[3.5,9,14.5],bridges:[{left:0,right:18}],kings:[],princessY:[],goalTop:1.25,goalBottom:30.75});
const touchdownWide=freeze({...touchdown,id:'Touchdown3v3',theme:'touchdown-wide',left:-3,right:21,lanes:[1,6,12,17],goalTop:1.25,goalBottom:30.75,revision:1});
const ffa=freeze({id:'FreeForAll',custom:true,theme:'ffa',ffa:true,river:true,left:-2,right:20,top:-2,bottom:34,riverTop:15,riverBottom:17,verticalRiverLeft:8,verticalRiverRight:10,verticalBridges:[{top:3.5,bottom:6.5},{top:12.5,bottom:19.5},{top:25.5,bottom:28.5}],lanes:[3,9,15],bridges:[{left:1.5,right:3.5},{left:7.5,right:10.5},{left:14.5,right:16.5}],kings:[],princessY:[],revision:1,ffaTeams:[{team:0,color:'blue',king:[1.5,29.5],princess:[[4.2,29.5],[1.5,26.4]]},{team:1,color:'red',king:[16.5,2.5],princess:[[13.8,2.5],[16.5,5.6]]},{team:2,color:'green',king:[1.5,2.5],princess:[[4.2,2.5],[1.5,5.6]]},{team:3,color:'yellow',king:[16.5,29.5],princess:[[13.8,29.5],[16.5,26.4]]}]});
const layouts={classic,Team3v3:triple,Team3v3Jungle:tripleJungle,Team3v3Volcano:tripleVolcano,BridgeBattle:bridge,BridgeBattleLava:bridgeLava,BridgeBattleGarden:bridgeGarden,TeamRumble:rumble,TeamRumbleArcReverse:rumbleReverse,TeamRumbleRiverLine:rumbleRiver,Touchdown:touchdown,Touchdown2v2:touchdown,Touchdown3v3:touchdownWide};
function get(id){return layouts[id]||classic;}
function waterClear(x,y,r=0,id){const a=get(id);if(a.river===false)return true;const horizontal=()=>{const dy=y<a.riverTop?a.riverTop-y:y>a.riverBottom?y-a.riverBottom:0;if(dy>=r&&!(y>a.riverTop&&y<a.riverBottom))return true;const margin=dy>0?Math.sqrt(Math.max(0,r*r-dy*dy)):r;return a.bridges.some(b=>x-margin>=b.left-1e-7&&x+margin<=b.right+1e-7);};if(!horizontal())return false;if(a.verticalRiverLeft===undefined)return true;const dx=x<a.verticalRiverLeft?a.verticalRiverLeft-x:x>a.verticalRiverRight?x-a.verticalRiverRight:0;if(dx>=r&&!(x>a.verticalRiverLeft&&x<a.verticalRiverRight))return true;const margin=dx>0?Math.sqrt(Math.max(0,r*r-dx*dx)):r;return (a.verticalBridges||[]).some(b=>y-margin>=b.top-1e-7&&y+margin<=b.bottom+1e-7);}
function boundsClear(x,y,r=0,id,air=false){const a=get(id);return x-r>=a.left-1e-7&&x+r<=a.right+1e-7&&y-r>=a.top-1e-7&&y+r<=a.bottom+1e-7;}
function forbidden(id,waterFree=false){const a=get(id),rects=[];if(a.left>0)rects.push({left:0,right:a.left,top:a.top,bottom:a.bottom});if(a.right<18)rects.push({left:a.right,right:18,top:a.top,bottom:a.bottom});if(!waterFree&&a.river!==false){let x=a.left;for(const b of [...a.bridges,{left:a.right,right:a.right}]){if(b.left>x)rects.push({left:x,right:b.left,top:a.riverTop,bottom:a.riverBottom});x=b.right;}if(a.verticalRiverLeft!==undefined){let y=a.top;for(const b of [...(a.verticalBridges||[]),{top:a.bottom,bottom:a.bottom}]){if(b.top>y)rects.push({left:a.verticalRiverLeft,right:a.verticalRiverRight,top:y,bottom:b.top});y=b.bottom;}}}return rects;}
function lane(x,id){const a=get(id);let index=0;for(let i=1;i<a.lanes.length;i++)if(Math.abs(a.lanes[i]-x)<Math.abs(a.lanes[index]-x))index=i;return index;}
function towers(team,id){const a=get(id),flip=y=>team?y:32-y;if(!a.custom)return[['KingTower',9,flip(3),0],['PrincessTower',3.5,flip(6.5),0],['PrincessTower',14.5,flip(6.5),0]];const out=[];for(let i=0;i<a.kings.length;i++)out.push(['KingTower',a.kings[i],flip(a.kingYs?.[i]??a.kingY??3),i]);for(let i=0;i<a.lanes.length;i++)out.push(['PrincessTower',a.lanes[i],flip(a.princessY[i]),i]);return out;}
function validSlots(slots,teamSize=3){return Array.isArray(slots)&&slots.length===teamSize*2&&slots.every(x=>Number.isInteger(x)&&x>=0&&x<teamSize)&&[0,1].every(t=>new Set(slots.filter((_,s)=>s%2===t)).size===teamSize);}
function shuffleSlots(random,teamSize=3){const slots=[];for(const team of [0,1]){const row=Array.from({length:teamSize},(_,i)=>i);for(let i=teamSize-1;i>0;i--){const j=Math.floor(random()*(i+1));[row[i],row[j]]=[row[j],row[i]];}for(let i=0;i<teamSize;i++)slots[team+i*2]=row[i];}return slots;}
function limits(id,air=false){const l=get(id);if(air&&!String(id).startsWith('TeamRumble')&&!String(id).startsWith('Touchdown'))return classic;return l;}
return{limits,get,waterClear,boundsClear,forbidden,lane,towers,validSlots,shuffleSlots};});
