/* Offline Clan Wars II, post-Summer-2021 schedule. Local rule overrides: every
   playable war battle is level 9. Destroyed defenses are not repaired midweek. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./core.js'):root.RoyaleCore,n?require('./world.js'):root.RoyaleWorld,n?require('./economy.js'):root.RoyaleEconomy,n?require('./progression.js'):root.RoyaleProgression);if(n)module.exports=api;else root.RoyaleClanWar=api;})(globalThis,function(C,W,E,R){'use strict';
const DAY=W.DAY,WEEK=7*DAY,copy=x=>JSON.parse(JSON.stringify(x)),H=W.hash,MAX_HP=C.entityDef('ClanWarsTowerXbow',9).hp;
const movement=[3000,1800,1000,600,400],leagues=[{name:'Bronze',min:0,defenses:10,gold:400},{name:'Silver',min:600,defenses:12,gold:600},{name:'Gold',min:1500,defenses:15,gold:800},{name:'Legendary',min:3000,defenses:15,gold:1000}];
const firstMonday=(year,month)=>{const d=new Date(Date.UTC(year,month,1));return d.getTime()+((8-d.getUTCDay())%7)*DAY;};
function calendar(now=Date.now()){const t=Math.max(0,Number(now)||0),d=new Date(t),day=Math.floor(t/DAY),weekday=(d.getUTCDay()+6)%7,weekStart=(day-weekday)*DAY;let start=firstMonday(d.getUTCFullYear(),d.getUTCMonth()),end=firstMonday(d.getUTCFullYear(),d.getUTCMonth()+1);if(t<start){end=start;start=firstMonday(d.getUTCFullYear(),d.getUTCMonth()-1);}const weeksInSeason=Math.round((end-start)/WEEK),weekIndex=Math.floor((weekStart-start)/WEEK);return{now:t,day,weekday,weekStart,weekEnd:weekStart+WEEK,seasonStart:start,seasonEnd:end,weeksInSeason,weekIndex,phase:weekday<3?'Training':'Battle',colosseum:weekIndex===weeksInSeason-1,nextReset:(day+1)*DAY};}
function league(trophies){return leagues.filter(l=>l.min<=trophies).at(-1)||leagues[0];}
function eligible(p,now){const c=W.clan(p,p.world.currentClan,now);if(!c)return'Join a clan first';if(c.count<10)return'Your clan needs at least 10 members';if(p.level<6)return'Reach King Level 6 to participate';return null;}
function freshDecks(p){const allowed=C.CARDS.filter(c=>C.canUseCard(p,c.id)).map(c=>c.id),first=p.decks[p.activeDeck].filter(id=>allowed.includes(id)),pool=[...new Set([...first,...allowed])];return[0,1,2,3].map(i=>pool.slice(i*8,i*8+8));}
function rivals(p,season){const own=p.world.currentClan,out=[own];let n=H(own+':'+season)%W.CLAN_COUNT;while(out.length<5){const id=W.clanId(n);if(!out.includes(id))out.push(id);n=(n+7919)%W.CLAN_COUNT;}return out;}
function boatsFor(p,ids){const out={};for(const id of ids){const c=W.clan(p,id),members=c?.memberIds||[],count=Math.min(league(c?.clanTrophies||0).defenses,members.length+(id===p.world.currentClan?1:0));out[id]=Array.from({length:Math.max(1,count)},(_,i)=>({owner:id===p.world.currentClan&&i===0?'self':members[Math.max(0,i-(id===p.world.currentClan?1:0))%Math.max(1,members.length)]||null,hp:[MAX_HP,MAX_HP,MAX_HP],maxHp:MAX_HP}));}return out;}
function fresh(p,cal,old=null){const ids=rivals(p,cal.seasonStart);return{clanId:p.world.currentClan,seasonStart:cal.seasonStart,weekStart:cal.weekStart,day:cal.day,lastClosedDay:Math.floor(cal.weekStart/DAY)-1,decks:old?.decks||freshDecks(p),used:[],rivalIds:ids,movement:Object.fromEntries(ids.map(id=>[id,0])),medalsByDay:{},participation:{},boats:boatsFor(p,ids),defenseDecks:old?.defenseDecks||[],duel:null,tickets:{},history:old?.history||[],rewards:old?.rewards||[],claimed:old?.claimed||[],traderPurchases:old?.traderPurchases||[],traderRerolls:old?.traderRerolls||{},joinedAt:Date.now(),colosseum:cal.colosseum};}
function dailyMemberMedals(p,id,day,progress=1){const c=W.clan(p,id,day*DAY),members=c?.memberIds||[];let medals=0,participants=0;for(const pid of members.slice(0,50)){const h=H(pid+':war:'+day),games=h%5;if(!games)continue;participants++;const wins=(h>>>4)%(games+1);medals+=Math.floor((games*100+wins*100)*progress);}return{medals,participants};}
function dailyRanking(p,war,day,progress=1){return war.rivalIds.map(id=>{const v=dailyMemberMedals(p,id,day,progress),actual=id===war.clanId?(war.medalsByDay[day]||0):0;return{id,medals:v.medals+actual,participants:Math.min(50,v.participants+(actual>0?1:0))};}).sort((a,b)=>b.medals-a.medals||a.id.localeCompare(b.id));}
function closeDay(p,war,day){if((new Date(day*DAY).getUTCDay()+6)%7<3)return;const scores=dailyRanking(p,war,day);for(let i=0;i<scores.length;i++){const id=scores[i].id;
 // A deterministic sample of other clans' boat attacks. Only live defenses can be lost.
 if(!war.colosseum){const defenses=war.boats[id]||[];const live=defenses.map((d,i)=>({d,i})).filter(x=>x.d.hp.some(v=>v>0));const losses=H(id+':boats:'+day)%3;for(let j=0;j<Math.min(losses,live.length);j++){const item=live[(H(day+':'+id)+j)%live.length];item.d.hp=[0,0,0];}}
 const bonus=war.colosseum?0:(war.boats[id]||[]).filter(d=>d.hp.some(v=>v>0)).reduce((s,d,j)=>s+Math.max(20,80-j*5),0);war.movement[id]=(war.movement[id]||0)+movement[i]+bonus;
 }war.history.push({day,scores,movement:{...war.movement}});war.history=war.history.slice(-12);}
function validSavedWar(w){return w&&Number.isFinite(w.weekStart)&&Number.isFinite(w.day)&&Number.isFinite(w.lastClosedDay)&&Array.isArray(w.decks)&&w.decks.length===4&&w.decks.every(d=>Array.isArray(d)&&d.length<=8&&d.every(id=>C.CARD_BY_ID[id]))&&Array.isArray(w.used)&&Array.isArray(w.rivalIds)&&w.rivalIds.length===5&&w.movement&&Array.isArray(w.history)&&Array.isArray(w.rewards)&&Array.isArray(w.claimed)&&w.tickets&&w.boats&&w.participation&&w.medalsByDay;}
function opponentWarDecks(p,person){const pool=E.cardPool({...p,highestTrophies:Math.max(3000,person.trophies),trophies:Math.max(3000,person.trophies)}).map(c=>c.id);pool.sort((a,b)=>H(person.id+':war-card:'+a)-H(person.id+':war-card:'+b));return[0,1,2,3].map(i=>pool.slice(i*8,i*8+8));}
function advance(raw,now=Date.now()){
 const p=C.normalizeProfile(raw),cal=calendar(Math.max(Number(now)||0,p.world.clock||0));if(!p.world.currentClan)return{profile:p,changed:false};let war=p.world.war,changed=false;
 if(!validSavedWar(war)||war.clanId!==p.world.currentClan){war=fresh(p,cal);war.joinedAt=cal.now;p.world.war=war;changed=true;}
 // Only one previously observed week is settled; unobserved years never mint rewards.
 if(war.weekStart!==cal.weekStart){for(let d=war.lastClosedDay+1;d<Math.floor((war.weekStart+WEEK)/DAY);d++){closeDay(p,war,d);war.lastClosedDay=d;}
  const participated=Object.values(war.participation||{}).some(Boolean);if(participated){const rank=war.rivalIds.slice().sort((a,b)=>(war.movement[b]||0)-(war.movement[a]||0)||a.localeCompare(b)).indexOf(war.clanId)+1,id='river-'+war.clanId+'-'+war.weekStart;if(!war.rewards.some(x=>x.id===id)&&!war.claimed.includes(id))war.rewards.push({id,rank,weekStart:war.weekStart,league:league(W.clan(p,war.clanId)?.clanTrophies||0).name});const c=p.world.clans[war.clanId];if(c)c.clanTrophies=Math.max(0,(c.clanTrophies||0)+[20,10,0,-10,-20][rank-1]);}
  const old=war;war=fresh(p,cal,old);war.joinedAt=cal.now;war.rewards=war.rewards.slice(-12);war.claimed=war.claimed.slice(-52);p.world.war=war;changed=true;
 }
 for(let d=war.lastClosedDay+1;d<cal.day;d++){closeDay(p,war,d);war.lastClosedDay=d;changed=true;}
 if(war.day!==cal.day){war.day=cal.day;war.used=[];if(war.duel&&!war.duel.finished){war.duel.finished=true;war.duel.abandoned=true;}changed=true;}
 return{profile:p,changed};
}
function validDeck(p,war,index,deck){return Number.isInteger(index)&&index>=0&&index<4&&Array.isArray(deck)&&deck.length===8&&new Set(deck).size===8&&deck.every(id=>C.CARD_BY_ID[id]&&C.canUseCard(p,id))&&!war.decks.some((d,i)=>i!==index&&d.some(id=>deck.includes(id)));}
function setDeck(raw,index,deck,now=Date.now()){const p=advance(raw,now).profile,w=p.world.war;if(!w)return{ok:false,profile:p,reason:'Join a clan first'};if(w.used.includes(index))return{ok:false,profile:p,reason:'A used war deck cannot be edited today'};if(!validDeck(p,w,index,deck))return{ok:false,profile:p,reason:'Choose 8 owned cards not used in another war deck'};w.decks[index]=deck.slice();return{ok:true,profile:p};}
function autoDecks(raw,now=Date.now()){const p=advance(raw,now).profile,w=p.world.war;if(!w||w.used.length)return{ok:false,profile:p,reason:'Used war decks cannot be replaced today'};w.decks=freshDecks(p);return{ok:true,profile:p};}
function defenseCards(p,owner,now){if(owner==='self'){const existing=p.world.war.defenseDecks;if(existing?.length===3&&existing.every(d=>d.length===4))return copy(existing);}const m=owner==='self'?{trophies:p.trophies,deck:p.decks[p.activeDeck]}:W.player(p,owner,now);const arena=R.arenaForTrophies(m?.trophies||6000).number;const pool=C.CARDS.filter(c=>c.kind==='Troop'&&c.entity&&(owner!=='self'||C.canUseCard(p,c.id))&&(C.DEFAULT_DECK.includes(c.id)||R.cardArenaNumber(c,C.DATA.arenas)<=arena));pool.sort((a,b)=>H(owner+':'+a.id)-H(owner+':'+b.id));return[0,1,2].map(i=>owner==='self'?pool.slice(i*4,i*4+4).map(c=>c.id):Array.from({length:4},(_,j)=>pool[(i*4+j)%pool.length].id));}
function begin(raw,{kind='battle',deckIndex=0,targetClan=null,defenseIndex=0}={},now=Date.now()){
 const p=advance(raw,now).profile,cal=calendar(Math.max(now,p.world.clock||0)),w=p.world.war,reason=eligible(p,now);if(reason)return{ok:false,profile:p,reason};if(Object.values(p.cheats).some(Boolean))return{ok:false,profile:p,reason:'Turn off cheats before playing a war battle'};
 if(!['battle','rotating','duel','boat','defense-test'].includes(kind))return{ok:false,profile:p,reason:'Unknown river task'};
 if(!validDeck(p,w,deckIndex,w.decks[deckIndex]))return{ok:false,profile:p,reason:'Build a complete, unique war deck first'};
 if(kind!=='defense-test'&&w.used.includes(deckIndex))return{ok:false,profile:p,reason:'This deck is on cooldown until the daily reset'};
 const ongoing=Object.values(w.tickets).find(t=>t.status==='playing');if(ongoing&&kind!=='defense-test')return{ok:false,profile:p,reason:'Finish or forfeit your current war battle'};
 if(w.duel&&!w.duel.finished&&w.duel.score.every(x=>x<2)&&kind!=='duel')return{ok:false,profile:p,reason:'Finish your current Duel first'};
 let target=targetClan||w.rivalIds[1];if(!w.rivalIds.includes(target)||target===w.clanId)target=w.rivalIds[1];const opponents=W.members(p,target,now).filter(m=>m.id!=='self'),opponent=opponents[H(w.clanId+':'+cal.day+':'+w.used.length)%opponents.length]||W.matchOpponent(p,p.battleSerial,now);
 let chosen=opponent;if(kind==='duel'){
  if(!w.duel||w.duel.finished){if(4-w.used.length<3)return{ok:false,profile:p,reason:'A Duel needs at least 3 unused war decks'};w.duel={id:'duel-'+(++p.world.serial),day:cal.day,opponentId:opponent.id,score:[0,0],rounds:[],finished:false};}
  chosen=W.player(p,w.duel.opponentId,now)||opponent;
 }
 let boat=null;if(kind==='boat'||kind==='defense-test'){
  if(kind==='boat'&&(cal.phase==='Training'||cal.colosseum))return{ok:false,profile:p,reason:cal.colosseum?'Boat attacks are unavailable in the Colosseum':'Boat attacks open on Battle Days'};
  const defender=kind==='defense-test'?{owner:'self',hp:[MAX_HP,MAX_HP,MAX_HP],maxHp:MAX_HP}:w.boats[target]?.[defenseIndex];if(!defender||defender.hp.every(v=>v<=0))return{ok:false,profile:p,reason:'Choose a surviving boat defense'};
  boat={hp:[...defender.hp],maxHp:MAX_HP,cards:defenseCards(p,defender.owner,now),targetClan:kind==='defense-test'?w.clanId:target,defenseIndex,test:kind==='defense-test'};if(boat.cards.some(d=>d.length!==4))return{ok:false,profile:p,reason:'Unlock 12 different troop cards to set up a boat defense'};
 }
 const aiDecks=opponentWarDecks(p,chosen),aiDeckIndex=kind==='duel'?w.duel.rounds.length:w.used.length%4,enemyDeck=aiDecks[aiDeckIndex];
 const id='war-'+cal.day+'-'+(++p.world.serial),ticket={id,kind,deckIndex,targetClan:target,defenseIndex,day:cal.day,weekStart:cal.weekStart,training:cal.phase==='Training'||kind==='defense-test',status:'playing',startedAt:cal.now,opponentId:chosen.id,duelId:kind==='duel'?w.duel.id:null};
 if(kind!=='defense-test')w.used.push(deckIndex);w.tickets[id]=ticket;const keys=Object.keys(w.tickets);for(const old of keys.slice(0,Math.max(0,keys.length-40)))if(w.tickets[old].status!=='playing')delete w.tickets[old];
 const mode=boat?'ClanWar_BoatBattle':kind==='rotating'?['DoubleElixir','TripleElixir','SuddenDeath','RampUp'][H(cal.weekStart)%4]:'Default';
 return{ok:true,profile:p,ticket,options:{queue:kind==='defense-test'?'training':'clan-war',mode,profile:p,deck:[...w.decks[deckIndex]],enemyDeck,opponent:{...chosen,deck:enemyDeck},practice:true,shuffleDeck:true,seed:H(id+chosen.id),warContext:{ticketId:id,kind},boat}};
}
function resolve(raw,id,result,now=Date.now()){
 const p=C.normalizeProfile(raw),w=p.world.war,t=w?.tickets?.[id];if(!t||t.status!=='playing')return{ok:false,profile:p,reason:'War result already settled or unavailable'};t.status='completed';let winner=[0,1].includes(result.winner)?result.winner:(H(t.id)%2);t.winner=winner;t.endedAt=now;const won=winner===0,own=W.clan(p,w.clanId,now),tier=league(own?.clanTrophies||0);let medals=t.training?0:won?200:100,gold=won?tier.gold:Math.floor(tier.gold/10);
 if(t.kind==='duel'){
  const d=w.duel;if(d&&d.id===t.duelId&&!d.finished){d.score[winner]++;d.rounds.push({ticketId:id,winner,deck:t.deckIndex});d.finished=d.score.some(x=>x>=2);if(d.finished){const win=d.score[0]>=2;medals=t.training?0:(win?250:100)*d.rounds.length;gold=win?tier.gold*3:Math.floor(tier.gold*.3);d.winner=win?0:1;if(w.colosseum&&own&&p.world.clans[own.id])p.world.clans[own.id].clanTrophies=Math.max(0,(own.clanTrophies||0)+(win?20:-10));}else{medals=0;gold=0;}}
 }
 if(t.kind==='boat'){const d=w.boats[t.targetClan]?.[t.defenseIndex];if(d&&Array.isArray(result.boatHp)&&result.boatHp.length===3){d.hp=d.hp.map((old,i)=>old<=0?0:Math.max(0,Math.min(old,Number(result.boatHp[i])||0)));d.hp=d.hp.map(v=>v>0?Math.max(v,Math.round(MAX_HP*(C.DATA.globals.BOAT_PVE_MIN_TOWER_HEALTH_PERCENT?.NumberValue||25)/100)):0);d.lastAttackedAt=now;}medals=t.training?0:won?125:75;gold=won?Math.floor(tier.gold/2):Math.floor(tier.gold/10);}
 if(t.kind==='defense-test'){medals=0;gold=0;}
 if(!t.training){w.medalsByDay[t.day]=(w.medalsByDay[t.day]||0)+medals;w.participation[t.weekStart]=true;}
 p.gold=Math.min(9999999,p.gold+gold);t.medals=medals;t.gold=gold;return{ok:true,profile:p,medals,gold,duel:w.duel};
}
function forfeit(raw,id,now=Date.now()){return resolve(raw,id,{winner:1,forfeit:true},now);}
function setDefense(raw,decks,now=Date.now()){const p=advance(raw,now).profile,w=p.world.war;if(!w)return{ok:false,profile:p,reason:'Join a clan first'};if(calendar(now).phase!=='Training')return{ok:false,profile:p,reason:'Boat defenses can be set on Training Days'};if(!Array.isArray(decks)||decks.length!==3||decks.some(d=>!Array.isArray(d)||d.length!==4)||new Set(decks.flat()).size!==12||decks.flat().some(id=>!C.CARD_BY_ID[id]?.entity||C.CARD_BY_ID[id].kind!=='Troop'||!C.canUseCard(p,id)))return{ok:false,profile:p,reason:'Choose 12 different owned troop cards, 4 for each tower'};w.defenseDecks=copy(decks);return{ok:true,profile:p};}
function view(raw,now=Date.now()){const p=advance(raw,now).profile,cal=calendar(Math.max(now,p.world.clock||0)),w=p.world.war;if(!w)return{calendar:cal,reason:'Join a clan first',rivals:[],boats:{},decks:[],used:[]};const progress=(cal.now%DAY)/DAY,scores=dailyRanking(p,w,cal.day,progress);return{...copy(w),calendar:cal,reason:eligible(p,now),rivals:w.rivalIds.map(id=>{const c=W.clan(p,id,now);return{id,name:c?.name||id,badge:c?.badge||'clan-badge',movement:w.movement[id]||0,medals:scores.find(x=>x.id===id)?.medals||0,members:c?.count||0};}),daily:scores,league:league(W.clan(p,w.clanId,now)?.clanTrophies||0),maxHp:MAX_HP};}
function claimReward(raw,id){const p=C.normalizeProfile(raw),w=p.world.war,r=w?.rewards.find(r=>r.id===id);if(!r||w.claimed.includes(id))return{ok:false,profile:p,reason:'Reward unavailable or already claimed'};const scale=6-r.rank,arena=R.highestArena(p).number,cards=[];for(const [rarity,n]of [['Common',80*scale],['Rare',10*scale],['Epic',scale],...(r.rank===1?[['Legendary',1]]:[])]){const pool=E.cardPool(p,arena,rarity);if(pool.length)cards.push({id:pool[H(id+rarity)%pool.length].id,count:n});}const reward={gold:500*scale,cards,tradeTokens:{Common:1},magicItems:r.rank<=2?{'chest-key':1}:{}};E.grant(p,reward);w.claimed.push(id);w.rewards=w.rewards.filter(x=>x.id!==id);return{ok:true,profile:p,reward};}
function trader(raw,now=Date.now()){const p=C.normalizeProfile(raw),day=Math.floor(now/DAY),rarities=['Common','Rare','Epic','Legendary'],rarity=rarities[day%4],pool=E.cardPool(p,undefined,rarity);if(pool.length<2)return{day,rarity,receive:[],give:[],count:W.TRADE_COUNTS[rarity],bought:false};const random=C.rng(H(p.world.seed+':trader:'+day)),sorted=pool.map(c=>({id:c.id,k:random()})).sort((a,b)=>a.k-b.k),receive=Array.from({length:3},(_,i)=>sorted[i%sorted.length].id);const offset=(p.world.war?.traderRerolls?.[day]||0)+3,give=Array.from({length:3},(_,i)=>sorted[(i+offset)%sorted.length].id);return{day,rarity,receive,give,count:W.TRADE_COUNTS[rarity],bought:p.world.war?.traderPurchases?.includes(day)||false};}
function tradeWithTrader(raw,receive,give,now=Date.now()){const p=advance(raw,now).profile,o=trader(p,now);if(!p.world.war)return{ok:false,profile:p,reason:'Join a clan first'};if(o.bought||!o.receive.includes(receive)||!o.give.includes(give)||receive===give)return{ok:false,profile:p,reason:'Choose two different cards from today’s offer'};if(p.tradeTokens[o.rarity]<1||p.copies[give]<o.count)return{ok:false,profile:p,reason:'Not enough spare cards or matching Trade Tokens'};p.tradeTokens[o.rarity]--;p.copies[give]-=o.count;E.grant(p,{cards:[{id:receive,count:o.count}]});p.world.war.traderPurchases.push(o.day);p.world.war.traderPurchases=p.world.war.traderPurchases.slice(-35);return{ok:true,profile:p};}
function rerollTrader(raw,now=Date.now()){const p=advance(raw,now).profile,day=Math.floor(now/DAY);if(!p.world.war||p.gems<10)return{ok:false,profile:p,reason:'A reroll costs 10 gems'};p.gems-=10;p.world.war.traderRerolls[day]=(p.world.war.traderRerolls[day]||0)+1;return{ok:true,profile:p};}
return{DAY,WEEK,MAX_HP,calendar,league,advance,view,setDeck,autoDecks,begin,resolve,forfeit,setDefense,defenseCards,claimReward,trader,tradeWithTrader,rerollTrader};});
