/* Permanent crown progression. Claims are compact disjoint milestone ranges;
   nothing here pays currency, changes King XP, or spends Crown Chest crowns. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.RoyaleCrownRoad=api;})(globalThis,function(){'use strict';
const MAX_CROWNS=9999999,integer=(v,max=MAX_CROWNS)=>Number.isFinite(v)?Math.max(0,Math.min(max,Math.floor(v))):0;
function lifetime(p={}){const recent=Array.isArray(p.history)?p.history.filter(h=>h&&!h.practice&&h.queue!=='replay'&&[-1,0,1].includes(h.winner)).slice(0,20).reduce((n,h)=>n+integer(h.crowns?.[0],h.mode==='TeamRumble'?10:h.mode==='Team3v3'?6:3),0):0;return Math.max(integer(p.lifetimeCrowns),integer(p.earnedCrowns),integer(p.crownChestClaimed),recent);}
function normalizeClaims(raw,limit){const pairs=Array.isArray(raw)?raw.filter(x=>Array.isArray(x)&&x.length===2&&x.every(Number.isSafeInteger)&&x[0]>=1&&x[1]>=x[0]&&x[0]<=limit).map(([lo,hi])=>[lo,Math.min(limit,hi)]).sort((a,b)=>a[0]-b[0]):[],out=[];for(const p of pairs){const last=out[out.length-1];if(last&&p[0]<=last[1]+1)last[1]=Math.max(last[1],p[1]);else out.push(p);}return out;}
function normalize(p){const lifetimeCrowns=lifetime(p),milestones=Math.floor(lifetimeCrowns/10);return{lifetimeCrowns,crownLevel:1+milestones,crownRoadClaims:normalizeClaims(p.crownRoadClaims,milestones)};}
function progress(p){const v=normalize(p),milestones=v.crownLevel-1,claimed=v.crownRoadClaims.reduce((n,[lo,hi])=>n+hi-lo+1,0);let next=1;for(const [lo,hi] of v.crownRoadClaims){if(lo>next)break;next=Math.max(next,hi+1);}return{...v,milestones,remainder:v.lifetimeCrowns%10,unclaimed:milestones-claimed,nextUnclaimed:next<=milestones?next:null};}
function claimed(p,n){return normalize(p).crownRoadClaims.some(([lo,hi])=>n>=lo&&n<=hi);}
function state(p,n){if(!Number.isSafeInteger(n)||n<1||n>Math.floor(lifetime(p)/10))return'locked';return claimed(p,n)?'claimed':'available';}
function mark(p,n){return normalizeClaims([...p.crownRoadClaims,[n,n]],Math.floor(lifetime(p)/10));}
function reward(n){if(!Number.isSafeInteger(n)||n<1||n>Math.floor(MAX_CROWNS/10))return null;const cap=(x,limit=9999999)=>Math.min(limit,Math.floor(x));const r={gold:cap(500+150*n+25*n*n),gems:0,cards:[],wildcards:{Common:cap(15+5*n+Math.pow(n,1.25),100000)}};if(n>=2)r.wildcards.Rare=cap(5+n+Math.pow(n,1.12)/3,100000);if(n%5===0){r.gems=cap(10+4*n+Math.pow(n,1.25));r.wildcards.Epic=cap(2+n/5+Math.pow(n,1.1)/10,100000);}if(n%3===0)r.wildcards.Epic=Math.max(r.wildcards.Epic||0,cap(2+n/5+Math.pow(n,1.1)/10,100000));if(n%10===0){r.wildcards.Legendary=cap(1+n/50,100000);const book=n>=100?'book-of-books':n>=60?'legendary-book':n>=30?'epic-book':n>=20?'rare-book':'common-book';r.magicItems={[book]:1};}if(n%7===0)r.magicItems={...r.magicItems,'magic-coin':Math.min(10,1+Math.floor(n/100))};if(n%25===0){r.wildcards.Legendary=cap(1+n/50,100000);const id=n>=100?'book-of-books':n>=75?'legendary-book':n>=50?'epic-book':'rare-book';r.magicItems={...r.magicItems,[id]:Math.min(10,1+Math.floor(n/100))};}if(n%10===0)r.chestKind=n%50===0?'treasure':n>=30&&n%30===0?'legendary':n%20===0?'giant':'magic';return r;}
return{MAX_CROWNS,lifetime,normalize,progress,normalizeClaims,claimed,state,mark,reward};});
