/* Paged named ranked decks and independent full-catalog casual deck libraries. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./core.js'):root.RoyaleCore);if(n)module.exports=api;else root.RoyaleDeckManager=api;})(globalThis,function(C){'use strict';
const MAX_DECKS=C.MAX_DECKS,PAGE_SIZE=C.DECK_PAGE_SIZE,MODE_DECKS=C.MODE_DECKS;
function add(raw){const p=C.normalizeProfile(raw);if(p.decks.length>=MAX_DECKS)return{ok:false,profile:p,reason:'All '+MAX_DECKS+' deck slots are in use'};p.decks.push([...p.decks[p.activeDeck]]);p.deckNames.push(C.deckName('',p.decks.length-1));p.activeDeck=p.decks.length-1;return{ok:true,profile:p};}
function remove(raw,index){const p=C.normalizeProfile(raw);if(!Number.isInteger(index)||index<0||index>=p.decks.length)return{ok:false,profile:p,reason:'Deck not found'};if(p.decks.length<=1)return{ok:false,profile:p,reason:'Keep at least one battle deck'};p.decks.splice(index,1);p.deckNames.splice(index,1);if(index<p.activeDeck)p.activeDeck--;else if(index===p.activeDeck)p.activeDeck=Math.min(index,p.decks.length-1);return{ok:true,profile:p};}
function rename(raw,index,value){const p=C.normalizeProfile(raw);if(!Number.isInteger(index)||index<0||index>=p.decks.length||typeof value!=='string')return{ok:false,profile:p,reason:'Deck not found'};p.deckNames[index]=C.deckName(value,index);return{ok:true,profile:p};}
function page(raw,index){const decks=Array.isArray(raw?.decks)&&raw.decks.length?raw.decks:[C.DEFAULT_DECK],count=Math.ceil(decks.length/PAGE_SIZE),number=Math.max(0,Math.min(count-1,Number.isFinite(index)?Math.floor(index):Math.floor((raw?.activeDeck||0)/PAGE_SIZE)));return{page:number,count,indices:Array.from({length:Math.min(PAGE_SIZE,decks.length-number*PAGE_SIZE)},(_,i)=>number*PAGE_SIZE+i)};}
function random(raw,seed=1,size=8){const r=C.rng(seed),out=[...C.CARDS];for(let i=out.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out.slice(0,size).map(c=>c.id);}
function modeSet(p,mode){const cfg=MODE_DECKS[mode];if(!cfg)return null;const set=p.modeDeckSets?.[mode]||{active:0,decks:[p[cfg.key]],names:['Deck 1']};return{cfg,set};}
function modeState(raw,mode){const p=C.normalizeProfile(raw),m=modeSet(p,mode);if(!m)return null;const {cfg,set}=m,eligible=C.CARDS.filter(c=>C.allowedInMode(c.id,mode)).map(c=>c.id),active=Math.max(0,Math.min(set.decks.length-1,set.active||0)),deck=[...set.decks[active]],duplicates=p.cheats.duplicates,valid=C.validDeck(deck,{size:cfg.size,duplicates})&&deck.every(id=>eligible.includes(id));return {...cfg,deck,eligible,eligibleCount:eligible.length,valid,duplicates,missing:deck.filter(id=>!id).length,active,decks:set.decks.map(d=>[...d]),names:[...set.names],page:Math.floor(active/PAGE_SIZE),pageCount:Math.ceil(set.decks.length/PAGE_SIZE)};}
function syncMode(p,mode){const cfg=MODE_DECKS[mode],set=p.modeDeckSets[mode];p[cfg.key]=[...set.decks[set.active]];}
function setModeCard(raw,mode,slot,id){const p=C.normalizeProfile(raw),state=modeState(p,mode);if(!state||!Number.isInteger(slot)||slot<0||slot>=state.size||!state.eligible.includes(id))return{ok:false,profile:p,reason:'This card is not allowed in this mode'};const set=p.modeDeckSets[mode],deck=set.decks[set.active],other=deck.indexOf(id);if(!state.duplicates&&other>=0&&other!==slot)[deck[slot],deck[other]]=[deck[other],deck[slot]];else deck[slot]=id;syncMode(p,mode);return{ok:true,profile:p};}
function modeAdd(raw,mode){const p=C.normalizeProfile(raw),m=modeSet(p,mode);if(!m)return{ok:false,profile:p,reason:'Mode deck not found'};const set=p.modeDeckSets[mode];if(set.decks.length>=MAX_DECKS)return{ok:false,profile:p,reason:'All '+MAX_DECKS+' deck slots are in use'};set.decks.push([...set.decks[set.active]]);set.names.push(C.deckName('',set.decks.length-1));set.active=set.decks.length-1;syncMode(p,mode);return{ok:true,profile:p};}
function modeRemove(raw,mode,index){const p=C.normalizeProfile(raw),m=modeSet(p,mode);if(!m)return{ok:false,profile:p,reason:'Mode deck not found'};const set=p.modeDeckSets[mode];if(set.decks.length<=1)return{ok:false,profile:p,reason:'Keep at least one deck'};if(!Number.isInteger(index)||index<0||index>=set.decks.length)return{ok:false,profile:p,reason:'Deck not found'};set.decks.splice(index,1);set.names.splice(index,1);set.active=Math.min(set.active,index,set.decks.length-1);syncMode(p,mode);return{ok:true,profile:p};}
function modeRename(raw,mode,index,value){const p=C.normalizeProfile(raw),m=modeSet(p,mode);if(!m||!Number.isInteger(index)||index<0||index>=p.modeDeckSets[mode].decks.length)return{ok:false,profile:p,reason:'Deck not found'};p.modeDeckSets[mode].names[index]=C.deckName(value,index);return{ok:true,profile:p};}
function modeSelect(raw,mode,index){const p=C.normalizeProfile(raw),m=modeSet(p,mode);if(!m||!Number.isInteger(index)||index<0||index>=p.modeDeckSets[mode].decks.length)return{ok:false,profile:p,reason:'Deck not found'};p.modeDeckSets[mode].active=index;syncMode(p,mode);return{ok:true,profile:p};}
function modePage(raw,mode,pageIndex){const p=C.normalizeProfile(raw),m=modeSet(p,mode);if(!m)return null;const set=p.modeDeckSets[mode],count=Math.ceil(set.decks.length/PAGE_SIZE),pg=Math.max(0,Math.min(count-1,Number(pageIndex)||0));return{page:pg,count,indices:Array.from({length:Math.min(PAGE_SIZE,set.decks.length-pg*PAGE_SIZE)},(_,i)=>pg*PAGE_SIZE+i)};}
return{MAX_DECKS,PAGE_SIZE,add,remove,rename,page,random,MODE_DECKS,modeState,setModeCard,modeAdd,modeRemove,modeRename,modeSelect,modePage};});
