/* Source-asset battle graphics; original demo HUD primitives. */
(function(root){'use strict';
const TAU=Math.PI*2;
function rounded(c,x,y,w,h,r,fill,stroke,lw=1){c.beginPath();c.roundRect(x,y,w,h,r);if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.lineWidth=lw;c.stroke()}}
function poly(c,pts,fill,stroke,lw=1){c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.lineWidth=lw;c.stroke()}}
function ellipse(c,x,y,rx,ry,fill,stroke,lw=1){c.beginPath();c.ellipse(x,y,rx,ry,0,0,TAU);c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=lw;c.stroke()}}
function line(c,x,y,tx,ty,color,width=2){c.beginPath();c.moveTo(x,y);c.lineTo(tx,ty);c.lineWidth=width;c.strokeStyle=color;c.lineCap='round';c.stroke()}
function text(c,str,x,y,size=14,color='#fff',align='center',outline=true){if(root.RoyaleText?.draw(c,str,x,y,size,color,align,outline?'#162433':null))return;c.font=`900 ${size}px "Arial Black", "Trebuchet MS", sans-serif`;c.textAlign=align;c.textBaseline='middle';if(outline){c.strokeStyle='#162433';c.lineJoin='round';c.lineWidth=Math.max(2,size*.13);c.strokeText(String(str),x,y)}c.fillStyle=color;c.fillText(String(str),x,y)}
function gradient(c,x,y,tx,ty,stops){const g=c.createLinearGradient(x,y,tx,ty);stops.forEach((s,i)=>g.addColorStop(i/(stops.length-1),s));return g}
function crown(c,x,y,scale=1,color='#ffd65d'){c.save();c.translate(x,y);c.scale(scale,scale);poly(c,[[-19,-12],[-10,-4],[0,-18],[10,-4],[19,-12],[15,12],[-15,12]],color,'#7e4a16',2);rounded(c,-15,8,30,7,2,'#ffb633','#8c571b',1.5);ellipse(c,0,1,3.5,5,'#5bc7ee','#e6ac31',1);line(c,-13,10,13,10,'#ffed9a',2);c.restore()}
function gem(c,x,y,s=1){c.save();c.translate(x,y);c.scale(s,s);poly(c,[[0,-13],[13,-5],[9,11],[-8,12],[-14,-3]],'#6ff593','#19764e',2);poly(c,[[0,-13],[2,1],[13,-5]],'#beffcb');poly(c,[[2,1],[9,11],[-8,12]],'#36b765');c.restore()}
function droplet(c,x,y,s=1){c.save();c.translate(x,y);c.scale(s,s);c.beginPath();c.moveTo(0,-20);c.bezierCurveTo(-9,-11,-17,1,-16,10);c.bezierCurveTo(-13,29,16,29,17,10);c.bezierCurveTo(17,1,6,-11,0,-20);c.fillStyle=gradient(c,-13,-20,14,25,['#f8b5ff','#d94deb','#8828b7']);c.fill();c.strokeStyle='#55157d';c.lineWidth=3;c.stroke();ellipse(c,-6,3,4,7,'#ffc3ff');c.restore()}
function unit(c,id,x,y,scale=1,team=0,t=0,attack=0,portrait=false){const lib=root.RoyaleNative?.library;if(lib?.ready)lib.unit(c,id,x,y,team,t,attack?'attack':'idle',team===0?-Math.PI/2:Math.PI/2,0,scale);}
function spellArt(c,id,x,y,s=1){c.save();c.translate(x,y);c.scale(s,s);if(id==='fireball'){poly(c,[[1,4],[-28,-38],[-19,-38],[-41,-62],[-16,-48],[-14,-57],[17,-22]],'#ec692d');poly(c,[[0,0],[-19,-33],[-8,-29],[-17,-44],[11,-22]],'#ffd55b');ellipse(c,0,-7,21,23,gradient(c,-10,-26,13,15,['#ffe879','#ff992c','#cf3d30']),'#ffb842',2);ellipse(c,-4,-13,11,14,'#fff2a1');}else{for(let i=0;i<3;i++){const ox=(i-1)*20;c.save();c.translate(ox,-i*5);c.rotate(.45);line(c,0,-48,0,13,'#dec699',4);poly(c,[[0,17],[-8,1],[0,5],[8,1]],'#dce5e9','#526b7a',1);poly(c,[[0,-36],[-9,-49],[-9,-35],[0,-25]],'#f1687b','#9d384b',1);poly(c,[[0,-36],[9,-49],[9,-35],[0,-25]],'#eb7184','#9d384b',1);c.restore();}}c.restore()}
function card(c,id,width=108,height=136){
 const def=RoyaleCore.CARD_BY_ID[id],asset=root.RoyaleAssets?.store?.get(id);
 c.clearRect(0,0,width,height);c.save();
 if(c.canvas?.dataset){c.canvas.dataset.artId=id;c.canvas.dataset.artStatus=asset?.status||'idle';}
 if(asset?.status==='ready'){
  const b=asset.bounds,r=root.RoyaleAssets.containRect(b.width,b.height,width,height,2);
  c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';
  c.drawImage(asset.image,b.x,b.y,b.width,b.height,r.x,r.y,r.width,r.height);
  // Keep names legible without replacing the original card frame or artwork.
  c.fillStyle=gradient(c,0,height-25,0,height-4,['rgba(9,17,30,0)','rgba(9,17,30,.8)']);
  c.fillRect(r.x+4,height-26,Math.max(0,r.width-8),20);
 }else{
  rounded(c,3,2,width-6,height-5,8,'#18334a','#7798b0',2);
  text(c,asset?.status==='error'?'Art unavailable':'Loading art…',width/2,height*.5,Math.max(6,width*.1));
 }
 text(c,def.name,width/2,height-11,Math.max(6,Math.min(13,width*(def.name.length>10?.098:.118))));
 c.restore();
}
function tower(c,t,showHP=true,time=0){root.RoyaleNative?.library?.drawTower(c,t,time);if(showHP)root.RoyalePresentation?.health(c,t,time);}
function arenaBase(c,time=0,overtime=false){root.RoyaleNative?.library?.drawArena(c,time,overtime);}
function drawPlacementBubble(c,f){if(!f)return;const ok=f.ok&&f.affordable&&!f.cycling,cx=f.x,cy=f.y;c.save();c.lineWidth=3;c.strokeStyle=ok?'rgba(255,255,255,.94)':'rgba(255,104,116,.95)';c.fillStyle=ok?'rgba(244,252,255,.15)':'rgba(255,65,82,.18)';c.shadowColor=ok?'rgba(238,252,255,.6)':'rgba(255,30,50,.45)';c.shadowBlur=7;if(f.spell&&(f.shape?.kind==='line'||f.shape?.kind==='rolling')){const q=f.shape,dx=q.x2-q.x,dy=q.y2-q.y,len=Math.hypot(dx,dy)||1;c.lineCap='round';c.lineWidth=Math.max(8,(q.width||.5)*2*RoyaleCore.SX);c.strokeStyle=ok?'rgba(255,255,255,.16)':'rgba(255,65,82,.18)';c.beginPath();c.moveTo(q.x,q.y);c.lineTo(q.x2,q.y2);c.stroke();c.lineWidth=3;c.strokeStyle=ok?'rgba(255,255,255,.88)':'rgba(255,104,116,.95)';for(const side of [-1,1]){const px=-dy/len*(q.width||.5)*RoyaleCore.SX*side,py=dx/len*(q.width||.5)*RoyaleCore.SY*side;c.beginPath();c.moveTo(q.x+px,q.y+py);c.lineTo(q.x2+px,q.y2+py);c.stroke();}}else{const radius=f.spell?(f.shape?.radius||f.radius||1):Math.max(.55,(f.range||0)+(f.radius||0));c.beginPath();c.ellipse(cx,cy,radius*RoyaleCore.SX,radius*RoyaleCore.SY,0,0,TAU);c.fill();c.stroke();if(!f.spell&&f.tiles?.length){const cols=f.tiles.map(t=>t.col),rows=f.tiles.map(t=>t.row),x0=(Math.min(...cols))*RoyaleCore.SX,y0=(Math.min(...rows))*RoyaleCore.SY,x1=(Math.max(...cols)+1)*RoyaleCore.SX,y1=(Math.max(...rows)+1)*RoyaleCore.SY;c.shadowBlur=0;c.fillStyle=ok?'rgba(116,223,255,.24)':'rgba(255,88,96,.22)';rounded(c,x0+2,y0+2,x1-x0-4,y1-y0-4,6,c.fillStyle,ok?'rgba(221,251,255,.75)':'rgba(255,170,170,.75)',1.5);}}c.restore();}
function drawPlacementLabel(c,f){if(!f||!Number.isFinite(f.x)||!Number.isFinite(f.y))return;const y=Math.max(25,f.y-(f.spell?42:58));c.save();c.shadowColor='rgba(0,0,0,.65)';c.shadowBlur=2;text(c,f.name||'',f.x,y,18,'#fff','center',true);text(c,'lvl.'+f.level,f.x,y+18,13,'#fff','center',true);c.restore();}
function drawTargetWarnings(c,f,time){for(const e of f?.retargeting||[]){const bob=Math.sin(time*8+e.id)*1.2,x=e.x,y=e.y-49+bob;c.save();c.font='900 28px Arial Black,Arial,sans-serif';c.textAlign='center';c.textBaseline='middle';c.lineJoin='round';c.lineWidth=6;c.strokeStyle='#5c1730';c.strokeText('!',x,y);c.lineWidth=2;c.strokeStyle='#19070e';c.strokeText('!',x,y);c.fillStyle='#fff';c.fillText('!',x,y);c.restore();}}
function drawSpellHighlights(c,f,time,b,lib){if(!f?.spell||!f.ok)return;for(const hit of f.affected||[]){const u=b.getEntity(hit.id);if(!u||u.hp<=0)continue;c.save();c.globalAlpha=.58;c.globalCompositeOperation='screen';c.filter='brightness(1.65) saturate(.55)';if(u.king!==undefined)lib.drawTower(c,u,time);else lib.unit(c,u.entity,u.x,u.y,u.team,b.time,u.wait>0?'idle':u.visualState||'idle',u.heading,u.visualStarted||0,1,{elapsed:u.animationTime||0,idleTime:u.visualTime||0,attackDuration:u.visualDuration,height:RoyaleNative.entityElevation(u),entity:u});c.restore();}}
function battle(c,b,time,pointer,selected,alpha=1,compactSwarmLevels=true){if(root.RoyaleGraphics?.current?.potato)return root.RoyalePotato.draw(c,b,time,pointer,selected,alpha,compactSwarmLevels);const lib=root.RoyaleNative?.library,visualTime=Number.isFinite(b.visualTime)?b.visualTime:time;c.clearRect(0,0,540,root.RoyaleBattleView.layout.height);c.fillStyle=b.mode==='TeamRumble'?'#19283d':'#22202a';c.fillRect(0,0,540,root.RoyaleBattleView.layout.height);c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';const V=root.RoyaleBattleView;c.save();c.beginPath();c.rect(V.viewport.x,V.viewport.y,V.viewport.width,V.viewport.height);c.clip();c.translate(V.camera.x,V.camera.y);c.scale(V.camera.scale,V.camera.scale);if(!root.RoyaleCustomArena?.draw(c,b,lib))arenaBase(c,visualTime,b.overtime);for(const t of b.towers)lib?.drawTowerShadow(c,t);
 const fx=lib?.fx;fx?.begin();fx?.areas(c,b,'ground');fx?.events(c,b,'ground');fx?.movement(c,b,'ground');fx?.unitStates(c,b,'ground');
 let placementForecast=null;
 if(selected!==null){const original=b.card(0,selected),card=original?.mirrorCard?{...RoyaleCore.cardAt(original.mirrorCard,original.level),cost:original.cost}:original;
  if(card&&pointer&&pointer.x>=b.arenaLayout.left*RoyaleCore.SX&&pointer.x<=b.arenaLayout.right*RoyaleCore.SX&&pointer.y>=b.arenaLayout.top*RoyaleCore.SY&&pointer.y<=b.arenaLayout.bottom*RoyaleCore.SY){placementForecast=b.placementPreview(0,selected,pointer.x,pointer.y);const f=placementForecast,ok=f.ok&&f.affordable&&!f.cycling;c.save();
   if(!b.cheats?.placement&&!card.spell&&!card.source.CanDeployOnEnemySide){c.fillStyle='rgba(181,27,47,.12)';const enemy=b.towers.filter(t=>t.team===1&&!t.king).sort((x,y)=>x.x-y.x);const lanes=b.arenaLayout?.custom?b.arenaLayout.lanes.length:2;const a=b.arenaLayout,width=(a.right-a.left)*RoyaleCore.SX,y=a.top*RoyaleCore.SY;for(let side=0;side<lanes;side++)c.fillRect(a.left*RoyaleCore.SX+side*width/lanes,y,width/lanes,(enemy[side]?.hp<=0?200:a.river===false?320:340)-y);if(b.mode==='BridgeBattle'){c.fillStyle='rgba(181,27,47,.3)';c.fillRect(0,y,a.left*RoyaleCore.SX,(a.bottom-a.top)*RoyaleCore.SY);c.fillRect(a.right*RoyaleCore.SX,y,(18-a.right)*RoyaleCore.SX,(a.bottom-a.top)*RoyaleCore.SY);}}
   drawPlacementBubble(c,f);if(card.entity&&Number.isFinite(f.x)){c.save();c.globalAlpha=ok?.58:.38;c.filter=ok?'brightness(1.18) saturate(.8)':'sepia(.4) saturate(1.8) hue-rotate(300deg)';const members=f.members?.length?f.members:[{entity:card.entity,x:f.x,y:f.y}];for(const m of members)lib.unit(c,m.entity||card.entity,m.x,m.y,0,visualTime,'idle',-Math.PI/2,0,1,{ghost:true});c.restore();}drawPlacementLabel(c,f);if(!ok&&f.reason)text(c,f.reason,f.x,Math.min(620,f.y+45),12,'#ffd8da');c.restore();}}
 // Teammate intent is a declared placement, not access to an opponent's hand.
 if(b.is2v2&&b.bots[2]?.intent){const a=b.bots[2].intent.action,card=RoyaleCore.CARD_BY_ID[a.card];c.save();c.globalAlpha=.42;if(card?.entity)lib.unit(c,card.entity,a.x,a.y,0,visualTime,'idle',-Math.PI/2,0,1);c.setLineDash([4,3]);c.strokeStyle='#a4eaff';c.lineWidth=2;c.beginPath();c.ellipse(a.x,a.y,card?.spell?(card.radiusTiles||1)*RoyaleCore.SX:21,card?.spell?(card.radiusTiles||1)*RoyaleCore.SY:13,0,0,TAU);c.stroke();c.restore();}
 const levels=root.RoyaleLevelLabels?.plan(b.units,u=>b.isPresent(u)&&!u.hidden&&!u.burrowing&&!u.effectCarrier&&!u.attachedTo,compactSwarmLevels);
 const objs=[...b.towers,...b.units].sort((a,d)=>Number(a.air)-Number(d.air)||a.y-d.y);for(const raw of objs){const pos=root.RoyaleNative.renderPosition(raw,alpha),o=raw.king!==undefined?raw:{...raw,...pos};if(o.king!==undefined){tower(c,o,!o.localKing,visualTime);continue;}if(!b.isPresent(o))continue;c.save();c.globalAlpha=o.cloned?.58:o.invisible?.48:o.hidden?.25:1;const r=o.def.source;root.RoyalePresentation?.shadow(c,o);lib.unit(c,o.entity,o.x,o.y,o.team,visualTime,o.wait>0?'idle':(o.charged&&o.visualState==='run'?'charge':o.visualState||'idle'),o.heading,o.visualStarted||0,1,{elapsed:o.effectCarrier?Math.max(0,b.time-o.born):(o.animationTime??0),idleTime:o.visualTime??0,attackDuration:o.visualDuration,height:RoyaleNative.entityElevation(o),entity:o});
  root.RoyalePresentation?.health(c,o,visualTime,!levels||levels.individual.has(o.id));root.RoyalePresentation?.deployment(c,o,visualTime);
  c.restore();}
 for(const group of levels?.groups||[])root.RoyalePresentation?.groupLevel(c,group,alpha);
 if(placementForecast){drawSpellHighlights(c,placementForecast,visualTime,b,lib);drawTargetWarnings(c,placementForecast,visualTime);}
 for(const o of b.units.concat(b.towers)){if(!o.def.source.VariableDamage2||o.hp<=0||o.wait>0||o.visualState!=='attack'||o.buffs.Freeze||o.buffs.ZapFreeze)continue;
  const target=b.getEntity(o.targetId);if(!target||target.hp<=0||o.lockTime<=0)continue;
  if(fx?.beam(c,o,target,visualTime))continue;
  const fromY=o.y-RoyaleNative.entityElevation(o)-(o.building?45:22),toY=target.y-RoyaleNative.entityElevation(target)-(target.king!==undefined?50:target.building?32:20),power=Math.min(1,o.lockTime/4);
  line(c,o.x,fromY,target.x,toY,'#ff772acc',2.5+power*3);line(c,o.x,fromY,target.x,toY,'#ffed9b',1+power);
 }
 fx?.areas(c,b,'above');fx?.movement(c,b,'above');fx?.unitStates(c,b,'above');fx?.trails(c,b);
 for(const p of b.projectiles){if(!lib.drawProjectile(c,p,b.time,b)&&RoyaleCore.DATA.projectiles[p.name]?.FileName){line(c,p.x-p.vx*8,p.y-15-p.vy*8,p.x,p.y-15,p.team===0?'#b3e9ff':'#ffe0a5',3);}}
 fx?.events(c,b,'above');
 for(const e of b.effects){if(e.sourceEffect||e.sourceBeam||e.kind==='arrowsFly'&&fx)continue;if(lib.drawEffect(c,e,visualTime))continue;const progress=Math.max(0,Math.min(1,(visualTime-e.born)/e.ttl));c.save();c.globalAlpha=1-progress;if(e.kind==='beam'){line(c,e.x,e.y,e.tx,e.ty,'#97e7ff',4);line(c,e.x,e.y,e.tx,e.ty,'#f0fdff',1.2);}else if(e.kind==='impact'){for(let i=0;i<4;i++){const ang=i*1.57+progress;line(c,e.x+Math.cos(ang)*3,e.y-12+Math.sin(ang)*3,e.x+Math.cos(ang)*(4+progress*7),e.y-12+Math.sin(ang)*(4+progress*7),'#ffeabf',1.5);}}else if(e.kind==='cleave'){c.strokeStyle='#fff0b3';c.lineWidth=2;c.beginPath();c.ellipse(e.x,e.y-17,12+progress*10,7+progress*4,-.5,-.8,1.9);c.stroke();}else if(e.kind==='slash'){line(c,e.tx-10,e.ty-11,e.tx+11,e.ty+8,'#fff3bc',3);}else if(e.kind==='spawn'){c.strokeStyle='#e5f9ed';c.lineWidth=2;c.beginPath();c.ellipse(e.x,e.y,12+progress*20,6+progress*10,0,0,TAU);c.stroke();}else if(e.kind==='elixir'){text(c,'+1',e.x,e.y-progress*20,20,'#efb6ff');}else if(e.kind==='blast'){ellipse(c,e.x,e.y,(e.radius||20)*progress,(e.radius||20)*progress*.7,'#ffe7aa88');}c.restore();}
 root.RoyaleCustomArena?.drawForeground?.(c,b,lib,visualTime);
 // Owner health is a HUD overlay: keep it readable over the King's destruction dust.
 for(const t of b.towers)if(t.localKing)root.RoyalePresentation?.health(c,t,visualTime);
 c.restore();root.RoyaleUltra?.present(c);}
function diorama(c,time=0){c.clearRect(0,0,540,360);const lib=root.RoyaleNative?.library;if(!lib?.ready){text(c,lib?.error?'Asset load failed':'Loading original graphics…',270,180,20);return;}c.save();c.translate(34.8,75);c.transform(.78,-.07,.15,.39,0,0);lib.drawArena(c,time);c.restore();const project=(x,y)=>[270+(x-240)*.78+(y-320)*.15,183+(y-320)*.39-(x-240)*.07];for(const [x,y,team,king] of [[240,80,1,true],[118,118,1,false],[362,118,1,false],[118,522,0,false],[362,522,0,false],[240,560,0,true]]){const pt=project(x,y);c.save();c.translate(...pt);c.scale(.68,.68);lib.drawTower(c,{x:0,y:0,team,king,hp:1},time);c.restore();}for(const [x,y,id,team]of [[107,435,'knight',0],[355,238,'giant',1],[373,414,'archers',0]]){const pt=project(x,y);lib.unit(c,id,...pt,team,time,'idle',team?Math.PI/2:-Math.PI/2,0,.75);}}
root.RoyaleDraw={rounded,poly,ellipse,line,text,gradient,crown,droplet,gem,unit,card,tower,battle,diorama,drawPlacementBubble,drawPlacementLabel,drawTargetWarnings,drawSpellHighlights};
})(globalThis);
