/* Collection-strength model for local AI opponents. Card strength is sampled from
   collection development, not copied from the human deck. Rarity floors, unlock
   age, collection scarcity and league position all affect the result. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./catalog.js'):root.RoyaleCatalog,n?require('./progression.js'):root.RoyaleProgression);if(n)module.exports=api;else root.RoyaleLevelModel=api;})(globalThis,function(K,R){'use strict';
const MAX=13,clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const DEVELOPMENT=Object.freeze({1:.10,2:.17,3:.24,4:.31,5:.39,6:.47,7:.55,8:.62,9:.69,10:.75,11:.80,12:.85,13:.89,14:.92});
const KING_CENTER=Object.freeze({1:2.0,2:3.0,3:4.0,4:5.0,5:6.0,6:7.0,7:7.7,8:8.4,9:9.0,10:9.6,11:10.1,12:10.6,13:11.0,14:11.4});
const MASTER_INDEX=R.LEAGUES.findIndex(x=>x.name==='Master I');
const LEAGUE_RULES=R.LEAGUES.map((league,i)=>{const d=i-MASTER_INDEX;let max12=null,pStart=0,pEnd=0,king12=0;if(d===0){max12=4;pStart=.22;pEnd=.17;king12=.22;}else if(d===1){max12=3;pStart=.15;pEnd=.11;king12=.12;}else if(d===2){max12=2;pStart=.10;pEnd=.07;king12=.06;}else if(d===3){max12=1;pStart=.06;pEnd=.04;king12=.025;}else if(d===4){max12=1;pStart=.03;pEnd=.015;king12=.01;}else if(d>=5){max12=0;pStart=0;pEnd=0;king12=0;}return{...league,index:i,max12,pStart,pEnd,king12};});
function leagueForTrophies(t){const n=Math.max(0,Number(t)||0);return[...LEAGUE_RULES].reverse().find(x=>n>=x.trophies)||null;}
function randNormal(rng){let u=0,v=0;while(!u)u=rng();while(!v)v=rng();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);}
function rarityFloor(card){return K.baseLevel(card?.rarity||'Common');}
function cardArena(card){return Math.max(0,R.cardArenaNumber(card,K.DATA.arenas));}
function rarityScarcity(card){const row=K.DATA.rarities[card?.rarity]||K.DATA.rarities.Common,weight=Math.max(1,Number(row?.ChanceWeight)||1);return clamp(Math.log10(194/weight)/Math.log10(194),0,1);}
function acquisitionDifficulty(card,arena){const unlock=cardArena(card),age=Math.max(0,(Number(arena)||1)-unlock),newness=clamp(1-age/6,0,1),scarcity=rarityScarcity(card);return clamp(.20+.45*scarcity+.35*newness,.15,1);}
function displayedLevel(card,development){const min=rarityFloor(card);return clamp(Math.round(min+clamp(development,0,1)*(MAX-min)),min,MAX);}
function baseDevelopment(arena,trophies){const a=clamp(Math.floor(Number(arena)||1),1,14),t=Math.max(0,Number(trophies)||0),challenger=R.LEAGUES[0]?.trophies||5000,master=R.LEAGUES[MASTER_INDEX]?.trophies||6000;if(t>=master)return 1;if(t>=challenger){const x=clamp((t-challenger)/Math.max(1,master-challenger),0,1);return .91+.075*x;}return DEVELOPMENT[a]??.5;}
function rollAccountBias(rng){const x=rng();if(x<.06)return-.095-Math.abs(randNormal(rng))*.025;if(x>.94)return.070+Math.abs(randNormal(rng))*.020;return clamp(randNormal(rng)*.032,-.075,.075);}
function weightedPickIndices(cards,count,arena,rng){const pool=cards.map((card,i)=>({i,w:.35+acquisitionDifficulty(card,arena)})),out=[];while(pool.length&&out.length<count){let total=pool.reduce((s,x)=>s+x.w,0),r=rng()*total,k=0;for(;k<pool.length-1;k++){r-=pool[k].w;if(r<=0)break;}out.push(pool[k].i);pool.splice(k,1);}return out;}
function masterLevel12Count(trophies,deckSize,rng){const rule=leagueForTrophies(trophies);if(!rule||rule.max12===null)return null;if(rule.max12===0)return 0;const next=LEAGUE_RULES[rule.index+1],end=next?.trophies??rule.trophies+300,x=clamp((trophies-rule.trophies)/Math.max(1,end-rule.trophies),0,1),p=rule.pStart+(rule.pEnd-rule.pStart)*x;let count=0;for(let i=0;i<deckSize;i++)if(rng()<p)count++;return Math.min(rule.max12,count);}
function deckLevels({arena=1,trophies=0,cards=[],rng=Math.random,accountBias=null}={}){const a=clamp(Math.floor(Number(arena)||1),1,14),t=Math.max(0,Number(trophies)||0),rule=leagueForTrophies(t),master=R.LEAGUES[MASTER_INDEX]?.trophies||6000;if(t>=master&&rule?.max12!==null){const count=masterLevel12Count(t,cards.length,rng),lag=new Set(weightedPickIndices(cards,count,a,rng));return cards.map((card,i)=>({cardId:card.id,level:lag.has(i)?12:13,difficulty:acquisitionDifficulty(card,a)}));}
 const account=accountBias===null?rollAccountBias(rng):Number(accountBias)||0,base=baseDevelopment(a,t);return cards.map(card=>{const age=Math.max(0,a-cardArena(card)),difficulty=acquisitionDifficulty(card,a),ageLag=clamp((4-age)*.016,0,.064),scarcityLag=difficulty*.055,cardNoise=randNormal(rng)*.030,favorite=rng()<.12?.045:rng()<.10?-.040:0,outlier=rng()<.025?(rng()<.5?-.12:.09):0,development=clamp(base+account-ageLag-scarcityLag+cardNoise+favorite+outlier,0,1);return{cardId:card.id,level:displayedLevel(card,development),development,difficulty};});}
function levelMap(opts){return Object.fromEntries(deckLevels(opts).map(x=>[x.cardId,x.level]));}
function opponentTrophies(playerTrophies,rng=Math.random){const t=Math.max(0,Number(playerTrophies)||0),spread=t>=5000?140:t>=3000?120:90;return Math.max(0,Math.round(t+(rng()+rng()-1)*spread));}
function expectedKing(arena,trophies){const t=Math.max(0,Number(trophies)||0),master=R.LEAGUES[MASTER_INDEX]?.trophies||6000;if(t>=master)return 12.8;const challenger=R.LEAGUES[0]?.trophies||5000;if(t>=challenger)return 11.2+1.35*clamp((t-challenger)/Math.max(1,master-challenger),0,1);return KING_CENTER[clamp(Math.floor(Number(arena)||1),1,14)]||9;}
function kingLevel({arena=1,trophies=0,rng=Math.random}={}){const t=Math.max(0,Number(trophies)||0),rule=leagueForTrophies(t),master=R.LEAGUES[MASTER_INDEX]?.trophies||6000;if(t>=master&&rule?.max12!==null)return rule.king12>0&&rng()<rule.king12?12:13;return clamp(Math.round(expectedKing(arena,trophies)+randNormal(rng)*.55),1,13);}
return{MAX,DEVELOPMENT,KING_CENTER,LEAGUE_RULES,MASTER_INDEX,leagueForTrophies,rarityScarcity,acquisitionDifficulty,displayedLevel,baseDevelopment,rollAccountBias,masterLevel12Count,deckLevels,levelMap,opponentTrophies,expectedKing,kingLevel};
});
