/* Screenshot-led menus, with historical data and explicitly local practice actions. */
(function(root,factory){const n=typeof module==='object'&&module.exports;const api=factory(n?require('./core.js'):root.RoyaleCore,n?require('./cosmetics.js'):root.RoyaleCosmetics);if(n)module.exports=api;else root.RoyaleMenu=api;})(globalThis,function(C,Cos){'use strict';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const {emotes,towerSkins,magicItems,collectionSections}=Cos;
// Quantities and original USD reference values come from the uploaded billing_packages.csv.
// Values are displayed only in a historical reference note; this demo never processes payment.
const gemPacks=[['Fistful of Gems',80,99],['Pouch of Gems',500,499],['Bucket of Gems',1200,999],['Barrel of Gems',2500,1999],['Wagon of Gems',6500,4999],['Mountain of Gems',14000,9999]].map(([name,amount,referenceCents],i)=>({id:i,name,amount,referenceCents}));
function swapSlots(deck,a,b){const out=[...deck];if(Number.isInteger(a)&&Number.isInteger(b)&&a>=0&&b>=0&&a<out.length&&b<out.length)[out[a],out[b]]=[out[b],out[a]];return out;}
function filterCards(cards,query='',rarity='all',sort='rarity',levels={},excluded=[]){const excludedIds=new Set(excluded);const q=String(query).toLowerCase().trim(),order={Common:0,Rare:1,Epic:2,Legendary:3};return cards.filter(c=>!excludedIds.has(c.id)&&(rarity==='all'||c.rarity===rarity)&&(c.name+' '+c.rarity+' '+c.kind+' '+C.features(c).join(' ')).toLowerCase().includes(q)).sort((a,b)=>{if(sort==='name')return a.name.localeCompare(b.name);if(sort==='rarity')return order[a.rarity]-order[b.rarity]||a.cost-b.cost||a.name.localeCompare(b.name);if(sort==='type')return a.kind.localeCompare(b.kind)||a.cost-b.cost;if(sort==='level')return (levels[b.id]||9)-(levels[a.id]||9)||a.name.localeCompare(b.name);return a.cost-b.cost||a.name.localeCompare(b.name);});}
function refreshIn(now=Date.now(),windowMs=3600000){if(!Number.isFinite(now)||now<0||!Number.isFinite(windowMs)||windowMs<=0)return '';const seconds=Math.max(1,Math.ceil((windowMs-now%windowMs)/1000));return [Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(n=>String(n).padStart(2,'0')).join(':');}
function hourlyKey(now=Date.now()){return Math.floor(Math.max(0,Number(now)||0)/3600000);}
function rotating(items,now,count,salt){const hour=hourlyKey(now),pool=[...items];const random=C.rng(0x791924^salt);for(let i=pool.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}const start=(hour*count)%Math.max(1,pool.length);return Array.from({length:Math.min(count,pool.length)},(_,i)=>pool[(start+i)%pool.length]);}
function rotatingEmotes(now=Date.now(),count=3){return rotating(emotes.filter(e=>!e.free),now,count,311);}
function rotatingTowerSkins(now=Date.now(),count=3){return rotating(towerSkins.filter(s=>!s.free),now,count,741);}
function purchaseTowerSkin(raw,id,now=null,expectedHour=null){const p=C.normalizeProfile(raw),s=towerSkins.find(s=>s.id===id);if(!s||s.free)return{ok:false,profile:p,reason:'Unknown tower skin'};if(now!==null&&(hourlyKey(now)!==expectedHour||!rotatingTowerSkins(now).some(s=>s.id===id)))return{ok:false,profile:p,reason:'This offer expired. Refresh the shop.'};if(p.ownedTowerSkins.includes(id))return{ok:false,profile:p,reason:'Tower skin already owned'};if(p.gems<s.cost)return{ok:false,profile:p,reason:'Not enough gems'};p.gems-=s.cost;p.ownedTowerSkins.push(id);return{ok:true,profile:p};}
function selectTowerSkin(raw,id){const p=C.normalizeProfile(raw);if(!Cos.validSkin(id)||!p.ownedTowerSkins.includes(id))return{ok:false,profile:p,reason:'Unlock this tower skin first'};p.selectedTowerSkin=id;return{ok:true,profile:p};}
function equipEmote(raw,id){const p=C.normalizeProfile(raw);if(!p.ownedEmotes.includes(id))return{ok:false,profile:p,reason:'Unlock this emote first'};if(p.equippedEmotes.includes(id))p.equippedEmotes=p.equippedEmotes.filter(e=>e!==id);else {if(p.equippedEmotes.length>=8)p.equippedEmotes.pop();p.equippedEmotes.push(id);}return{ok:true,profile:p};}
function age(when,now=Date.now()){if(!Number.isFinite(Number(when))||!Number.isFinite(now))return 'Earlier';const min=Math.max(0,Math.floor((now-Number(when))/60000));if(min===0)return 'Just now';if(min<60)return min+'min ago';const h=Math.floor(min/60);return h<24?h+'h '+min%60+'min ago':Math.floor(h/24)+'d '+h%24+'h ago';}
function purchaseEmote(raw,id,now=null,expectedHour=null){const p=C.normalizeProfile(raw),e=emotes.find(e=>e.id===id);if(!e||e.free||e.roadOnly)return {ok:false,profile:p,reason:'Unknown shop emote'};if(now!==null&&(hourlyKey(now)!==expectedHour||!rotatingEmotes(now).some(e=>e.id===id)))return {ok:false,profile:p,reason:'This offer expired. Refresh the shop.'};if(p.ownedEmotes.includes(id))return {ok:false,profile:p,reason:'Emote already owned'};if(p.gems<e.cost)return {ok:false,profile:p,reason:'Not enough gems'};p.gems-=e.cost;p.ownedEmotes.push(id);return {ok:true,profile:p};}
function grantGemPack(raw,index){return{ok:false,profile:C.normalizeProfile(raw),reason:'Currency purchases are disabled.'};}
function swipeDirection(dx,dy,scale,elapsed){return [dx,dy,scale,elapsed].every(Number.isFinite)&&scale>0&&elapsed>=0&&elapsed<3500&&Math.abs(dx)>90*scale&&Math.abs(dx)>Math.abs(dy)*2?(dx<0?1:-1):0;}
return {collectionSections,towerSkins,magicItems,hourlyKey,rotatingEmotes,rotatingTowerSkins,purchaseTowerSkin,selectTowerSkin,equipEmote,swipeDirection,snapshot:C.DATA.snapshot,maxLevel:13,cardCount:C.CARDS.length,emotes,gemPacks,escape,swapSlots,filterCards,refreshIn,age,purchaseEmote,grantGemPack};
});
