/* Historical level-13 account XP progression for the supplied 3.2557.2-era data. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./catalog.js'):root.RoyaleCatalog);if(n)module.exports=api;else root.RoyalePlayerXP=api;})(globalThis,function(K){'use strict';
const MAX_KING_LEVEL=13;
const CUMULATIVE=Object.freeze({1:0,2:20,3:70,4:170,5:370,6:770,7:1770,8:3770,9:8770,10:18770,11:48770,12:88770,13:168770});
const TO_NEXT=Object.freeze({1:20,2:50,3:100,4:200,5:400,6:1000,7:2000,8:5000,9:10000,10:30000,11:40000,12:80000,13:0});
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
function levelFromTotalXp(total){const xp=Math.max(0,Math.floor(Number(total)||0));let level=1;for(let i=2;i<=MAX_KING_LEVEL;i++){if(xp>=CUMULATIVE[i])level=i;else break;}return level;}
function progressFromTotalXp(total){const totalXp=Math.max(0,Math.floor(Number(total)||0)),level=levelFromTotalXp(totalXp),maxLevel=level>=MAX_KING_LEVEL,start=CUMULATIVE[level],need=maxLevel?0:TO_NEXT[level],into=maxLevel?0:clamp(totalXp-start,0,need);return{level,kingLevel:level,totalXp:Math.min(totalXp,CUMULATIVE[13]),xpIntoLevel:into,xpNeededForNextLevel:need,xpRemaining:maxLevel?0:Math.max(0,need-into),progress01:maxLevel?1:clamp(into/Math.max(1,need),0,1),maxLevel};}
function legacyTotalXp(raw,fresh=false){if(Number.isFinite(Number(raw?.experience)))return clamp(Math.floor(Number(raw.experience)),0,CUMULATIVE[13]);if(fresh)return 0;const level=clamp(Math.floor(Number(raw?.kingLevel??raw?.level)||9),1,13);if(level>=13)return CUMULATIVE[13];const into=clamp(Math.floor(Number(raw?.xp)||0),0,Math.max(0,TO_NEXT[level]-1));return CUMULATIVE[level]+into;}
function sync(profile){profile.experience=clamp(Math.floor(Number(profile.experience)||0),0,CUMULATIVE[13]);const p=progressFromTotalXp(profile.experience);profile.kingLevel=p.level;profile.level=p.level;profile.xp=p.xpIntoLevel;profile.starPoints=Math.max(0,Math.floor(Number(profile.starPoints)||0));return p;}
function grant(profile,amount,reason='generic'){const add=Math.max(0,Math.floor(Number(amount)||0));sync(profile);if(!add)return{amount:0,xpApplied:0,overflowToStarPoints:0,...progressFromTotalXp(profile.experience)};const room=Math.max(0,CUMULATIVE[13]-profile.experience),xpApplied=Math.min(add,room),overflowToStarPoints=add-xpApplied,oldLevel=profile.level;profile.experience+=xpApplied;if(overflowToStarPoints)profile.starPoints+=overflowToStarPoints;const p=sync(profile);return{amount:add,xpApplied,overflowToStarPoints,oldKingLevel:oldLevel,newKingLevel:p.level,leveledUp:p.level>oldLevel,reason,...p};}
function rarityRow(cardOrRarity){const rarity=typeof cardOrRarity==='string'?cardOrRarity:cardOrRarity?.rarity;return K.DATA.rarities[rarity]||K.DATA.rarities[Object.keys(K.DATA.rarities).find(k=>k.toLowerCase()===String(rarity||'').toLowerCase())];}
function upgradeXp(card,currentLevel){const row=rarityRow(card);if(!row)return 0;const base=K.baseLevel(typeof card==='string'?card:card.rarity),idx=Math.max(0,Math.floor(Number(currentLevel)||base)-base);return Math.max(0,Math.floor(Number(row.UpgradeExp?.[idx])||0));}
function donationXp(card,count=1){const row=rarityRow(card);return Math.max(0,Math.floor(Number(row?.DonateXP)||0))*Math.max(0,Math.floor(Number(count)||0));}
return{MAX_KING_LEVEL,CUMULATIVE,TO_NEXT,levelFromTotalXp,progressFromTotalXp,legacyTotalXp,sync,grant,upgradeXp,donationXp};
});
