/* DOM views for the local world. The model owns inventory, dates and receipts;
   these views never mint currency or invent friends just because a page opens. */
(function(root){'use strict';
function create(ctx){
 const C=root.RoyaleCore,W=root.RoyaleWorld,War=root.RoyaleClanWar,U=root.RoyaleMenu,$=id=>document.getElementById(id),esc=U.escape,icon=ctx.icon,button=ctx.button,word=ctx.word;
 const p=()=>ctx.getProfile(),now=()=>Date.now(),fmt=n=>Math.floor(n||0).toLocaleString('en-US');let page=0,query='',hubTab='friends',warTab='river',edit=null;
 function mini(id){return `<span class="social-card-mini">${ctx.cardVisual(id)}</span>`;}
 function act(label,key,action,extra='',kind='blue'){return button(`${icon(key,'action-icon')}<span>${esc(label)}</span>`,action,kind,extra);}
 function left(at,t=now()){const s=Math.max(0,Math.ceil((at-t)/1000));return String(Math.floor(s/3600)).padStart(2,'0')+':'+String(Math.floor(s/60)%60).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
 function commit(r,label='',refresh=true){if(!r?.ok){ctx.toast(r?.reason||'Action unavailable');return false;}ctx.setProfile(r.profile);ctx.save();ctx.header();if(refresh){if(ctx.getScreen()==='clanChat')chat();else if(ctx.getScreen()==='clan')hub();}if(label)ctx.toast(label);if(r.reward)ctx.rewards(r.reward,'Clan Reward');return true;}
 function personRow(m,add=false){return `<div class="social-person"><button data-action="soc-profile" data-id="${m.id}" ${m.id==='self'?'disabled':''}>${icon(m.badge||'clan-badge','person-badge')}<span><b>${esc(m.name)}</b><small>${esc(m.role||m.tag||'')}${m.online?' · Online':''}</small></span><strong>${icon('trophy')}${fmt(m.trophies)}</strong></button>${add&&m.id!=='self'?button('Add','soc-add-friend','blue',`data-id="${m.id}" ${p().world.friends.includes(m.id)?'disabled':''}`):''}</div>`;}
 function clanRow(c){return `<button class="clan-directory-row" data-action="soc-clan" data-id="${c.id}">${icon(c.badge,'clan-directory-badge')}<span><b>${esc(c.name)}</b><small>${esc(c.type)} · ${c.count}/50 · ${esc(c.region||'')}</small></span><strong>${icon('trophy')}${fmt(c.trophies)}</strong></button>`;}
 function hub(){const profile=p(),cl=W.clan(profile,profile.world.currentClan),friends=profile.world.friends.map(id=>W.player(profile,id)).filter(Boolean).sort((a,b)=>Number(b.online)-Number(a.online)||b.trophies-a.trophies);
  $('clanContent').innerHTML=`<div class="social-hub">${cl?`<section class="social-clan-card">${icon(cl.badge)}<h2>${word(cl.name)}</h2><p>${esc(cl.description||'Welcome to the clan.')}</p><div class="clan-facts"><span>${cl.count}/50 members</span><span>${fmt(cl.trophies)} trophies</span></div><div class="social-actions">${act('Chat','emote-icon','soc-chat')}${act('Members','clan','soc-members')}${act('Clan Wars','event-war','soc-war')}</div></section>`:`<section class="social-clan-card"><h2>${word('Find your clan')}</h2><p>Meet players, exchange cards, and take part in Clan Wars.</p><div class="social-actions">${act('Find Clan','clan','soc-browse')}${act('Create','team-icon','soc-create','','green')}</div></section>`}
  <div class="social-tabs"><button data-action="soc-friends" class="${hubTab==='friends'?'selected':''}">Friends</button><button data-action="soc-browse" class="${hubTab==='browse'?'selected':''}">Clan Search</button></div>
  ${hubTab==='friends'?`<section id="friendsList">${friends.length?friends.map(m=>personRow(m)).join(''):'<div class="social-empty"><h3>No friends added yet</h3><p>Open a clanmate’s profile or an opponent’s profile in the Battle Log to add them.</p></div>'}</section>`:`<form id="clanSearchForm" class="clan-search"><input id="clanSearchQuery" aria-label="Search clans" maxlength="80" placeholder="Search by clan name or tag" value="${esc(query)}">${button('Search','soc-search','blue')}</form><div id="clanDirectory">${W.browseClans(profile,{query,page,limit:12}).map(clanRow).join('')||'<p class="social-empty">No matching clans.</p>'}</div><div class="social-pagination">${button('Previous','soc-prev','blue',page?'':'disabled')}<span>Page ${page+1}</span>${button('Next','soc-next','blue')}</div>`}</div>`;
  ctx.hydrate($('clanContent'));$('clanSearchForm')?.addEventListener('submit',e=>{e.preventDefault();query=$('clanSearchQuery').value;page=0;hub();});
 }
 function browse(){hubTab='browse';ctx.show('clan');}
 function profile(id){if(id==='self'){ctx.profileMenu();return;}const m=W.player(p(),id);if(!m)return;const cl=W.clan(p(),m.clanId),known=p().world.encountered.includes(id)||W.members(p(),p().world.currentClan).some(x=>x.id===id),friend=p().world.friends.includes(id);
  ctx.panel('social-profile',m.name,`<div class="social-profile-hero">${icon(m.badge)}<div><b>${esc(m.tag)}</b><p>King Level ${m.kingLevel} · ${fmt(m.trophies)} trophies</p>${cl?`<button class="small-link" data-action="soc-clan" data-id="${cl.id}">${esc(cl.name)}</button>`:'<span>No Clan</span>'}</div></div><div class="stats-grid"><div class="stat-box">Wins<b>${fmt(m.wins)}</b></div><div class="stat-box">Best trophies<b>${fmt(m.highestTrophies)}</b></div><div class="stat-box">Donations<b>${fmt(m.donations)}</b></div><div class="stat-box">Status<b>${m.online?'Online':U.age(m.lastActive)}</b></div></div><h3 class="social-section-title">Battle Deck</h3><div class="social-profile-deck">${m.deck.map(id=>`<div>${ctx.cardVisual(id)}<small>Level ${m.levels[id]}</small></div>`).join('')}</div><div class="social-actions">${button(friend?'Remove Friend':'Add Friend',friend?'soc-remove-friend':'soc-add-friend',friend?'blue':'green',`data-id="${id}" ${!known&&!friend?'disabled':''}`)}${button('Friendly Battle','soc-friendly','gold',`data-id="${id}"`)}</div>${!known&&!friend?'<p class="small center">Meet this player in battle or join their clan before adding them.</p>':''}`);
 }
 function clanPage(id){const cl=W.clan(p(),id);if(!cl)return;const joined=p().world.currentClan===id;ctx.panel('social-clan',cl.name,`<div class="social-profile-hero">${icon(cl.badge)}<div><b>${esc(cl.tag)}</b><p>${esc(cl.description)}</p></div></div><div class="clan-facts"><span>${cl.count}/50 members</span><span>${fmt(cl.trophies)} trophies</span><span>${esc(cl.type)}</span><span>Required: ${fmt(cl.requiredTrophies||0)}</span></div><div class="social-actions">${joined?act('Chat','emote-icon','soc-chat'):button('Join Clan','soc-join','green',`data-id="${id}" ${p().world.currentClan||cl.type!=='Open'||cl.count>=50||p().trophies<cl.requiredTrophies?'disabled':''}`)}${joined?act('Clan Wars','event-war','soc-war'):''}</div><h3 class="social-section-title">Members</h3><div class="social-member-list">${W.members(p(),id).map(m=>personRow(m)).join('')}</div>${joined&&cl.custom?button('Manage Clan','soc-manage','blue'):''}${joined?button('Leave Clan','soc-leave-confirm','danger'):''}`);}
 function createClan(){ctx.panel('social-create','Create Clan',`<div class="clan-create-form"><label>Name<input id="newClanName" maxlength="24" class="input" placeholder="Clan name"></label><label>Description<textarea id="newClanDescription" maxlength="200" class="input" placeholder="Tell prospective members about your clan"></textarea></label><label>Badge<select id="newClanBadge" class="input">${W.BADGES.map((b,i)=>`<option value="${i}">Badge ${i+1}</option>`).join('')}</select></label><div id="newClanBadgePreview" class="new-clan-badge">${icon(W.BADGES[0])}</div><label>Type<select id="newClanType" class="input"><option>Open</option><option>Invite Only</option><option>Closed</option></select></label><label>Required trophies<input id="newClanTrophies" type="number" value="0" min="0" max="8000" step="100" class="input"></label><p class="notice">A new clan begins with just you. Members may discover and join an Open clan over time. It has no earlier chat history.</p>${button(icon('gold')+' 1,000 · Create','soc-confirm-create','green')}</div>`);$('newClanBadge')?.addEventListener('change',()=>{$('newClanBadgePreview').innerHTML=icon(W.BADGES[Number($('newClanBadge').value)]);ctx.hydrate($('newClanBadgePreview'));});}
 function requestPanel(){const cards=C.CARDS.filter(c=>C.canUseCard(p(),c.id)&&c.rarity!=='Legendary');ctx.panel('social-request','Request Cards',`<p>Clanmates contribute actual card copies. Requests refresh every 7 hours; Epic cards can be requested on Sunday.</p><label>Card<select id="requestCardId" class="input">${cards.map(c=>`<option value="${c.id}">${esc(c.name)} · ${c.rarity}</option>`).join('')}</select></label><p class="notice">${p().world.requestAt>now()?'Next request in '+left(p().world.requestAt):'A request is available now.'}</p>${button('Request','soc-confirm-request','gold',p().world.requestAt>now()?'disabled':'')}`);}
 function tradePanel(){const cards=root.RoyaleEconomy.cardPool(p());ctx.panel('social-trade','Trade Cards',`<p>Choose a card to receive and up to four same-rarity options to give. The matching Trade Token is reserved until acceptance or cancellation.</p><label>Receive<select id="tradeWant" class="input">${cards.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Offer <small>(select up to 4)</small><select id="tradeGive" class="input" multiple size="6"></select></label><div id="tradeDetails" class="notice"></div>${button('Post Trade','soc-confirm-trade','green')}`);const update=()=>{const want=C.CARD_BY_ID[$('tradeWant').value],n=W.TRADE_COUNTS[want.rarity];$('tradeGive').innerHTML=cards.filter(c=>c.rarity===want.rarity&&c.id!==want.id).map(c=>`<option value="${c.id}" ${p().copies[c.id]<n?'disabled':''}>${esc(c.name)} · ${p().copies[c.id]}/${n}</option>`).join('');$('tradeDetails').textContent=`${want.rarity} · ${n} cards · ${p().tradeTokens[want.rarity]} Trade Tokens`;};$('tradeWant').addEventListener('change',update);update();}
 function renderRequest(q){if(!q)return'';const card=C.CARD_BY_ID[q.card];if(!card)return'';const can=q.owner!=='self'&&q.filled<q.total&&q.expiresAt>now()&&!q.donors?.self;
 return `<div class="chat-card-request">${mini(q.card)}<div><b>${esc(card.name)}</b><span>${q.filled} / ${q.total}</span><progress value="${q.filled}" max="${q.total}"></progress></div>${button(q.filled>=q.total?'Filled':q.donors?.self?'Donated':'Donate','soc-donate','green',`data-id="${q.id}" ${can?'':'disabled'}`)}</div>`;}
 function renderTrade(t){if(!t)return'';const receive=t.want;return `<div class="chat-trade">${mini(receive)}<span>${t.count} cards<br>${esc(C.CARD_BY_ID[receive]?.name||'')}<small>${esc(t.status)}</small></span><div class="trade-options">${t.give.map(mini).join('')}</div>${t.status==='open'?(t.owner==='self'?button('Cancel','soc-cancel-trade','blue',`data-id="${t.id}"`):button('Trade','soc-accept-trade','green',`data-id="${t.id}" data-card="${t.want}"`)):''}</div>`;}
 function chat(){const profile=p(),cl=W.clan(profile,profile.world.currentClan);if(!cl){ctx.show('clan');return;}const container=$('clanChatContent'),atBottom=container.scrollHeight-container.clientHeight-container.scrollTop<90,scroll=container.scrollTop;
  $('clanChat').classList.add('ecosystem-chat');$('clanChatHeader').innerHTML=`<button class="eco-chat-heading" data-action="soc-members">${icon(cl.badge)}<span><b>${esc(cl.name)}</b><small>${cl.count}/50 members · ${1+W.members(profile,cl.id).filter(x=>x.id!=='self'&&x.online).length} online</small></span></button>${act('War','event-war','soc-war')}`;
  container.innerHTML=cl.messages.length?cl.messages.slice().sort((a,b)=>a.time-b.time).map(m=>{const actor=m.actor==='self'?{name:profile.name}:W.player(profile,m.actor);if(m.kind==='system')return`<div class="eco-system-message">${esc(m.text)}</div>`;return`<article class="eco-chat-message ${m.actor==='self'?'mine':''}"><header><button data-action="soc-profile" data-id="${esc(m.actor)}">${esc(actor?.name||'Clanmate')}</button><time>${new Date(m.time).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}</time></header>${m.kind==='request'?renderRequest(cl.requests.find(q=>q.id===m.requestId)):m.kind==='trade'?renderTrade(cl.trades.find(t=>t.id===m.tradeId)):m.kind==='emote'?ctx.emoteVisual(m.emote,{play:true}):m.kind==='replay'?`<p>${esc(m.text)}</p>${act('Watch Replay','battle','soc-replay',`data-id="${esc(m.replayId)}"`)}`:`<p>${esc(m.text)}</p>`}</article>`;}).join(''):'<div class="social-empty"><h3>Your clan starts here</h3><p>There are no earlier messages. Introduce yourself and welcome new members as they arrive.</p></div>';
  $('clanChatActions').innerHTML=`<div class="eco-chat-actions">${act('Request','cards','soc-request','','gold')}${act('Trade','road-token-rare','soc-trade','','green')}${act('Friendly','challenge','soc-clan-friendly')}${act('Emotes','emote-icon','soc-emotes')}</div><form id="ecoChatForm" class="eco-chat-composer"><input id="ecoChatInput" class="input" maxlength="240" aria-label="Clan message" placeholder="Message your clan…">${button('Send','soc-send','blue')}</form>`;
  ctx.hydrate($('clanChat'));container.scrollTop=atBottom?container.scrollHeight:scroll;$('ecoChatForm').addEventListener('submit',e=>{e.preventDefault();send();});
 }
 function send(){const value=$('ecoChatInput')?.value;if(commit(W.postMessage(p(),value),'',false)){chat();$('ecoChatInput').focus();$('clanChatContent').scrollTop=$('clanChatContent').scrollHeight;}}
 function log(){ctx.panel('social-log','Battle Log',p().history.length?p().history.map(h=>`<article class="eco-battle-log"><header><b class="${h.winner===0?'win':'loss'}">${h.winner===0?'Victory':h.winner>=1?'Defeat':'Draw'}</b><span>${h.crowns[0]} – ${h.crowns[1]}</span><small>${esc(h.queue||h.mode)}</small></header><button class="log-opponent" data-action="soc-profile" data-id="${esc(h.opponent?.id||'')}" ${h.opponent?'':'disabled'}>${icon('clan-badge')}<span>${esc(h.opponent?.name||'Earlier opponent')}<small>${h.opponent?fmt(h.opponent.trophies)+' trophies':''}</small></span></button><div class="log-deck">${h.deck.map(mini).join('')}</div><footer><small>${esc(h.date.slice(0,10))} · ${Math.floor(h.duration/60)}:${String(h.duration%60).padStart(2,'0')}</small>${act('Replay','battle','soc-replay',`data-id="${esc(h.replayId)}" ${h.replayId?'':'disabled'}`)}${p().world.currentClan&&h.replayId?act('Share','cards','soc-share-replay',`data-id="${esc(h.replayId)}"`):''}</footer></article>`).join(''):'<p class="social-empty">Your completed battles will appear here.</p>');}
 function war(tab=warTab){warTab=tab;const advanced=War.advance(p());ctx.setProfile(advanced.profile);ctx.save();const v=War.view(p()),cal=v.calendar;if(!p().world.currentClan){browse();return;}
  let body='';if(tab==='river')body=`<div class="war-river">${v.rivals.map(c=>`<div class="war-boat-row ${c.id===p().world.currentClan?'own':''}">${icon(c.badge)}<div><b>${esc(c.name)}</b><small>${fmt(c.medals)} medals today</small><div class="war-river-track"><i style="width:${Math.min(100,c.movement/100)}%"></i></div><span>${fmt(c.movement)} / 10,000 Movement</span></div>${c.id!==p().world.currentClan?button('Defenses','soc-boat-list','blue',`data-id="${c.id}" ${cal.phase==='Training'||cal.colosseum?'disabled':''}`):''}</div>`).join('')}</div><div class="war-tasks">${act('1v1 Battle','battle','soc-war-select','data-kind="battle"','gold')}${act(v.duel&&!v.duel.finished?`Continue Duel ${v.duel.score[0]}–${v.duel.score[1]}`:'Duel','challenge','soc-war-select','data-kind="duel"','gold')}${act('Rotating Mode','event-double','soc-war-select','data-kind="rotating"','gold')}</div><p class="small">${cal.colosseum?'Colosseum week: Duels award bonus Clan Trophies. No boat attacks.':'Daily medals set the next movement award. Surviving defenses add bonus movement. Destroyed defenses stay down until next week.'}</p>${Object.values(v.tickets||{}).filter(t=>t.status==='playing').map(t=>`<p class="notice">An unfinished ${esc(t.kind)} is using Deck ${t.deckIndex+1}.</p>${button('Forfeit unfinished battle','soc-war-forfeit','danger',`data-id="${t.id}"`)}`).join('')}<h3 class="social-section-title">Weekly rewards</h3>${v.rewards.length?v.rewards.map(r=>`<div class="war-reward">${icon('magic-chest')}<span>River Chest · Place ${r.rank}</span>${button('Collect','soc-war-reward','green',`data-id="${r.id}"`)}</div>`).join(''):'<p class="small">Take part on a Battle Day to qualify for a River Chest at the end of the week.</p>'}`;
  if(tab==='decks')body=`<p class="notice">Four decks, 32 different owned cards. All cards and towers use Level 9 in war. Each deck is available once per day.</p><div class="war-deck-list">${v.decks.map((deck,i)=>`<article class="war-deck"><header><b>War Deck ${i+1}</b><span>${v.used.includes(i)?'Used today':deck.length===8?'Ready':deck.length+'/8'}</span></header><div class="log-deck">${deck.map(mini).join('')}</div>${button('Edit Deck','soc-edit-war-deck','blue',`data-index="${i}" ${v.used.includes(i)?'disabled':''}`)}</article>`).join('')}</div>${button('Auto-fill Unique Decks','soc-auto-war-decks','blue',v.used.length?'disabled':'')}`;
  if(tab==='defense'){const cards=War.defenseCards(p(),'self',now());body=`<p class="notice">Three towers carry four troop cards each. A tower wakes when damaged and summons its cards. Defenses can be edited on Training Days.</p><div class="war-deck-list">${cards.map((d,i)=>`<article class="war-deck"><h3>Defense Tower ${i+1}</h3><div class="log-deck four">${d.map(mini).join('')}</div></article>`).join('')}</div><div class="social-actions">${button('Edit Defense','soc-edit-defense','blue',cal.phase==='Training'?'':'disabled')}${button('Test Defense','soc-war-select','gold','data-kind="defense-test"')}</div>`;}
  if(tab==='trader'){const o=War.trader(p());body=`<p class="notice">${o.rarity} · ${o.count} cards per trade · ${p().tradeTokens[o.rarity]} Trade Tokens. One trade per day.</p><h3>Receive</h3><div class="trader-cards">${o.receive.map(mini).join('')}</div><select id="traderReceive" class="input">${o.receive.map(id=>`<option value="${id}">${esc(C.CARD_BY_ID[id].name)}</option>`).join('')}</select><h3>Give</h3><div class="trader-cards">${o.give.map(mini).join('')}</div><select id="traderGive" class="input">${o.give.map(id=>`<option value="${id}">${esc(C.CARD_BY_ID[id].name)} · ${p().copies[id]}</option>`).join('')}</select><div class="social-actions">${button(o.bought?'Traded Today':'Trade','soc-trader-exchange','green',o.bought||!o.receive.length?'disabled':'')}${button(icon('gems')+' 10 · Reroll Give','soc-trader-reroll','blue',o.bought?'disabled':'')}</div>`;}
  ctx.panel('social-war','Clan Wars',`<div class="war-phase"><b>${cal.colosseum?'Colosseum':cal.phase+' Days'} · Week ${cal.weekIndex+1}/${cal.weeksInSeason}</b><span>Deck reset <b data-war-reset="${cal.nextReset}">${left(cal.nextReset)}</b></span></div><div class="war-week-days">${['M','T','W','T','F','S','S'].map((d,i)=>`<span class="${i<3?'training':'battle'} ${i===cal.weekday?'current':''}">${d}</span>`).join('')}</div><div class="social-tabs four">${[['river','River'],['decks','War Decks'],['defense','Defenses'],['trader','Trader']].map(([id,n])=>`<button data-action="soc-war-tab" data-id="${id}" class="${tab===id?'selected':''}">${n}</button>`).join('')}</div>${v.reason?`<p class="notice">${esc(v.reason)}</p>`:''}${body}`);
 }
 function selectWar(kind,targetClan=null,defenseIndex=0){const v=War.view(p());ctx.panel('social-war-select',kind==='duel'?'Choose Duel Deck':'Choose War Deck',`<p>${kind==='duel'?'Best of three. Only decks actually played are consumed.':'All cards and towers will be Level 9.'}</p>${v.reason?`<p class="notice">${esc(v.reason)}</p>`:''}<div class="war-deck-list">${v.decks.map((deck,i)=>`<article class="war-deck"><h3>Deck ${i+1} · ${v.used.includes(i)?'Used today':'Ready'}</h3><div class="log-deck">${deck.map(mini).join('')}</div>${button('Battle','soc-start-war','gold',`data-kind="${kind}" data-index="${i}" data-clan="${targetClan||''}" data-defense="${defenseIndex}" ${v.reason||deck.length!==8||(v.used.includes(i)&&kind!=='defense-test')?'disabled':''}`)}</article>`).join('')}</div>`);}
 function boatList(id){const v=War.view(p()),cl=v.rivals.find(c=>c.id===id);if(!cl)return;ctx.panel('social-boats',cl.name,`<p>Attack a surviving defense. Damage persists between attacks; destroyed towers stay down for the week.</p>${(v.boats[id]||[]).map((d,i)=>`<article class="boat-defense-entry"><b>Defense ${i+1} · ${esc(W.player(p(),d.owner)?.name||'Clan defense')}</b><div class="boat-health">${d.hp.map(h=>`<span>${icon('boat-body')}<progress max="${d.maxHp}" value="${h}"></progress><small>${h>0?Math.ceil(h)+' HP':'Destroyed'}</small></span>`).join('')}</div>${button('Attack','soc-war-select','gold',`data-kind="boat" data-clan="${id}" data-defense="${i}" ${d.hp.every(h=>h<=0)?'disabled':''}`)}</article>`).join('')}`);}
 function editDeck(index,defense=false){const w=War.view(p());edit={index,defense,selected:defense?War.defenseCards(p(),'self',now()).flat():[...(w.decks[index]||[])]};paintEditor();}
 function paintEditor(){if(!edit)return;const count=edit.defense?12:8,v=War.view(p()),elsewhere=edit.defense?[]:v.decks.filter((_,i)=>i!==edit.index).flat(),cards=C.CARDS.filter(c=>C.canUseCard(p(),c.id)&&!elsewhere.includes(c.id)&&(!edit.defense||c.kind==='Troop'&&c.entity));
  ctx.panel('social-deck-editor',edit.defense?'Boat Defense':`War Deck ${edit.index+1}`,`<p>Select ${count} distinct cards. ${edit.defense?'Slots 1–4, 5–8 and 9–12 belong to the three towers.':'Cards already in another War Deck are excluded.'}</p><b>${edit.selected.length}/${count} selected</b><div class="war-editor-selected">${edit.selected.map(id=>`<button data-action="soc-editor-toggle" data-id="${id}">${mini(id)}</button>`).join('')}</div>${button('Save','soc-editor-save','green',edit.selected.length===count?'':'disabled')}<div class="war-editor-pool">${cards.map(c=>`<button class="${edit.selected.includes(c.id)?'selected':''}" data-action="soc-editor-toggle" data-id="${c.id}" ${!edit.selected.includes(c.id)&&edit.selected.length>=count?'disabled':''}>${mini(c.id)}<span>${esc(c.name)}</span></button>`).join('')}</div>`);}
 function clanManagement(){const cl=W.clan(p(),p().world.currentClan);if(!cl?.custom){clanPage(cl?.id);return;}ctx.panel('social-manage','Clan Settings',`<label>Description<textarea id="editClanDescription" maxlength="200" class="input">${esc(cl.description)}</textarea></label><label>Recruitment<select id="editClanType" class="input">${['Open','Invite Only','Closed'].map(t=>`<option ${cl.type===t?'selected':''}>${t}</option>`).join('')}</select></label>${button('Save','soc-save-clan','green')}<h3>Members</h3>${W.members(p(),cl.id).filter(m=>m.id!=='self').map(m=>`<div class="clan-manage-member"><b>${esc(m.name)}</b><span>${esc(m.role)}</span>${button('Promote','soc-promote','blue',`data-id="${m.id}"`)}${button('Kick','soc-kick','danger',`data-id="${m.id}"`)}</div>`).join('')||'<p>No other members yet.</p>'}`);}
 function tick(){for(const el of document.querySelectorAll('[data-war-reset]'))el.textContent=left(Number(el.dataset.warReset));}
 function handle(action,el){const id=el.dataset.id,index=Number(el.dataset.index);if(!action.startsWith('soc-'))return false;
  switch(action){
   case'soc-friends':hubTab='friends';ctx.show('clan');break;case'soc-browse':browse();break;case'soc-search':query=$('clanSearchQuery')?.value||'';page=0;hub();break;case'soc-next':page++;hub();break;case'soc-prev':page=Math.max(0,page-1);hub();break;
   case'soc-clan':clanPage(id);break;case'soc-members':clanPage(p().world.currentClan);break;case'soc-profile':profile(id);break;
   case'soc-add-friend':if(commit(W.addFriend(p(),id),'Friend added'))profile(id);break;case'soc-remove-friend':if(commit(W.removeFriend(p(),id),'Friend removed'))profile(id);break;
   case'soc-create':createClan();break;case'soc-confirm-create':if(commit(W.createClan(p(),{name:$('newClanName').value,description:$('newClanDescription').value,badge:Number($('newClanBadge').value),type:$('newClanType').value,requiredTrophies:Number($('newClanTrophies').value)}),'Clan created',false)){ctx.close();ctx.show('clanChat');}break;
   case'soc-join':if(commit(W.joinClan(p(),id),'Joined clan',false)){ctx.close();ctx.show('clanChat');}break;
   case'soc-leave-confirm':ctx.panel('social-leave','Leave Clan?',`<p>Leave this clan? Your friends, cards and battle history are kept.</p>${button('Leave','soc-leave','danger')}${button('Stay','close','blue')}`);break;
   case'soc-leave':if(commit(W.leaveClan(p()),'Left clan',false)){ctx.close();ctx.show('clan');}break;
   case'soc-chat':ctx.show('clanChat');break;case'soc-send':send();break;
   case'soc-request':requestPanel();break;case'soc-confirm-request':if(commit(W.requestCards(p(),$('requestCardId').value),'Request posted'))ctx.close();break;
   case'soc-donate':commit(W.donate(p(),id),'Cards donated');break;case'soc-trade':tradePanel();break;
   case'soc-confirm-trade':if(commit(W.postTrade(p(),$('tradeWant').value,[...$('tradeGive').selectedOptions].map(x=>x.value)),'Trade posted'))ctx.close();break;
   case'soc-cancel-trade':commit(W.cancelTrade(p(),id),'Trade cancelled');break;case'soc-accept-trade':commit(W.acceptTrade(p(),id,el.dataset.card),'Trade completed');break;
   case'soc-emotes':ctx.emotePicker();break;
   case'soc-friendly':{const opponent=W.player(p(),id);if(opponent)ctx.startBattle('Default',false,{queue:'friendly',opponent,enemyDeck:opponent.deck});break;}
   case'soc-clan-friendly':{const m=W.members(p(),p().world.currentClan).find(x=>x.id!=='self');if(m)ctx.startBattle('Default',false,{queue:'friendly',opponent:m,enemyDeck:m.deck});else ctx.toast('Your clan needs another member for a friendly battle');break;}
   case'soc-log':log();break;case'soc-replay':ctx.playReplay(id);break;
   case'soc-share-replay':{const h=p().history.find(x=>x.replayId===id);if(h){const c=W.clan(p(),p().world.currentClan);if(c){const next=C.normalizeProfile(p());c.messages.push({id:'share-'+(++next.world.serial),actor:'self',kind:'replay',text:`${p().name} vs ${h.opponent?.name||'Opponent'} · ${h.crowns[0]}–${h.crowns[1]}`,replayId:id,time:now()});next.world.clans[c.id]=c;commit({ok:true,profile:W.sync(next)},'Replay shared');ctx.close();ctx.show('clanChat');}}break;}
   case'soc-war':war();break;case'soc-war-tab':war(id);break;case'soc-war-select':selectWar(el.dataset.kind,el.dataset.clan||null,Number(el.dataset.defense)||0);break;
   case'soc-start-war':{const r=War.begin(p(),{kind:el.dataset.kind,deckIndex:index,targetClan:el.dataset.clan||null,defenseIndex:Number(el.dataset.defense)||0});if(commit(r,'',false)){ctx.close();ctx.startBattle(r.options.mode,false,r.options);}break;}
   case'soc-war-forfeit':if(commit(War.forfeit(p(),id),'Battle forfeited',false))war();break;case'soc-war-reward':commit(War.claimReward(p(),id),'River Chest collected',false);break;
   case'soc-edit-war-deck':editDeck(index);break;case'soc-auto-war-decks':if(commit(War.autoDecks(p()),'Unique war decks ready',false))war('decks');break;
   case'soc-boat-list':boatList(id);break;case'soc-edit-defense':editDeck(0,true);break;
   case'soc-editor-toggle':if(edit){edit.selected=edit.selected.includes(id)?edit.selected.filter(x=>x!==id):[...edit.selected,id];paintEditor();}break;
   case'soc-editor-save':if(edit){const r=edit.defense?War.setDefense(p(),[edit.selected.slice(0,4),edit.selected.slice(4,8),edit.selected.slice(8,12)]):War.setDeck(p(),edit.index,edit.selected);if(commit(r,'Saved',false)){const tab=edit.defense?'defense':'decks';edit=null;war(tab);}}break;
   case'soc-trader-exchange':if(commit(War.tradeWithTrader(p(),$('traderReceive').value,$('traderGive').value),'Trade completed',false))war('trader');break;
   case'soc-trader-reroll':if(commit(War.rerollTrader(p()),'Trader rerolled',false))war('trader');break;
   case'soc-manage':clanManagement();break;
   case'soc-save-clan':{const next=C.normalizeProfile(p()),cl=W.clan(next,next.world.currentClan);if(cl?.custom){cl.description=$('editClanDescription').value.slice(0,200);cl.type=$('editClanType').value;next.world.clans[cl.id]=cl;commit({ok:true,profile:W.sync(next)},'Clan settings saved');ctx.close();}break;}
   case'soc-promote':case'soc-kick':{const next=C.normalizeProfile(p()),cl=W.clan(next,next.world.currentClan);if(cl?.custom&&cl.memberIds.includes(id)){if(action==='soc-kick'){cl.memberIds=cl.memberIds.filter(x=>x!==id);cl.departed=[...new Set([...(cl.departed||[]),id])];}else{cl.roles=cl.roles||{};cl.roles[id]=cl.roles[id]==='Elder'?'Co-leader':cl.roles[id]==='Co-leader'?'Member':'Elder';}next.world.clans[cl.id]=cl;commit({ok:true,profile:W.sync(next)},'Member updated',false);clanManagement();}break;}
  }return true;
 }
 return{hub,browse,chat,profile,clanPage,createClan,requestPanel,tradePanel,war,log,clanManagement,handle,tick};
}
root.RoyaleSocialUI={create};
})(globalThis);
