/* Persistent local social simulation. Identities are generated from stable IDs; only
   interactions, membership changes and the player's friends occupy save space. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./core.js'):root.RoyaleCore,n?require('./progression.js'):root.RoyaleProgression,n?require('./world-state.js'):root.RoyaleWorldState,n?require('./training-decks.js'):root.RoyaleTrainingDecks,n?require('./level-model.js'):root.RoyaleLevelModel);if(n)module.exports=api;else root.RoyaleWorld=api;})(globalThis,function(C,R,S,Decks,Levels){'use strict';
const {PLAYER_COUNT,CLAN_COUNT,playerId,validPlayer,validClan}=S,DAY=86400000,HOUR=3600000;
const FIRST=['Royal','Moon','Frost','Iron','Crimson','Azure','Emerald','Solar','Golden','Shadow','Storm','Wild','Lucky','Silent','Swift','Ivory','Mighty','Tiny','Brave','Velvet','Neon','Copper','Oak','Misty','Night','Ember','Rogue','Silver','Atomic','Crystal','Pixel','Cobalt','Polar','River','Rising','Jade','Scarlet','Cosmic','Mellow','Flame'];
const LAST=['Knight','Falcon','Panda','Dragon','Fox','Wizard','Arrow','Tiger','Hawk','Raven','Golem','Hunter','Turtle','Bard','Ghost','Rider','Warden','Sparrow','Wolf','Guard','Phoenix','Otter','Giant','Ace','Sage','King','Queen','Nomad','Comet','Scout','Monarch','Lynx','Nova','Echo','Quill','Moth','Bison','Pilot','Ronin','Peach'];
const CLAN_NAMES=['Guardians','Royals','Raiders','Legion','Union','Kingdom','Alliance','Order','Voyagers','Sentinels','Brigade','Collective','Knights','Covenant','Warriors','Dynasty','Champions','Sanctuary','Council','Crew','Academy','Guild','Outpost','Squad','Horizons','Vanguard','Phantoms','Dragons','Citadel','Company','Keepers','Circle'];
const MOOD=['Friendly games and steady upgrades.','We donate before we request.','War decks ready; good sports welcome.','Casual ladder, serious teamwork.','Learning new decks together.','Push trophies at your own pace.','Active chat, clean battles.','Keep all four war decks different.','Returning players welcome.','Quality trades and good company.','Small wins add up.','Defense first, then counterpush.'];
const REGION=['International','North America','Europe','Oceania','South America','Asia'];
const BADGES=['clan-badge','event-war','team-icon','clan','classic-crown','challenge','battle','arena-7'];
function hash(x){let h=2166136261;for(const ch of String(x))h=Math.imul(h^ch.charCodeAt(0),16777619);h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;return h>>>0;}
function rnd(seed){return C.rng(hash(seed));}
function pick(a,h){return a[(h>>>0)%a.length];}
function clanId(n){return'c'+String(n).padStart(5,'0');}
function tag(n,prefix=''){const alphabet='0289PYLQGRJCUV';let out='';n+=10000000;do{out=alphabet[n%alphabet.length]+out;n=Math.floor(n/alphabet.length);}while(n);return '#'+prefix+out;}
function eligibleCard(p,id){const c=C.CARD_BY_ID[id];return !!c&&(C.DEFAULT_DECK.includes(id)||R.cardArenaNumber(c,C.DATA.arenas)<=R.highestArena(p).number);}
function receiveCopies(p,id,count){if(!eligibleCard(p,id)||!Number.isInteger(count)||count<1)return false;p.copies[id]=Math.min(100000,p.copies[id]+count);if(!p.unlockedCards.includes(id))p.unlockedCards.push(id);return true;}
function worldOf(p){return p?.world||S.normalize();}
function norm(p){return C.normalizeProfile(p);}
function fail(p,reason){return{ok:false,profile:p,reason};}
function freshTime(w,now){const t=Number.isFinite(now)?Math.max(0,Math.floor(now)):Date.now();return Math.max(w.clock||0,t);}
function baseClan(p,id,includeMembers=true){if(!validClan(id)||id[0]!=='c')return null;const n=Number(id.slice(1)),seed=worldOf(p).seed,h=hash(seed+':clan:'+n),center=100+(h%7700),count=12+(h>>>9)%37;
 return{id,tag:tag(n,'C'),name:pick(FIRST,h)+' '+pick(CLAN_NAMES,h>>>6)+' '+(1+Math.floor(n/1280)),badge:pick(BADGES,h>>>13),description:pick(MOOD,h>>>4)+' '+pick(MOOD,h>>>16),region:pick(REGION,h>>>21),type:h%9===0?'Invite Only':h%23===0?'Closed':'Open',requiredTrophies:Math.max(0,Math.floor((center-600)/100)*100),center,count,clanTrophies:Math.floor(center*.32),createdAt:0,custom:false,role:'Member',messages:[],requests:[],trades:[],memberIds:includeMembers?Array.from({length:count},(_,i)=>playerId(n*50+i)):[],departed:[]};
}
function identityBase(p,id){if(!validPlayer(id))return null;const n=Number(id.slice(1)),w=worldOf(p),h=hash(w.seed+':player:'+n),home=n<2500000?baseClan(p,clanId(Math.floor(n/50)),false):null;
 const inHome=home&&n%50<home.count,base=inHome?Math.max(0,Math.min(8000,home.center+(n%50===0?260:(h%601)-300))):(n%801)*10;
 // Activity varies by identity; deck and acquisition history do not mirror a matchup.
 const name=pick(FIRST,h)+pick(LAST,h>>>8)+(h%4===0?String((h>>>16)%999):h%7===0?'_'+(h%100):'');
 return{id,tag:tag(n),name,trophies:base,clanId:inHome?home.id:null,badge:home?.badge||'clan-badge',region:pick(REGION,h>>>20),seed:h,role:inHome?(n%50===0?'Leader':n%50<3?'Co-leader':n%50<7?'Elder':'Member'):'Member',ageDays:30+h%2000};
}
function player(p,id,now=Date.now()){
 const raw=identityBase(p,id);if(!raw)return null;const w=worldOf(p),t=Math.max(0,Number(now)||0),day=Math.floor(t/DAY),h=raw.seed,drift=(hash(h+':day:'+day)%81)-40;
 raw.trophies=Math.max(0,Math.min(8000,raw.trophies+drift+(w.players?.[id]?.trophies||0)));raw.highestTrophies=Math.min(8500,raw.trophies+50+(h%380));
 for(const [cid,cl] of Object.entries(w.clans||{})){if((cl.memberIds||[]).includes(id)){raw.clanId=cid;raw.role=cl.roles?.[id]||'Member';}else if(cl.departed?.includes(id)&&raw.clanId===cid)raw.clanId=null;}
 const arena=R.arenaForTrophies(raw.trophies).number;raw.arena=arena;raw.deck=Decks.randomDeck(h,arena);
 raw.levels=Levels.levelMap({arena,trophies:raw.trophies,cards:raw.deck.map(id=>C.CARD_BY_ID[id]),rng:rnd(h+':levels')});raw.kingLevel=Levels.kingLevel({arena,trophies:raw.trophies,rng:rnd(h+':king')});
 raw.wins=Math.floor(raw.ageDays*(.6+(h%90)/30));raw.matches=raw.wins+Math.floor(raw.wins*(.6+(h%60)/100));raw.donations=(h>>>3)%2500;
 const delta=w.players?.[id];if(delta){raw.wins+=delta.wins||0;raw.matches+=delta.matches||0;raw.donations+=delta.donations||0;}
 const hour=Math.floor(t/HOUR);raw.online=hash(h+':online:'+hour)%8<2;raw.lastActive=raw.online?t:t-(1+hash(h+':away:'+day)%72)*HOUR;
 return raw;
}
function clan(p,id,now=Date.now()){const w=worldOf(p),override=w.clans?.[id],base=id?.startsWith('c')?baseClan(p,id):null;if(!base&&!override)return null;const c={...(base||{}),...(override||{})};c.memberIds=[...(c.memberIds||[])];c.messages=[...(c.messages||[])];c.requests=[...(c.requests||[])].filter(q=>q&&C.CARD_BY_ID[q.card]);c.trades=[...(c.trades||[])].filter(t=>t&&C.CARD_BY_ID[t.want]&&t.give.every(id=>C.CARD_BY_ID[id]));c.count=c.memberIds.length+(w.currentClan===id?1:0);c.trophies=c.memberIds.slice(0,50).reduce((sum,id)=>sum+(identityBase(p,id)?.trophies||0),0);if(w.currentClan===id)c.trophies+=p.trophies;return c;}
function members(p,id,now=Date.now()){const cl=clan(p,id,now);if(!cl)return[];const out=cl.memberIds.map(id=>player(p,id,now)).filter(Boolean);if(worldOf(p).currentClan===id)out.unshift({id:'self',tag:'#YOU',name:p.name,trophies:p.trophies,kingLevel:p.level,deck:p.decks[p.activeDeck],role:cl.custom?'Leader':(cl.roles?.self||'Member'),online:true,donations:p.clan?.donations||0});return out.sort((a,b)=>b.trophies-a.trophies||a.id.localeCompare(b.id));}
function browseClans(p,{query='',page=0,limit=20,now=Date.now()}={}){const out=[],q=String(query).trim().toLowerCase(),seed=hash(worldOf(p).seed+':browse'),size=Math.min(100,Math.max(1,Number(limit)||20)),start=Math.max(0,Math.floor(page))*size;let matched=0;
 for(const id of Object.keys(worldOf(p).clans).filter(id=>id.startsWith('new-'))){const c=clan(p,id,now);if(q&&!((c.name+' '+c.tag+' '+c.description).toLowerCase().includes(q)))continue;if(matched++>=start)out.push(c);if(out.length>=size)return out;}
 for(let i=0;i<CLAN_COUNT&&out.length<size;i++){const n=(seed+i*7919)%CLAN_COUNT,id=clanId(n),c={...baseClan(p,id,false),...worldOf(p).clans[id]};
  if(q&&!((c.name+' '+c.tag+' '+c.description).toLowerCase().includes(q)))continue;if(matched++<start)continue;out.push(clan(p,id,now));
 }return out;
}
function matchOpponent(p,serial=worldOf(p).serial,now=Date.now()){
 const random=rnd(worldOf(p).seed+':match:'+serial),target=Math.max(0,Math.min(8000,p.trophies)),band=Math.floor(target/10),candidates=[];
 // The unaffiliated half of the population is indexed by trophy band for O(1) lookup.
 for(let k=0;k<12;k++){const offset=Math.floor(random()*17)-8,b=Math.max(0,Math.min(800,band+offset));const block=3122+Math.floor(random()*1869),n=block*801+b;if(n>=2500000&&n<PLAYER_COUNT)candidates.push(player(p,playerId(n),now));}
 // Established clan members are also encountered when their ranks are suitable.
 for(let k=0;k<64;k++){const n=Math.floor(random()*2500000),x=identityBase(p,playerId(n));if(Math.abs(x.trophies-target)<130)candidates.push(player(p,x.id,now));}
 candidates.sort((a,b)=>Math.abs(a.trophies-target)-Math.abs(b.trophies-target));return candidates[Math.min(candidates.length-1,Math.floor(random()*Math.min(5,candidates.length)))];
}
function sync(p){const w=p.world,cl=clan(p,w.currentClan,w.clock);p.clan=cl?{name:cl.name,badge:cl.badge,donations:p.clan?.donations||0,messages:cl.messages.slice(-50).map(m=>({kind:m.kind==='emote'?'emote':'text',emote:m.emote||null,name:m.actor==='self'?p.name:(identityBase(p,m.actor)?.name||'Clanmate'),text:String(m.text||'').slice(0,240),time:m.time,bot:m.actor!=='self'}))}:null;return p;}
function saveClan(p,c){c.messages=(c.messages||[]).slice(-100);c.requests=(c.requests||[]).slice(-24);c.trades=(c.trades||[]).slice(-24);p.world.clans[c.id]=c;return sync(p);}
function message(c,kind,text,actor,time,extra={}){const id='m-'+hash(c.id+':'+time+':'+text+':'+actor);if(!c.messages.some(m=>m.id===id))c.messages.push({id,kind,text,actor,time,...extra});c.messages=c.messages.slice(-100);}
function encounter(p,id){if(validPlayer(id)&&!p.world.encountered.includes(id))p.world.encountered.push(id);p.world.encountered=p.world.encountered.slice(-200);}
function addFriend(raw,id,now=Date.now()){const p=norm(raw);if(!validPlayer(id))return fail(p,'Player not found');if(p.world.friends.includes(id))return fail(p,'Already friends');if(p.world.friends.length>=200)return fail(p,'Friend list is full');const known=p.world.encountered.includes(id)||members(p,p.world.currentClan,now).some(m=>m.id===id);if(!known)return fail(p,'Meet this player in battle or in your clan first');p.world.friends.push(id);return{ok:true,profile:p};}
function removeFriend(raw,id){const p=norm(raw);if(!p.world.friends.includes(id))return fail(p,'Not on your friend list');p.world.friends=p.world.friends.filter(x=>x!==id);return{ok:true,profile:p};}
function seedConversation(p,c,now){const ids=c.memberIds;if(!ids.length)return;
 for(let i=0;i<4;i++){const at=now-(4-i)*(11+hash(c.id)%19)*60000,actor=ids[(i+hash(c.id))%ids.length];message(c,'text',contextLine(p,c,actor,at,i),actor,at);}
 spawnRequest(p,c,now-15*60000);c.lastChatAt=now;c.nextChatAt=now+(4+hash(c.id)%12)*60000;c.nextRequestAt=now+35*60000;
}
function joinClan(raw,id,now=Date.now()){let p=norm(raw);const time=freshTime(p.world,now),c=clan(p,id,time);if(p.world.currentClan)return fail(p,'Leave your current clan first');if(!c)return fail(p,'Clan not found');if(c.type!=='Open')return fail(p,c.type==='Closed'?'This clan is closed':'This clan requires an invitation');if(c.count>=50)return fail(p,'This clan is full');if(p.trophies<c.requiredTrophies)return fail(p,'Reach '+c.requiredTrophies+' trophies first');p.world.currentClan=id;p.world.clock=time;if(!p.world.epoch)p.world.epoch=time;if(!p.world.clans[id])seedConversation(p,c,time);c.roles=c.roles||{};c.roles.self='Member';message(c,'system',p.name+' joined the clan.','self',time);saveClan(p,c);return{ok:true,profile:p};}
function createClan(raw,{name='',description='',badge=0,type='Open',requiredTrophies=0}={},now=Date.now()){const p=norm(raw),time=freshTime(p.world,now);name=String(name).trim().slice(0,24);if(p.world.currentClan)return fail(p,'Leave your current clan first');if(name.length<3)return fail(p,'Clan names need at least 3 characters');if(p.gold<1000)return fail(p,'Creating a clan costs 1,000 gold');p.gold-=1000;const id='new-'+time.toString(36)+'-'+(p.world.serial++).toString(36),h=hash(p.world.seed+':'+id),fast=h%4===0;
 const c={id,tag:tag(h,'N'),name,description:String(description).trim().slice(0,200),badge:BADGES[Math.max(0,Math.floor(Number(badge)||0))%BADGES.length],region:'International',type:['Open','Invite Only','Closed'].includes(type)?type:'Open',requiredTrophies:Math.max(0,Math.min(8000,Number(requiredTrophies)||0)),clanTrophies:0,custom:true,createdAt:time,memberIds:[],departed:[],roles:{self:'Leader'},messages:[],requests:[],trades:[],recruitment:fast?'fast':'steady',nextJoinAt:time+(fast?2:12+(h%48))*HOUR,nextChatAt:time+DAY,nextRequestAt:time+DAY,serial:0};p.world.currentClan=id;p.world.clock=time;if(!p.world.epoch)p.world.epoch=time;saveClan(p,c);return{ok:true,profile:p};}
function leaveClan(raw,now=Date.now()){const p=norm(raw);if(!p.world.currentClan)return fail(p,'No clan joined');const c=clan(p,p.world.currentClan,now);if(c){for(const t of c.trades){if(t.owner==='self'&&t.status==='open'){t.status='cancelled';if(t.tokenReserved){p.tradeTokens[t.rarity]=Math.min(10000,p.tradeTokens[t.rarity]+1);t.tokenReserved=false;}}}message(c,'system',p.name+' left the clan.','self',freshTime(p.world,now));saveClan(p,c);}p.world.currentClan=null;p.clan=null;p.world.war=null;return{ok:true,profile:p};}
function postMessage(raw,text,now=Date.now(),emote=null){const p=norm(raw),c=clan(p,p.world.currentClan,now);if(!c)return fail(p,'Join a clan first');text=String(text||'').trim().slice(0,240);if(!text&&!emote)return fail(p,'Enter a message');if(emote&&!p.ownedEmotes.includes(emote))return fail(p,'Emote not owned');const time=freshTime(p.world,now);message(c,emote?'emote':'text',text,'self',time,emote?{emote}:{});if(c.memberIds.length){c.replyAt=time+(15+hash(text+time)%90)*1000;c.replyTo=text;}saveClan(p,c);return{ok:true,profile:p};}
function requestLimit(p){const a=R.highestArena(p).number;return a>=10?40:a>=7?30:a>=4?20:10;}
function spawnRequest(p,c,time,forcedCard){if(!c.memberIds.length)return;const serial=(c.serial||0)+1;c.serial=serial;const owner=c.memberIds[serial%c.memberIds.length],person=player(p,owner,time);let eligible=person.deck.map(id=>C.CARD_BY_ID[id]).filter(x=>['Common','Rare'].includes(x.rarity));if(!eligible.length)return;const card=forcedCard||eligible[hash(c.id+':request:'+serial)%eligible.length].id;const count=C.CARD_BY_ID[card].rarity==='Common'?40:4;const request={id:'req-'+hash(c.id+':'+serial+':'+time),owner,card,total:count,filled:0,createdAt:time,expiresAt:time+7*HOUR,donors:{}};c.requests.push(request);message(c,'request','Requested '+C.CARD_BY_ID[card].name,owner,time,{requestId:request.id,card});}
function requestCards(raw,id,now=Date.now()){const p=norm(raw),time=freshTime(p.world,now),c=clan(p,p.world.currentClan,time),card=C.CARD_BY_ID[id];if(!c)return fail(p,'Join a clan first');if(!card||!C.canUseCard(p,id))return fail(p,'Unlock this card first');if(card.rarity==='Legendary')return fail(p,'Legendary cards can be traded, not requested');if(time<p.world.requestAt)return fail(p,'Next request in '+Math.ceil((p.world.requestAt-time)/60000)+' minutes');if(card.rarity==='Epic'&&new Date(time).getUTCDay()!==0)return fail(p,'Epic requests are available on Sundays');const sunday=Math.floor(time/DAY);if(card.rarity==='Epic'&&p.world.lastEpicSunday===sunday)return fail(p,'Your Epic Sunday request is already used');if(card.rarity==='Epic')p.world.lastEpicSunday=sunday;const total=card.rarity==='Common'?requestLimit(p):requestLimit(p)/10;
 const request={id:'selfreq-'+(++p.world.serial),owner:'self',card:id,total,filled:0,createdAt:time,expiresAt:time+7*HOUR,nextDonationAt:time+45000,donors:{}};p.world.requestAt=time+7*HOUR;c.requests.push(request);message(c,'request','Requested '+card.name,'self',time,{requestId:request.id,card:id});saveClan(p,c);return{ok:true,profile:p,request};}
function donate(raw,id,now=Date.now()){const p=norm(raw),time=freshTime(p.world,now),c=clan(p,p.world.currentClan,time),q=c?.requests.find(x=>x.id===id);if(!q||q.owner==='self'||q.expiresAt<time||q.filled>=q.total)return fail(p,'Request is no longer available');if(q.donors?.self)return fail(p,'Already donated to this request');const card=C.CARD_BY_ID[q.card];if(!card||!C.canUseCard(p,q.card))return fail(p,'Unlock this card first');const arena=R.highestArena(p).number,cap=arena>=10?360:arena>=7?270:arena>=4?180:90,day=Math.floor(time/DAY);if(p.world.donationDay!==day){p.world.donationDay=day;p.world.dailyDonated=0;}const max=card.rarity==='Common'?(arena>=10?8:arena>=7?6:arena>=4?4:1):1,amount=Math.min(max,q.total-q.filled,p.copies[q.card],cap-p.world.dailyDonated);if(amount<1)return fail(p,'No spare cards or daily donation limit reached');p.copies[q.card]-=amount;p.world.dailyDonated+=amount;p.gold=Math.min(9999999,p.gold+amount*(card.rarity==='Common'?5:card.rarity==='Rare'?50:500));const xp=C.grantDonationXp(p,q.card,amount);p.experience=xp.profile.experience;p.level=xp.profile.level;p.kingLevel=p.level;p.xp=xp.profile.xp;p.starPoints=xp.profile.starPoints;q.filled+=amount;q.donors={...(q.donors||{}),self:amount};p.clan.donations+=amount;saveClan(p,c);return{ok:true,profile:p,count:amount,xpEarned:xp.xpEarned};}
const TRADE_COUNTS={Common:250,Rare:50,Epic:10,Legendary:1};
function postTrade(raw,want,give,now=Date.now()){const p=norm(raw),c=clan(p,p.world.currentClan,now),card=C.CARD_BY_ID[want],options=[...new Set(Array.isArray(give)?give:[])];if(!c)return fail(p,'Join a clan first');if(!card||!eligibleCard(p,want)||options.length<1||options.length>4)return fail(p,'Choose one received card and 1–4 offered cards');const n=TRADE_COUNTS[card.rarity];if(options.some(id=>id===want||!C.CARD_BY_ID[id]||C.CARD_BY_ID[id].rarity!==card.rarity||!C.canUseCard(p,id)||p.copies[id]<n))return fail(p,'Offer spare cards of the same rarity');if(p.tradeTokens[card.rarity]<1)return fail(p,'A matching Trade Token is required');if(c.trades.some(t=>t.owner==='self'&&t.status==='open'))return fail(p,'Finish or cancel your current trade');const time=freshTime(p.world,now);p.tradeTokens[card.rarity]--;const trade={id:'trade-'+(++p.world.serial),owner:'self',want,give:options,rarity:card.rarity,count:n,status:'open',createdAt:time,acceptAt:time+(10+hash(c.id+time)%90)*60000,expiresAt:time+DAY,tokenReserved:true};c.trades.push(trade);message(c,'trade','Trade: '+card.name,'self',time,{tradeId:trade.id,card:want});saveClan(p,c);return{ok:true,profile:p,trade};}
function cancelTrade(raw,id){const p=norm(raw),c=clan(p,p.world.currentClan),t=c?.trades.find(t=>t.id===id);if(!t||t.owner!=='self'||t.status!=='open')return fail(p,'Trade is no longer open');t.status='cancelled';if(t.tokenReserved){p.tradeTokens[t.rarity]++;t.tokenReserved=false;}saveClan(p,c);return{ok:true,profile:p};}
function acceptTrade(raw,id,give,now=Date.now()){const p=norm(raw),c=clan(p,p.world.currentClan,now),t=c?.trades.find(x=>x.id===id);if(!t||t.owner==='self'||t.status!=='open'||t.expiresAt<now)return fail(p,'Trade unavailable');if(give!==t.want||!C.canUseCard(p,give)||p.copies[give]<t.count||p.tradeTokens[t.rarity]<1)return fail(p,'Not enough matching cards or tokens');const receive=t.give[0];if(!eligibleCard(p,receive))return fail(p,'Reach the offered card’s arena first');p.tradeTokens[t.rarity]--;p.copies[give]-=t.count;receiveCopies(p,receive,t.count);t.status='completed';t.partner='self';saveClan(p,c);return{ok:true,profile:p};}
function aiTrade(p,c,time){if(!c.memberIds.length)return;const m=player(p,c.memberIds[(c.serial||0)%c.memberIds.length],time),pool=m.deck.filter(id=>C.CARD_BY_ID[id].rarity==='Common');if(pool.length<2)return;const h=hash(c.id+':trade:'+time),want=pool[h%pool.length],give=pool.filter(x=>x!==want)[0],t={id:'aitrade-'+h,owner:m.id,want,give:[give],rarity:'Common',count:250,status:'open',createdAt:time,expiresAt:time+DAY};c.trades.push(t);message(c,'trade','Trade: '+C.CARD_BY_ID[want].name,m.id,time,{tradeId:t.id,card:want});}
const CHAT=['Good luck on ladder today.','I finally got that upgrade.','Anyone have spare cards for a trade?','Nice defense in that last game.','Saving my spells for the counterpush.','Going to use the other lane this time.','My war decks are ready.','Thanks for the donations!','Trying a cheaper cycle deck.','That was close.','Back for a couple of games.','Remember to donate before you request.','Taking a break, see you later.','I keep meeting air decks today.','Friendly battle after donations?','Still working on my defense.','Two wins and I am done for now.'];
function contextLine(p,c,actor,time,index=0){
 const m=player(p,actor,time);if(!m)return pick(CHAT,hash(c.id+time));
 const h=hash(actor+':line:'+time+':'+index),a=m.deck[h%8],b=m.deck[(h%8+3)%8],name=C.CARD_BY_ID[a].name,other=C.CARD_BY_ID[b].name;
 const average=(m.deck.reduce((n,id)=>n+C.CARD_BY_ID[id].cost,0)/8).toFixed(1);
 const lines=[`Anyone playing ${name} today?`,`Trying to make ${name} and ${other} work together.`,
 `My deck is ${average} elixir. Still getting used to the cycle.`,`Saving my gold for ${name}.`,
 `Working toward ${Math.ceil((m.trophies+1)/100)*100} trophies.`,`Might switch ${name} out after a few games.`,
 `Any tips for defending with ${other}?`,`Keeping ${name} at level ${m.levels[a]} for now.`,
 `I need a friendly to practice this ${name} deck.`,`Taking a break from ladder. Anyone around for a friendly?`,
 `I will check the card requests before my next game.`,`Still deciding which deck to take into the Duel.`,
 `Playing a few games before I head off.`,`I tend to spend too much elixir defending. Need to work on that.`,
 `The ${other} slot is the one I keep changing.`,`Four different decks makes war interesting.`,...CHAT];
 return pick(lines,h>>>7);
}
function replyTo(text,c){const s=String(text).toLowerCase();if(/hello|hi\b|hey|welcome/.test(s))return 'Hey! Welcome in. What deck are you playing?';if(/donat|request/.test(s))return 'I will check the requests. Thanks for helping out.';if(/war|duel/.test(s))return 'I saved a few decks for war. Good luck with your battles.';if(/trade|token/.test(s))return 'Post the trade and I will take a look when I have the cards.';if(/gg|well played|win/.test(s))return 'Well played! Keep it going.';return pick(CHAT,hash(s+c.id));}
function recruit(p,c,seed,time){
 const minBand=Math.min(800,Math.ceil((c.requiredTrophies+40)/10));
 for(let i=0;i<30;i++){const h=hash(seed+':candidate:'+i),band=minBand+h%Math.max(1,801-minBand);let n=2500000+h%1499000;n+=(band-n%801+801)%801;const id=playerId(n);
  if(c.memberIds.includes(id)||c.departed?.includes(id)||Object.values(p.world.clans).some(other=>other.id!==c.id&&other.memberIds?.includes(id)))continue;
  const person=player(p,id,time);if(person&&person.trophies>=c.requiredTrophies)return id;
 }return null;
}
function advance(raw,now=Date.now()){
 const p=norm(raw),w=p.world,time=freshTime(w,now);if(time<=w.clock)return{profile:p,changed:false};let changed=false;
 // Preserve the player's former local clan on upgrade, but not the old shell's
 // fabricated members/history. Migration is not a new paid clan creation.
 if(!w.epoch&&!w.currentClan&&!w.retiredLegacyClan&&p.clan){
  const legacy=p.clan,name=String(legacy.name||'My Clan').padEnd(3,' ').trim();
  const migrated=createClan({...p,clan:null,gold:Math.max(1000,p.gold)},{name:name.length>=3?name:'My Clan'},time);
  if(migrated.ok){Object.assign(w,migrated.profile.world);w.retiredLegacyClan=true;
   const restored=clan(p,w.currentClan,time);p.clan=legacy;
   for(const m of legacy.messages||[])if(!m.bot)message(restored,m.kind==='emote'?'emote':'text',String(m.text||''),'self',m.time||time,m.emote?{emote:m.emote}:{});
   saveClan(p,restored);changed=true;
  }
 }
 if(!w.epoch)w.epoch=time;const c=clan(p,w.currentClan,time);
 if(c){
  if(c.custom&&c.type==='Open'&&c.memberIds.length<49){let guard=0;while(c.nextJoinAt&&c.nextJoinAt<=time&&c.memberIds.length<49&&guard++<49){const at=c.nextJoinAt,h=hash(c.id+':join:'+c.memberIds.length),id=playerId(2500000+h%1500000);const newcomer=recruit(p,c,c.id+':'+at,at);if(newcomer){c.memberIds.push(newcomer);message(c,'system',(identityBase(p,newcomer)?.name||'A player')+' joined the clan.',newcomer,at);changed=true;}c.nextJoinAt=at+(c.recruitment==='fast'?3+h%16:24+h%110)*HOUR;c.nextChatAt=Math.min(c.nextChatAt||Infinity,at+7*60000);c.nextRequestAt=Math.min(c.nextRequestAt||Infinity,at+12*60000);}}
  if(c.memberIds.length){
   if(c.replyAt&&c.replyAt<=time){message(c,'text',replyTo(c.replyTo,c),c.memberIds[hash(c.replyTo)%c.memberIds.length],c.replyAt);c.replyAt=0;changed=true;}
   // At most the recent 24 hours of generated chatter is materialized after a long absence.
   let at=Math.max(c.nextChatAt||time+HOUR,time-DAY),guard=0;while(at<=time&&guard++<24){const h=hash(c.id+':chat:'+at),actor=c.memberIds[h%c.memberIds.length];message(c,'text',contextLine(p,c,actor,at),actor,at);at+=(15+h%80)*60000;changed=true;}c.nextChatAt=at;
   if((c.nextRequestAt||time+HOUR)<=time){const at=Math.max(c.nextRequestAt,time-2*HOUR);spawnRequest(p,c,at);if(hash(c.id+':trades:'+Math.floor(time/DAY))%3!==0)aiTrade(p,c,at+1);c.nextRequestAt=time+(45+hash(time)%180)*60000;changed=true;}
  }
  for(const q of c.requests){if(q.owner!=='self'||q.filled>=q.total||q.createdAt>=time)continue;let guard=0;while(c.memberIds.length&&q.nextDonationAt<=Math.min(time,q.expiresAt)&&q.filled<q.total&&guard++<60){const donor=c.memberIds[(q.donationCursor||0)%c.memberIds.length];q.donationCursor=(q.donationCursor||0)+1;const person=identityBase(p,donor),card=C.CARD_BY_ID[q.card],eligible=C.DEFAULT_DECK.includes(q.card)||R.cardArenaNumber(card,C.DATA.arenas)<=R.arenaForTrophies(person.trophies).number;if(eligible){const donorArena=R.arenaForTrophies(person.trophies).number,cap=card.rarity==='Common'?(donorArena>=10?8:donorArena>=7?6:donorArena>=4?4:1):1,count=Math.max(0,Math.min(card.rarity==='Common'?4:1,q.total-q.filled,cap-(q.donors[donor]||0)));if(count){q.filled+=count;p.copies[q.card]=Math.min(100000,p.copies[q.card]+count);q.donors[donor]=(q.donors[donor]||0)+count;const delta=p.world.players[donor]||(p.world.players[donor]={trophies:0,wins:0,matches:0,donations:0});delta.donations+=count;changed=true;}}q.nextDonationAt+=((q.total<=4?12:5)+(hash(donor+q.id)%7))*60000;}}
  for(const t of c.trades){if(t.status!=='open'||t.owner!=='self')continue;if(t.expiresAt<time&&(!t.acceptAt||t.acceptAt>t.expiresAt)){t.status='expired';if(t.tokenReserved){p.tradeTokens[t.rarity]++;t.tokenReserved=false;}changed=true;continue;}if(t.acceptAt<=time){const giver=t.give.find(id=>p.copies[id]>=t.count),partner=c.memberIds.find(id=>{const x=identityBase(p,id);return C.DEFAULT_DECK.includes(t.want)||R.cardArenaNumber(C.CARD_BY_ID[t.want],C.DATA.arenas)<=R.arenaForTrophies(x.trophies).number;});if(giver&&partner){p.copies[giver]-=t.count;receiveCopies(p,t.want,t.count);t.status='completed';t.partner=partner;t.receivedFromPlayer=giver;t.tokenReserved=false;message(c,'trade-complete',(identityBase(p,partner)?.name||'Clanmate')+' accepted your trade.',partner,t.acceptAt,{tradeId:t.id});changed=true;}else if(time>=t.expiresAt){t.status='expired';if(t.tokenReserved){p.tradeTokens[t.rarity]++;t.tokenReserved=false;}changed=true;}}}
  saveClan(p,c);
 }
 w.clock=time;return{profile:sync(p),changed};
}
function recordResult(raw,battle){const p=norm(raw),id=battle.opponent?.id;
 if(battle.queueType!=='trophy-road'||battle.practice||battle.isReplay||Object.values(battle.cheats||{}).some(Boolean)||!battle.result||!validPlayer(id)||p.world.lastOpponentResult===battle.id)return p;
 const delta=p.world.players[id]||(p.world.players[id]={trophies:0,wins:0,matches:0,donations:0});
 delta.matches++;if(battle.result.winner===1){delta.wins++;delta.trophies=Math.min(8000,delta.trophies+30);}else if(battle.result.winner===0)delta.trophies=Math.max(-8000,delta.trophies-20);
 p.world.lastOpponentResult=battle.id;return p;
}
function recordOpponent(raw,opponent){const p=norm(raw);if(opponent?.id)encounter(p,opponent.id);return p;}
return{PLAYER_COUNT,CLAN_COUNT,DAY,HOUR,BADGES,TRADE_COUNTS,hash,playerId,clanId,player,clan,members,browseClans,matchOpponent,addFriend,removeFriend,joinClan,createClan,leaveClan,postMessage,requestCards,donate,postTrade,cancelTrade,acceptTrade,advance,recordOpponent,recordResult,sync};});
